/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 150/hour (free) or 500/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type DeleteListTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 150/hour (free) or 500/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class DeleteListTooManyRequestsError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: DeleteListTooManyRequestsErrorData;

  constructor(
    err: DeleteListTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "DeleteListTooManyRequestsError";
  }
}

/**
 * Unauthorized
 */
export type ResponseBodyError2Data = {
  message?: string | undefined;
};

/**
 * Unauthorized
 */
export class ResponseBodyError2 extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: ResponseBodyError2Data;

  constructor(
    err: ResponseBodyError2Data,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ResponseBodyError2";
  }
}

/**
 * Wishlist
 */
export type ResponseBodyError1Data = {
  message?: string | undefined;
};

/**
 * Wishlist
 */
export class ResponseBodyError1 extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: ResponseBodyError1Data;

  constructor(
    err: ResponseBodyError1Data,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ResponseBodyError1";
  }
}

export type Forbidden = ResponseBodyError1 | ResponseBodyError2;

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type DeleteListUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class DeleteListUnauthorizedError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: DeleteListUnauthorizedErrorData;

  constructor(
    err: DeleteListUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "DeleteListUnauthorizedError";
  }
}

/** @internal */
export const DeleteListTooManyRequestsError$inboundSchema: z.ZodMiniType<
  DeleteListTooManyRequestsError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new DeleteListTooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ResponseBodyError2$inboundSchema: z.ZodMiniType<
  ResponseBodyError2,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ResponseBodyError2(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ResponseBodyError1$inboundSchema: z.ZodMiniType<
  ResponseBodyError1,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ResponseBodyError1(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const Forbidden$inboundSchema: z.ZodMiniType<Forbidden, unknown> =
  smartUnion([
    z.lazy(() => ResponseBodyError1$inboundSchema),
    z.lazy(() => ResponseBodyError2$inboundSchema),
  ]);

export function forbiddenFromJSON(
  jsonString: string,
): SafeParseResult<Forbidden, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Forbidden$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Forbidden' from JSON`,
  );
}

/** @internal */
export const DeleteListUnauthorizedError$inboundSchema: z.ZodMiniType<
  DeleteListUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new DeleteListUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
