/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 150/hour (free) or 500/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type EditReadingDateTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 150/hour (free) or 500/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class EditReadingDateTooManyRequestsError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: EditReadingDateTooManyRequestsErrorData;

  constructor(
    err: EditReadingDateTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "EditReadingDateTooManyRequestsError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type EditReadingDateUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class EditReadingDateUnauthorizedError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: EditReadingDateUnauthorizedErrorData;

  constructor(
    err: EditReadingDateUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "EditReadingDateUnauthorizedError";
  }
}

/** @internal */
export const EditReadingDateTooManyRequestsError$inboundSchema: z.ZodMiniType<
  EditReadingDateTooManyRequestsError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new EditReadingDateTooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const EditReadingDateUnauthorizedError$inboundSchema: z.ZodMiniType<
  EditReadingDateUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new EditReadingDateUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
