/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type GetSeriesIssuesTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class GetSeriesIssuesTooManyRequestsError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetSeriesIssuesTooManyRequestsErrorData;

  constructor(
    err: GetSeriesIssuesTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetSeriesIssuesTooManyRequestsError";
  }
}

/**
 * PRO Required
 */
export type GetSeriesIssuesPaymentRequiredErrorData = {
  message?: string | undefined;
  error?: string | undefined;
  upgradeUrl?: string | undefined;
};

/**
 * PRO Required
 */
export class GetSeriesIssuesPaymentRequiredError extends VerseDbError {
  error?: string | undefined;
  upgradeUrl?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetSeriesIssuesPaymentRequiredErrorData;

  constructor(
    err: GetSeriesIssuesPaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.upgradeUrl != null) this.upgradeUrl = err.upgradeUrl;

    this.name = "GetSeriesIssuesPaymentRequiredError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type GetSeriesIssuesUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class GetSeriesIssuesUnauthorizedError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetSeriesIssuesUnauthorizedErrorData;

  constructor(
    err: GetSeriesIssuesUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetSeriesIssuesUnauthorizedError";
  }
}

/** @internal */
export const GetSeriesIssuesTooManyRequestsError$inboundSchema: z.ZodMiniType<
  GetSeriesIssuesTooManyRequestsError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSeriesIssuesTooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetSeriesIssuesPaymentRequiredError$inboundSchema: z.ZodMiniType<
  GetSeriesIssuesPaymentRequiredError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    error: types.optional(types.string()),
    upgrade_url: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "upgrade_url": "upgradeUrl",
    });

    return new GetSeriesIssuesPaymentRequiredError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetSeriesIssuesUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetSeriesIssuesUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSeriesIssuesUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
