/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type GetVariantDetailsTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class GetVariantDetailsTooManyRequestsError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetVariantDetailsTooManyRequestsErrorData;

  constructor(
    err: GetVariantDetailsTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetVariantDetailsTooManyRequestsError";
  }
}

/**
 * Not Found
 */
export type GetVariantDetailsNotFoundErrorData = {
  error?: string | undefined;
};

/**
 * Not Found
 */
export class GetVariantDetailsNotFoundError extends VerseDbError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetVariantDetailsNotFoundErrorData;

  constructor(
    err: GetVariantDetailsNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetVariantDetailsNotFoundError";
  }
}

/**
 * PRO Required
 */
export type GetVariantDetailsPaymentRequiredErrorData = {
  message?: string | undefined;
  error?: string | undefined;
  upgradeUrl?: string | undefined;
};

/**
 * PRO Required
 */
export class GetVariantDetailsPaymentRequiredError extends VerseDbError {
  error?: string | undefined;
  upgradeUrl?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetVariantDetailsPaymentRequiredErrorData;

  constructor(
    err: GetVariantDetailsPaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.upgradeUrl != null) this.upgradeUrl = err.upgradeUrl;

    this.name = "GetVariantDetailsPaymentRequiredError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type GetVariantDetailsUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class GetVariantDetailsUnauthorizedError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetVariantDetailsUnauthorizedErrorData;

  constructor(
    err: GetVariantDetailsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetVariantDetailsUnauthorizedError";
  }
}

/** @internal */
export const GetVariantDetailsTooManyRequestsError$inboundSchema: z.ZodMiniType<
  GetVariantDetailsTooManyRequestsError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetVariantDetailsTooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetVariantDetailsNotFoundError$inboundSchema: z.ZodMiniType<
  GetVariantDetailsNotFoundError,
  unknown
> = z.pipe(
  z.object({
    error: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetVariantDetailsNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetVariantDetailsPaymentRequiredError$inboundSchema: z.ZodMiniType<
  GetVariantDetailsPaymentRequiredError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    error: types.optional(types.string()),
    upgrade_url: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "upgrade_url": "upgradeUrl",
    });

    return new GetVariantDetailsPaymentRequiredError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetVariantDetailsUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetVariantDetailsUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetVariantDetailsUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
