/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type GetSeriesForASpecificTeamTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class GetSeriesForASpecificTeamTooManyRequestsError
  extends VerseDbError
{
  /** The original data that was passed to this error instance. */
  data$: GetSeriesForASpecificTeamTooManyRequestsErrorData;

  constructor(
    err: GetSeriesForASpecificTeamTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetSeriesForASpecificTeamTooManyRequestsError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type GetSeriesForASpecificTeamUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class GetSeriesForASpecificTeamUnauthorizedError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetSeriesForASpecificTeamUnauthorizedErrorData;

  constructor(
    err: GetSeriesForASpecificTeamUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetSeriesForASpecificTeamUnauthorizedError";
  }
}

/** @internal */
export const GetSeriesForASpecificTeamTooManyRequestsError$inboundSchema:
  z.ZodMiniType<GetSeriesForASpecificTeamTooManyRequestsError, unknown> = z
    .pipe(
      z.object({
        message: types.string(),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetSeriesForASpecificTeamTooManyRequestsError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetSeriesForASpecificTeamUnauthorizedError$inboundSchema:
  z.ZodMiniType<GetSeriesForASpecificTeamUnauthorizedError, unknown> = z.pipe(
    z.object({
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetSeriesForASpecificTeamUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
