/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type GetSeriesDetailsTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class GetSeriesDetailsTooManyRequestsError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetSeriesDetailsTooManyRequestsErrorData;

  constructor(
    err: GetSeriesDetailsTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetSeriesDetailsTooManyRequestsError";
  }
}

/**
 * Not Found
 */
export type GetSeriesDetailsNotFoundErrorData = {
  message?: string | undefined;
};

/**
 * Not Found
 */
export class GetSeriesDetailsNotFoundError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetSeriesDetailsNotFoundErrorData;

  constructor(
    err: GetSeriesDetailsNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetSeriesDetailsNotFoundError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type GetSeriesDetailsUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class GetSeriesDetailsUnauthorizedError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetSeriesDetailsUnauthorizedErrorData;

  constructor(
    err: GetSeriesDetailsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetSeriesDetailsUnauthorizedError";
  }
}

/** @internal */
export const GetSeriesDetailsTooManyRequestsError$inboundSchema: z.ZodMiniType<
  GetSeriesDetailsTooManyRequestsError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSeriesDetailsTooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetSeriesDetailsNotFoundError$inboundSchema: z.ZodMiniType<
  GetSeriesDetailsNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSeriesDetailsNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetSeriesDetailsUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetSeriesDetailsUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSeriesDetailsUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
