/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewTooManyRequestsErrorData =
  {
    message: string;
  };

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewTooManyRequestsError
  extends VerseDbError
{
  /** The original data that was passed to this error instance. */
  data$:
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewTooManyRequestsErrorData;

  constructor(
    err:
      GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name =
      "GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewTooManyRequestsError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewUnauthorizedErrorData =
  {
    message: string;
  };

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewUnauthorizedError
  extends VerseDbError
{
  /** The original data that was passed to this error instance. */
  data$:
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewUnauthorizedErrorData;

  constructor(
    err:
      GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name =
      "GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewUnauthorizedError";
  }
}

/** @internal */
export const GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewTooManyRequestsError$inboundSchema:
  z.ZodMiniType<
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewTooManyRequestsError,
    unknown
  > = z.pipe(
    z.object({
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewTooManyRequestsError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    }),
  );

/** @internal */
export const GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewUnauthorizedError$inboundSchema:
  z.ZodMiniType<
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewUnauthorizedError,
    unknown
  > = z.pipe(
    z.object({
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewUnauthorizedError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    }),
  );
