/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type GetSeriesCharactersTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class GetSeriesCharactersTooManyRequestsError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetSeriesCharactersTooManyRequestsErrorData;

  constructor(
    err: GetSeriesCharactersTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetSeriesCharactersTooManyRequestsError";
  }
}

/**
 * PRO Required
 */
export type GetSeriesCharactersPaymentRequiredErrorData = {
  message?: string | undefined;
  error?: string | undefined;
  upgradeUrl?: string | undefined;
};

/**
 * PRO Required
 */
export class GetSeriesCharactersPaymentRequiredError extends VerseDbError {
  error?: string | undefined;
  upgradeUrl?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetSeriesCharactersPaymentRequiredErrorData;

  constructor(
    err: GetSeriesCharactersPaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.upgradeUrl != null) this.upgradeUrl = err.upgradeUrl;

    this.name = "GetSeriesCharactersPaymentRequiredError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type GetSeriesCharactersUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class GetSeriesCharactersUnauthorizedError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetSeriesCharactersUnauthorizedErrorData;

  constructor(
    err: GetSeriesCharactersUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetSeriesCharactersUnauthorizedError";
  }
}

/** @internal */
export const GetSeriesCharactersTooManyRequestsError$inboundSchema:
  z.ZodMiniType<GetSeriesCharactersTooManyRequestsError, unknown> = z.pipe(
    z.object({
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetSeriesCharactersTooManyRequestsError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetSeriesCharactersPaymentRequiredError$inboundSchema:
  z.ZodMiniType<GetSeriesCharactersPaymentRequiredError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      error: types.optional(types.string()),
      upgrade_url: types.optional(types.string()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      const remapped = remap$(v, {
        "upgrade_url": "upgradeUrl",
      });

      return new GetSeriesCharactersPaymentRequiredError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetSeriesCharactersUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetSeriesCharactersUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSeriesCharactersUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
