/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type GetSeriesCreatorsTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class GetSeriesCreatorsTooManyRequestsError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetSeriesCreatorsTooManyRequestsErrorData;

  constructor(
    err: GetSeriesCreatorsTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetSeriesCreatorsTooManyRequestsError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type GetSeriesCreatorsUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class GetSeriesCreatorsUnauthorizedError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetSeriesCreatorsUnauthorizedErrorData;

  constructor(
    err: GetSeriesCreatorsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetSeriesCreatorsUnauthorizedError";
  }
}

/** @internal */
export const GetSeriesCreatorsTooManyRequestsError$inboundSchema: z.ZodMiniType<
  GetSeriesCreatorsTooManyRequestsError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSeriesCreatorsTooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetSeriesCreatorsUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetSeriesCreatorsUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSeriesCreatorsUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
