/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type GetIssueVariantsTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class GetIssueVariantsTooManyRequestsError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetIssueVariantsTooManyRequestsErrorData;

  constructor(
    err: GetIssueVariantsTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetIssueVariantsTooManyRequestsError";
  }
}

/**
 * PRO Required
 */
export type GetIssueVariantsPaymentRequiredErrorData = {
  message?: string | undefined;
  error?: string | undefined;
  upgradeUrl?: string | undefined;
};

/**
 * PRO Required
 */
export class GetIssueVariantsPaymentRequiredError extends VerseDbError {
  error?: string | undefined;
  upgradeUrl?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetIssueVariantsPaymentRequiredErrorData;

  constructor(
    err: GetIssueVariantsPaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.upgradeUrl != null) this.upgradeUrl = err.upgradeUrl;

    this.name = "GetIssueVariantsPaymentRequiredError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type GetIssueVariantsUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class GetIssueVariantsUnauthorizedError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetIssueVariantsUnauthorizedErrorData;

  constructor(
    err: GetIssueVariantsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetIssueVariantsUnauthorizedError";
  }
}

/** @internal */
export const GetIssueVariantsTooManyRequestsError$inboundSchema: z.ZodMiniType<
  GetIssueVariantsTooManyRequestsError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetIssueVariantsTooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetIssueVariantsPaymentRequiredError$inboundSchema: z.ZodMiniType<
  GetIssueVariantsPaymentRequiredError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    error: types.optional(types.string()),
    upgrade_url: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "upgrade_url": "upgradeUrl",
    });

    return new GetIssueVariantsPaymentRequiredError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetIssueVariantsUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetIssueVariantsUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetIssueVariantsUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
