/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type GetCharacterIssuesTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class GetCharacterIssuesTooManyRequestsError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetCharacterIssuesTooManyRequestsErrorData;

  constructor(
    err: GetCharacterIssuesTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetCharacterIssuesTooManyRequestsError";
  }
}

/**
 * PRO subscription required (User API only)
 */
export type GetCharacterIssuesPaymentRequiredErrorData = {
  message?: string | undefined;
  error?: string | undefined;
  upgradeUrl?: string | undefined;
};

/**
 * PRO subscription required (User API only)
 */
export class GetCharacterIssuesPaymentRequiredError extends VerseDbError {
  error?: string | undefined;
  upgradeUrl?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetCharacterIssuesPaymentRequiredErrorData;

  constructor(
    err: GetCharacterIssuesPaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.upgradeUrl != null) this.upgradeUrl = err.upgradeUrl;

    this.name = "GetCharacterIssuesPaymentRequiredError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type GetCharacterIssuesUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class GetCharacterIssuesUnauthorizedError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetCharacterIssuesUnauthorizedErrorData;

  constructor(
    err: GetCharacterIssuesUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetCharacterIssuesUnauthorizedError";
  }
}

/** @internal */
export const GetCharacterIssuesTooManyRequestsError$inboundSchema:
  z.ZodMiniType<GetCharacterIssuesTooManyRequestsError, unknown> = z.pipe(
    z.object({
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetCharacterIssuesTooManyRequestsError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetCharacterIssuesPaymentRequiredError$inboundSchema:
  z.ZodMiniType<GetCharacterIssuesPaymentRequiredError, unknown> = z.pipe(
    z.object({
      message: types.optional(types.string()),
      error: types.optional(types.string()),
      upgrade_url: types.optional(types.string()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      const remapped = remap$(v, {
        "upgrade_url": "upgradeUrl",
      });

      return new GetCharacterIssuesPaymentRequiredError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetCharacterIssuesUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetCharacterIssuesUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetCharacterIssuesUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
