/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Not Found
 */
export type GetASpecificTitleNotFoundErrorData = {
  message?: string | undefined;
};

/**
 * Not Found
 */
export class GetASpecificTitleNotFoundError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: GetASpecificTitleNotFoundErrorData;

  constructor(
    err: GetASpecificTitleNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetASpecificTitleNotFoundError";
  }
}

/** @internal */
export const GetASpecificTitleNotFoundError$inboundSchema: z.ZodMiniType<
  GetASpecificTitleNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetASpecificTitleNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
