/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Not Found
 */
export type GetVariantDetailsNotFoundErrorData = {
  error?: string | undefined;
};

/**
 * Not Found
 */
export class GetVariantDetailsNotFoundError extends VerseDbError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetVariantDetailsNotFoundErrorData;

  constructor(
    err: GetVariantDetailsNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetVariantDetailsNotFoundError";
  }
}

/** @internal */
export const GetVariantDetailsNotFoundError$inboundSchema: z.ZodMiniType<
  GetVariantDetailsNotFoundError,
  unknown
> = z.pipe(
  z.object({
    error: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetVariantDetailsNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
