/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Already On Loan
 */
export type LendACopyOutConflictErrorData = {
  message?: string | undefined;
};

/**
 * Already On Loan
 */
export class LendACopyOutConflictError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: LendACopyOutConflictErrorData;

  constructor(
    err: LendACopyOutConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "LendACopyOutConflictError";
  }
}

/**
 * Not Owner
 */
export type LendACopyOutNotFoundErrorData = {
  message?: string | undefined;
};

/**
 * Not Owner
 */
export class LendACopyOutNotFoundError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: LendACopyOutNotFoundErrorData;

  constructor(
    err: LendACopyOutNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "LendACopyOutNotFoundError";
  }
}

/** @internal */
export const LendACopyOutConflictError$inboundSchema: z.ZodMiniType<
  LendACopyOutConflictError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new LendACopyOutConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const LendACopyOutNotFoundError$inboundSchema: z.ZodMiniType<
  LendACopyOutNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new LendACopyOutNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
