/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type ListAllPublishersWithOptionalSearchTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class ListAllPublishersWithOptionalSearchTooManyRequestsError
  extends VerseDbError
{
  /** The original data that was passed to this error instance. */
  data$: ListAllPublishersWithOptionalSearchTooManyRequestsErrorData;

  constructor(
    err: ListAllPublishersWithOptionalSearchTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ListAllPublishersWithOptionalSearchTooManyRequestsError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type ListAllPublishersWithOptionalSearchUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class ListAllPublishersWithOptionalSearchUnauthorizedError
  extends VerseDbError
{
  /** The original data that was passed to this error instance. */
  data$: ListAllPublishersWithOptionalSearchUnauthorizedErrorData;

  constructor(
    err: ListAllPublishersWithOptionalSearchUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ListAllPublishersWithOptionalSearchUnauthorizedError";
  }
}

/** @internal */
export const ListAllPublishersWithOptionalSearchTooManyRequestsError$inboundSchema:
  z.ZodMiniType<
    ListAllPublishersWithOptionalSearchTooManyRequestsError,
    unknown
  > = z.pipe(
    z.object({
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ListAllPublishersWithOptionalSearchTooManyRequestsError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ListAllPublishersWithOptionalSearchUnauthorizedError$inboundSchema:
  z.ZodMiniType<ListAllPublishersWithOptionalSearchUnauthorizedError, unknown> =
    z.pipe(
      z.object({
        message: types.string(),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new ListAllPublishersWithOptionalSearchUnauthorizedError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );
