/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type ListAllPodcastsWithOptionalSearchTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class ListAllPodcastsWithOptionalSearchTooManyRequestsError
  extends VerseDbError
{
  /** The original data that was passed to this error instance. */
  data$: ListAllPodcastsWithOptionalSearchTooManyRequestsErrorData;

  constructor(
    err: ListAllPodcastsWithOptionalSearchTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ListAllPodcastsWithOptionalSearchTooManyRequestsError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type ListAllPodcastsWithOptionalSearchUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class ListAllPodcastsWithOptionalSearchUnauthorizedError
  extends VerseDbError
{
  /** The original data that was passed to this error instance. */
  data$: ListAllPodcastsWithOptionalSearchUnauthorizedErrorData;

  constructor(
    err: ListAllPodcastsWithOptionalSearchUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ListAllPodcastsWithOptionalSearchUnauthorizedError";
  }
}

/** @internal */
export const ListAllPodcastsWithOptionalSearchTooManyRequestsError$inboundSchema:
  z.ZodMiniType<
    ListAllPodcastsWithOptionalSearchTooManyRequestsError,
    unknown
  > = z.pipe(
    z.object({
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ListAllPodcastsWithOptionalSearchTooManyRequestsError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ListAllPodcastsWithOptionalSearchUnauthorizedError$inboundSchema:
  z.ZodMiniType<ListAllPodcastsWithOptionalSearchUnauthorizedError, unknown> = z
    .pipe(
      z.object({
        message: types.string(),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new ListAllPodcastsWithOptionalSearchUnauthorizedError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );
