/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export type ListKeyIssueReasonsTooManyRequestsErrorData = {
  message: string;
};

/**
 * Rate limit exceeded. This endpoint allows 300/hour (free) or 1,000/hour (PRO). Wait for the number of seconds in the `Retry-After` header before retrying.
 */
export class ListKeyIssueReasonsTooManyRequestsError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: ListKeyIssueReasonsTooManyRequestsErrorData;

  constructor(
    err: ListKeyIssueReasonsTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ListKeyIssueReasonsTooManyRequestsError";
  }
}

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export type ListKeyIssueReasonsUnauthorizedErrorData = {
  message: string;
};

/**
 * Unauthenticated. The bearer token is missing, invalid, or revoked.
 */
export class ListKeyIssueReasonsUnauthorizedError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: ListKeyIssueReasonsUnauthorizedErrorData;

  constructor(
    err: ListKeyIssueReasonsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ListKeyIssueReasonsUnauthorizedError";
  }
}

/** @internal */
export const ListKeyIssueReasonsTooManyRequestsError$inboundSchema:
  z.ZodMiniType<ListKeyIssueReasonsTooManyRequestsError, unknown> = z.pipe(
    z.object({
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ListKeyIssueReasonsTooManyRequestsError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ListKeyIssueReasonsUnauthorizedError$inboundSchema: z.ZodMiniType<
  ListKeyIssueReasonsUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ListKeyIssueReasonsUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
