/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Not a Lunar or Universal Code
 */
export type LookupByDistributorCodeUnprocessableEntityErrorData = {
  message?: string | undefined;
};

/**
 * Not a Lunar or Universal Code
 */
export class LookupByDistributorCodeUnprocessableEntityError
  extends VerseDbError
{
  /** The original data that was passed to this error instance. */
  data$: LookupByDistributorCodeUnprocessableEntityErrorData;

  constructor(
    err: LookupByDistributorCodeUnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "LookupByDistributorCodeUnprocessableEntityError";
  }
}

/**
 * Multiple Matches
 */
export type LookupByDistributorCodeConflictErrorData = {
  message?: string | undefined;
  count?: number | undefined;
  totalCount?: number | undefined;
  matches?: Array<operations.LookupByDistributorCodeMatch> | undefined;
};

/**
 * Multiple Matches
 */
export class LookupByDistributorCodeConflictError extends VerseDbError {
  count?: number | undefined;
  totalCount?: number | undefined;
  matches?: Array<operations.LookupByDistributorCodeMatch> | undefined;

  /** The original data that was passed to this error instance. */
  data$: LookupByDistributorCodeConflictErrorData;

  constructor(
    err: LookupByDistributorCodeConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.count != null) this.count = err.count;
    if (err.totalCount != null) this.totalCount = err.totalCount;
    if (err.matches != null) this.matches = err.matches;

    this.name = "LookupByDistributorCodeConflictError";
  }
}

/**
 * Not Found
 */
export type LookupByDistributorCodeNotFoundErrorData = {
  message?: string | undefined;
};

/**
 * Not Found
 */
export class LookupByDistributorCodeNotFoundError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: LookupByDistributorCodeNotFoundErrorData;

  constructor(
    err: LookupByDistributorCodeNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "LookupByDistributorCodeNotFoundError";
  }
}

/**
 * Missing Ability
 */
export type LookupByDistributorCodeForbiddenErrorData = {
  message?: string | undefined;
};

/**
 * Missing Ability
 */
export class LookupByDistributorCodeForbiddenError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: LookupByDistributorCodeForbiddenErrorData;

  constructor(
    err: LookupByDistributorCodeForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "LookupByDistributorCodeForbiddenError";
  }
}

/** @internal */
export const LookupByDistributorCodeUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<LookupByDistributorCodeUnprocessableEntityError, unknown> = z
    .pipe(
      z.object({
        message: types.optional(types.string()),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new LookupByDistributorCodeUnprocessableEntityError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const LookupByDistributorCodeConflictError$inboundSchema: z.ZodMiniType<
  LookupByDistributorCodeConflictError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    count: types.optional(types.number()),
    total_count: types.optional(types.number()),
    matches: types.optional(z.array(z.lazy(() =>
      operations.LookupByDistributorCodeMatch$inboundSchema
    ))),
    request$: z.custom<Request>(x =>
      x instanceof Request
    ),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "total_count": "totalCount",
    });

    return new LookupByDistributorCodeConflictError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const LookupByDistributorCodeNotFoundError$inboundSchema: z.ZodMiniType<
  LookupByDistributorCodeNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new LookupByDistributorCodeNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const LookupByDistributorCodeForbiddenError$inboundSchema: z.ZodMiniType<
  LookupByDistributorCodeForbiddenError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new LookupByDistributorCodeForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
