/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Not Found
 */
export type LookupByISBNNotFoundErrorData = {
  message?: string | undefined;
};

/**
 * Not Found
 */
export class LookupByISBNNotFoundError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: LookupByISBNNotFoundErrorData;

  constructor(
    err: LookupByISBNNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "LookupByISBNNotFoundError";
  }
}

/**
 * Missing Ability
 */
export type LookupByISBNForbiddenErrorData = {
  message?: string | undefined;
};

/**
 * Missing Ability
 */
export class LookupByISBNForbiddenError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: LookupByISBNForbiddenErrorData;

  constructor(
    err: LookupByISBNForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "LookupByISBNForbiddenError";
  }
}

/** @internal */
export const LookupByISBNNotFoundError$inboundSchema: z.ZodMiniType<
  LookupByISBNNotFoundError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new LookupByISBNNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const LookupByISBNForbiddenError$inboundSchema: z.ZodMiniType<
  LookupByISBNForbiddenError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new LookupByISBNForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
