/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { VerseDbError } from "./verse-db-error.js";

/**
 * Invalid merge
 */
export type MergeAListIntoThisOneUnprocessableEntityErrorData = {
  message?: string | undefined;
};

/**
 * Invalid merge
 */
export class MergeAListIntoThisOneUnprocessableEntityError
  extends VerseDbError
{
  /** The original data that was passed to this error instance. */
  data$: MergeAListIntoThisOneUnprocessableEntityErrorData;

  constructor(
    err: MergeAListIntoThisOneUnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "MergeAListIntoThisOneUnprocessableEntityError";
  }
}

/**
 * Unauthorized
 */
export type MergeAListIntoThisOneForbiddenErrorData = {
  message?: string | undefined;
};

/**
 * Unauthorized
 */
export class MergeAListIntoThisOneForbiddenError extends VerseDbError {
  /** The original data that was passed to this error instance. */
  data$: MergeAListIntoThisOneForbiddenErrorData;

  constructor(
    err: MergeAListIntoThisOneForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "MergeAListIntoThisOneForbiddenError";
  }
}

/** @internal */
export const MergeAListIntoThisOneUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<MergeAListIntoThisOneUnprocessableEntityError, unknown> = z
    .pipe(
      z.object({
        message: types.optional(types.string()),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new MergeAListIntoThisOneUnprocessableEntityError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const MergeAListIntoThisOneForbiddenError$inboundSchema: z.ZodMiniType<
  MergeAListIntoThisOneForbiddenError,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new MergeAListIntoThisOneForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
