/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { VerseDBCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { VerseDbError } from "../models/errors/verse-db-error.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Like list, or react to it.
 *
 * @remarks
 * With no body this likes the list. Send `reaction` to leave that reaction instead, or to
 * change the one already held; `DELETE` takes it back whichever it is. A member holds one
 * reaction per list and every reaction counts toward `likes_count`. Cannot like your own lists.
 */
export function listsLikeListOrReactToIt(
  client: VerseDBCore,
  request: operations.LikeListOrReactToItRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.LikeListOrReactToItResponse,
    | errors.UnauthorizedErrorError
    | errors.LikeListOrReactToItForbiddenError
    | errors.LikeListOrReactToItUnprocessableEntityError
    | errors.TooManyRequestsError
    | VerseDbError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: VerseDBCore,
  request: operations.LikeListOrReactToItRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.LikeListOrReactToItResponse,
      | errors.UnauthorizedErrorError
      | errors.LikeListOrReactToItForbiddenError
      | errors.LikeListOrReactToItUnprocessableEntityError
      | errors.TooManyRequestsError
      | VerseDbError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      z.parse(operations.LikeListOrReactToItRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload.body, { explode: true });

  const pathParams = {
    list_id: encodeSimple("list_id", payload.list_id, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path = pathToFunc("/api/v1/lists/{list_id}/like")(pathParams);

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.token);
  const securityInput = secConfig == null ? {} : { token: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "likeListOrReactToIt",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.token,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.LikeListOrReactToItResponse,
    | errors.UnauthorizedErrorError
    | errors.LikeListOrReactToItForbiddenError
    | errors.LikeListOrReactToItUnprocessableEntityError
    | errors.TooManyRequestsError
    | VerseDbError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, operations.LikeListOrReactToItResponse$inboundSchema, {
      hdrs: true,
      key: "Result",
    }),
    M.json(201, operations.LikeListOrReactToItResponse$inboundSchema, {
      hdrs: true,
      key: "Result",
    }),
    M.jsonErr(401, errors.UnauthorizedErrorError$inboundSchema),
    M.jsonErr(403, errors.LikeListOrReactToItForbiddenError$inboundSchema),
    M.jsonErr(
      422,
      errors.LikeListOrReactToItUnprocessableEntityError$inboundSchema,
    ),
    M.jsonErr(429, errors.TooManyRequestsError$inboundSchema, { hdrs: true }),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
