/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { activityGetActivityFeed } from "../funcs/activity-get-activity-feed.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Activity extends ClientSDK {
  /**
   * Get activity feed.
   *
   * @remarks
   * Aggregates recent activity from collections, reads, follows, and reviews.
   */
  async getActivityFeed(
    request?: operations.GetActivityFeedRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetActivityFeedResponse> {
    return unwrapAsync(activityGetActivityFeed(
      this,
      request,
      options,
    ));
  }
}
