/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { barcodeLookupLookupByISBN } from "../funcs/barcode-lookup-lookup-by-isbn.js";
import { barcodeLookupLookupByUPC } from "../funcs/barcode-lookup-lookup-by-upc.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class BarcodeLookup extends ClientSDK {
  /**
   * Lookup by UPC.
   *
   * @remarks
   * Find an issue by its UPC barcode (typically 12-17 digits).
   * Returns full issue details including series information.
   */
  async lookupByUPC(
    request: operations.LookupByUPCRequest,
    options?: RequestOptions,
  ): Promise<operations.LookupByUPCResponse> {
    return unwrapAsync(barcodeLookupLookupByUPC(
      this,
      request,
      options,
    ));
  }

  /**
   * Lookup by ISBN.
   *
   * @remarks
   * Find an issue by its ISBN (10 or 13 digits, with or without dashes).
   * Commonly used for trade paperbacks and hardcovers.
   * Returns full issue details including series information.
   */
  async lookupByISBN(
    request: operations.LookupByISBNRequest,
    options?: RequestOptions,
  ): Promise<operations.LookupByISBNResponse> {
    return unwrapAsync(barcodeLookupLookupByISBN(
      this,
      request,
      options,
    ));
  }
}
