/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { comicShopsGetAComicShop } from "../funcs/comic-shops-get-a-comic-shop.js";
import { comicShopsListComicShops } from "../funcs/comic-shops-list-comic-shops.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ComicShops extends ClientSDK {
  /**
   * List comic shops.
   *
   * @remarks
   * Returns paginated shops with optional location-based and text filtering.
   */
  async listComicShops(
    request?: operations.ListComicShopsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListComicShopsResponse> {
    return unwrapAsync(comicShopsListComicShops(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a comic shop.
   *
   * @remarks
   * Returns full shop details including services offered.
   */
  async getAComicShop(
    request: operations.GetAComicShopRequest,
    options?: RequestOptions,
  ): Promise<operations.GetAComicShopResponse> {
    return unwrapAsync(comicShopsGetAComicShop(
      this,
      request,
      options,
    ));
  }
}
