/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creatorsGetCreatorDetails } from "../funcs/creators-get-creator-details.js";
import { creatorsGetCreatorsBlogPosts } from "../funcs/creators-get-creators-blog-posts.js";
import { creatorsGetCreatorsIssues } from "../funcs/creators-get-creators-issues.js";
import { creatorsGetCreatorsSeries } from "../funcs/creators-get-creators-series.js";
import { creatorsListCreators } from "../funcs/creators-list-creators.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Creators extends ClientSDK {
  /**
   * List creators.
   *
   * @remarks
   * Returns paginated creators with optional search and sorting.
   */
  async listCreators(
    request?: operations.ListCreatorsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListCreatorsResponse> {
    return unwrapAsync(creatorsListCreators(
      this,
      request,
      options,
    ));
  }

  /**
   * Get creator details.
   *
   * @remarks
   * Returns a single creator with full details including biography, role, and awards.
   */
  async getCreatorDetails(
    request: operations.GetCreatorDetailsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCreatorDetailsResponse> {
    return unwrapAsync(creatorsGetCreatorDetails(
      this,
      request,
      options,
    ));
  }

  /**
   * Get creator's blog posts.
   *
   * @remarks
   * Returns paginated published blog posts where this creator is featured.
   */
  async getCreatorsBlogPosts(
    request: operations.GetCreatorsBlogPostsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCreatorsBlogPostsResponse> {
    return unwrapAsync(creatorsGetCreatorsBlogPosts(
      this,
      request,
      options,
    ));
  }

  /**
   * Get creator's issues.
   *
   * @remarks
   * Returns paginated issues where the creator has a credit.
   */
  async getCreatorsIssues(
    request: operations.GetCreatorsIssuesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCreatorsIssuesResponse> {
    return unwrapAsync(creatorsGetCreatorsIssues(
      this,
      request,
      options,
    ));
  }

  /**
   * Get creator's series.
   *
   * @remarks
   * Returns paginated series where the creator has worked.
   */
  async getCreatorsSeries(
    request: operations.GetCreatorsSeriesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCreatorsSeriesResponse> {
    return unwrapAsync(creatorsGetCreatorsSeries(
      this,
      request,
      options,
    ));
  }
}
