/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { followsCheckFollowStatus } from "../funcs/follows-check-follow-status.js";
import { followsFollowContent } from "../funcs/follows-follow-content.js";
import { followsUnfollowContent } from "../funcs/follows-unfollow-content.js";
import { followsUpdateFollowPreferences } from "../funcs/follows-update-follow-preferences.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Follows extends ClientSDK {
  /**
   * Follow content.
   *
   * @remarks
   * Follows a title, character, podcast, creator, publisher, team, story arc, comic shop, event, or user.
   */
  async followContent(
    request: operations.FollowContentRequest,
    options?: RequestOptions,
  ): Promise<operations.FollowContentResponse> {
    return unwrapAsync(followsFollowContent(
      this,
      request,
      options,
    ));
  }

  /**
   * Unfollow content.
   */
  async unfollowContent(
    request: operations.UnfollowContentRequest,
    options?: RequestOptions,
  ): Promise<operations.UnfollowContentResponse> {
    return unwrapAsync(followsUnfollowContent(
      this,
      request,
      options,
    ));
  }

  /**
   * Check follow status.
   */
  async checkFollowStatus(
    request: operations.CheckFollowStatusRequest,
    options?: RequestOptions,
  ): Promise<operations.CheckFollowStatusResponse> {
    return unwrapAsync(followsCheckFollowStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Update follow preferences.
   *
   * @remarks
   * Updates notification preferences for an existing follow.
   */
  async updateFollowPreferences(
    request: operations.UpdateFollowPreferencesRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateFollowPreferencesResponse> {
    return unwrapAsync(followsUpdateFollowPreferences(
      this,
      request,
      options,
    ));
  }
}
