/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { keyIssueReasonsListKeyIssueReasons } from "../funcs/key-issue-reasons-list-key-issue-reasons.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class KeyIssueReasons extends ClientSDK {
  /**
   * List key issue reasons.
   *
   * @remarks
   * Returns all active key issue reasons, optionally filtered by category.
   * Useful for client-side pickers and filters.
   */
  async listKeyIssueReasons(
    request?: operations.ListKeyIssueReasonsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListKeyIssueReasonsResponse> {
    return unwrapAsync(keyIssueReasonsListKeyIssueReasons(
      this,
      request,
      options,
    ));
  }
}
