/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { listsAddItemToList } from "../funcs/lists-add-item-to-list.js";
import { listsBrowseLists } from "../funcs/lists-browse-lists.js";
import { listsBrowseSystemLists } from "../funcs/lists-browse-system-lists.js";
import { listsCreateList } from "../funcs/lists-create-list.js";
import { listsDeleteList } from "../funcs/lists-delete-list.js";
import { listsGetList } from "../funcs/lists-get-list.js";
import { listsGetUsersLists } from "../funcs/lists-get-users-lists.js";
import { listsLikeList } from "../funcs/lists-like-list.js";
import { listsRemoveItemFromList } from "../funcs/lists-remove-item-from-list.js";
import { listsReorderItems } from "../funcs/lists-reorder-items.js";
import { listsSaveList } from "../funcs/lists-save-list.js";
import { listsUnlikeList } from "../funcs/lists-unlike-list.js";
import { listsUnsaveList } from "../funcs/lists-unsave-list.js";
import { listsUpdateList } from "../funcs/lists-update-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Lists extends ClientSDK {
  /**
   * Browse lists.
   *
   * @remarks
   * Returns paginated public lists with filtering and sorting options.
   * Only shows lists with at least one item.
   */
  async browseLists(
    request?: operations.BrowseListsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.BrowseListsResponse> {
    return unwrapAsync(listsBrowseLists(
      this,
      request,
      options,
    ));
  }

  /**
   * Create list.
   *
   * @remarks
   * Creates a new user list.
   */
  async createList(
    request: operations.CreateListRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateListResponse> {
    return unwrapAsync(listsCreateList(
      this,
      request,
      options,
    ));
  }

  /**
   * Browse system lists.
   *
   * @remarks
   * Returns platform-curated lists (no user owner). These are editorial picks and featured content.
   */
  async browseSystemLists(
    request?: operations.BrowseSystemListsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.BrowseSystemListsResponse> {
    return unwrapAsync(listsBrowseSystemLists(
      this,
      request,
      options,
    ));
  }

  /**
   * Get list.
   *
   * @remarks
   * Returns a single list with all its items. Private lists are only visible to owners.
   */
  async getList(
    request: operations.GetListRequest,
    options?: RequestOptions,
  ): Promise<operations.GetListResponse> {
    return unwrapAsync(listsGetList(
      this,
      request,
      options,
    ));
  }

  /**
   * Update list.
   *
   * @remarks
   * Updates a list's metadata. Wishlists can only update privacy settings.
   */
  async updateList(
    request: operations.UpdateListRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateListResponse> {
    return unwrapAsync(listsUpdateList(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete list.
   *
   * @remarks
   * Permanently deletes a list and all its items. Wishlists cannot be deleted.
   */
  async deleteList(
    request: operations.DeleteListRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteListResponse | undefined> {
    return unwrapAsync(listsDeleteList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get user's lists.
   *
   * @remarks
   * Returns a user's public lists. If viewing your own profile, also includes private lists.
   */
  async getUsersLists(
    request: operations.GetUsersListsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetUsersListsResponse> {
    return unwrapAsync(listsGetUsersLists(
      this,
      request,
      options,
    ));
  }

  /**
   * Add item to list.
   *
   * @remarks
   * Adds an entity to a list. Free users: 100 items/list, PRO users: 500 items/list.
   */
  async addItemToList(
    request: operations.AddItemToListRequest,
    options?: RequestOptions,
  ): Promise<operations.AddItemToListResponse> {
    return unwrapAsync(listsAddItemToList(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove item from list.
   *
   * @remarks
   * Removes an item from a list. Other items' positions are automatically adjusted.
   */
  async removeItemFromList(
    request: operations.RemoveItemFromListRequest,
    options?: RequestOptions,
  ): Promise<operations.RemoveItemFromListResponse | undefined> {
    return unwrapAsync(listsRemoveItemFromList(
      this,
      request,
      options,
    ));
  }

  /**
   * Reorder items.
   *
   * @remarks
   * Reorders items in a list by providing the new order of item IDs.
   */
  async reorderItems(
    request: operations.ReorderItemsRequest,
    options?: RequestOptions,
  ): Promise<operations.ReorderItemsResponse> {
    return unwrapAsync(listsReorderItems(
      this,
      request,
      options,
    ));
  }

  /**
   * Save list.
   *
   * @remarks
   * Saves a list to the user's saved lists for quick access. Cannot save your own lists.
   */
  async saveList(
    request: operations.SaveListRequest,
    options?: RequestOptions,
  ): Promise<operations.SaveListResponse> {
    return unwrapAsync(listsSaveList(
      this,
      request,
      options,
    ));
  }

  /**
   * Unsave list.
   *
   * @remarks
   * Removes a list from the user's saved lists.
   */
  async unsaveList(
    request: operations.UnsaveListRequest,
    options?: RequestOptions,
  ): Promise<operations.UnsaveListResponse> {
    return unwrapAsync(listsUnsaveList(
      this,
      request,
      options,
    ));
  }

  /**
   * Like list.
   *
   * @remarks
   * Likes a list. Cannot like your own lists.
   */
  async likeList(
    request: operations.LikeListRequest,
    options?: RequestOptions,
  ): Promise<operations.LikeListResponse> {
    return unwrapAsync(listsLikeList(
      this,
      request,
      options,
    ));
  }

  /**
   * Unlike list.
   *
   * @remarks
   * Removes the user's like from a list.
   */
  async unlikeList(
    request: operations.UnlikeListRequest,
    options?: RequestOptions,
  ): Promise<operations.UnlikeListResponse> {
    return unwrapAsync(listsUnlikeList(
      this,
      request,
      options,
    ));
  }
}
