/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { podcastsGetASpecificPodcast } from "../funcs/podcasts-get-a-specific-podcast.js";
import { podcastsListAllPodcastsWithOptionalSearch } from "../funcs/podcasts-list-all-podcasts-with-optional-search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Podcasts extends ClientSDK {
  /**
   * List all podcasts with optional search
   *
   * @remarks
   * Returns a paginated list of comic book podcasts and YouTube channels, plus
   * the set of languages present in the catalog. Filter with `q`, `type`, or `language`.
   */
  async listAllPodcastsWithOptionalSearch(
    request?: operations.ListAllPodcastsWithOptionalSearchRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListAllPodcastsWithOptionalSearchResponse> {
    return unwrapAsync(podcastsListAllPodcastsWithOptionalSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific podcast.
   *
   * @remarks
   * Returns full detail for one podcast, including its feed, platform links, and categories.
   */
  async getASpecificPodcast(
    request: operations.GetASpecificPodcastRequest,
    options?: RequestOptions,
  ): Promise<operations.GetASpecificPodcastResponse> {
    return unwrapAsync(podcastsGetASpecificPodcast(
      this,
      request,
      options,
    ));
  }
}
