/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publishersGetPublisherDetails } from "../funcs/publishers-get-publisher-details.js";
import { publishersListAllPublishersWithOptionalSearch } from "../funcs/publishers-list-all-publishers-with-optional-search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Publishers extends ClientSDK {
  /**
   * List all publishers with optional search
   *
   * @remarks
   * Returns: id, name, slug, founded_year, headquarters, status, logo_url
   */
  async listAllPublishersWithOptionalSearch(
    request?: operations.ListAllPublishersWithOptionalSearchRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListAllPublishersWithOptionalSearchResponse> {
    return unwrapAsync(publishersListAllPublishersWithOptionalSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get publisher details
   *
   * @remarks
   * Returns: id, name, slug, description, founded_year, first_published_year,
   * website, email, headquarters, parent_company, status, logo_url, aliases,
   * titles_count, series_count, issues_count, characters_count
   *
   * Use the related endpoints for relationship data:
   * - /series?publisher_id={id} - Get series by publisher
   * - /publishers/{id}/characters - Get characters by publisher
   */
  async getPublisherDetails(
    request: operations.GetPublisherDetailsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPublisherDetailsResponse> {
    return unwrapAsync(publishersGetPublisherDetails(
      this,
      request,
      options,
    ));
  }
}
