/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publicProfilesGetUserProfile } from "../funcs/public-profiles-get-user-profile.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PublicProfiles extends ClientSDK {
  /**
   * Get user profile.
   *
   * @remarks
   * Returns a user's public profile data, respecting all privacy settings.
   * If the profile is private and the viewer is not the owner, only basic info is returned.
   */
  async getUserProfile(
    request: operations.GetUserProfileRequest,
    options?: RequestOptions,
  ): Promise<operations.GetUserProfileResponse> {
    return unwrapAsync(publicProfilesGetUserProfile(
      this,
      request,
      options,
    ));
  }
}
