/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storyArcsGetStoryArcDetail } from "../funcs/story-arcs-get-story-arc-detail.js";
import { storyArcsGetStoryArcsForASpecificCharacter } from "../funcs/story-arcs-get-story-arcs-for-a-specific-character.js";
import { storyArcsGetStoryArcsForASpecificIssue } from "../funcs/story-arcs-get-story-arcs-for-a-specific-issue.js";
import { storyArcsGetStoryArcsForASpecificUniverse } from "../funcs/story-arcs-get-story-arcs-for-a-specific-universe.js";
import { storyArcsListAllStoryArcsWithOptionalSearch } from "../funcs/story-arcs-list-all-story-arcs-with-optional-search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class StoryArcs extends ClientSDK {
  /**
   * List all story arcs with optional search
   */
  async listAllStoryArcsWithOptionalSearch(
    request?: operations.ListAllStoryArcsWithOptionalSearchRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListAllStoryArcsWithOptionalSearchResponse> {
    return unwrapAsync(storyArcsListAllStoryArcsWithOptionalSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get story arc detail.
   *
   * @remarks
   * Returns full story arc detail with the primary and secondary universes,
   * a denormalized characters count, the start/end issue summaries (each
   * with its parent series), and the last user who edited the arc.
   *
   * Paginated relationship data lives on dedicated nested endpoints:
   * - GET /story-arcs/{id}/issues - Issues in the arc, in reading order
   * - GET /story-arcs/{id}/series - Series spanned by the arc
   * - GET /story-arcs/{id}/characters - Characters appearing in the arc
   */
  async getStoryArcDetail(
    request: operations.GetStoryArcDetailRequest,
    options?: RequestOptions,
  ): Promise<operations.GetStoryArcDetailResponse> {
    return unwrapAsync(storyArcsGetStoryArcDetail(
      this,
      request,
      options,
    ));
  }

  /**
   * Get story arcs for a specific issue
   *
   * @remarks
   * Requires PRO subscription on the User API (`/api/...`). Returns 402 Payment Required for non-PRO users on that prefix.
   * The Mobile API (`/mobile/api/...`) is unrestricted — its route group does not apply the `pro.api` middleware.
   */
  async getStoryArcsForASpecificIssue(
    request: operations.GetStoryArcsForASpecificIssueRequest,
    options?: RequestOptions,
  ): Promise<operations.GetStoryArcsForASpecificIssueResponse> {
    return unwrapAsync(storyArcsGetStoryArcsForASpecificIssue(
      this,
      request,
      options,
    ));
  }

  /**
   * Get story arcs for a specific character
   *
   * @remarks
   * Requires PRO subscription on the User API (`/api/...`). Returns 402 Payment Required for non-PRO users on that prefix.
   * The Mobile API (`/mobile/api/...`) is unrestricted — its route group does not apply the `pro.api` middleware.
   */
  async getStoryArcsForASpecificCharacter(
    request: operations.GetStoryArcsForASpecificCharacterRequest,
    options?: RequestOptions,
  ): Promise<operations.GetStoryArcsForASpecificCharacterResponse> {
    return unwrapAsync(storyArcsGetStoryArcsForASpecificCharacter(
      this,
      request,
      options,
    ));
  }

  /**
   * Get story arcs for a specific universe
   *
   * @remarks
   * Requires PRO subscription on the User API (`/api/...`). Returns 402 Payment Required for non-PRO users on that prefix.
   * The Mobile API (`/mobile/api/...`) is unrestricted — its route group does not apply the `pro.api` middleware.
   */
  async getStoryArcsForASpecificUniverse(
    request: operations.GetStoryArcsForASpecificUniverseRequest,
    options?: RequestOptions,
  ): Promise<operations.GetStoryArcsForASpecificUniverseResponse> {
    return unwrapAsync(storyArcsGetStoryArcsForASpecificUniverse(
      this,
      request,
      options,
    ));
  }
}
