/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teamsGetASpecificTeam } from "../funcs/teams-get-a-specific-team.js";
import { teamsGetCharactersForASpecificTeammembers } from "../funcs/teams-get-characters-for-a-specific-teammembers.js";
import { teamsGetIssuesForASpecificTeam } from "../funcs/teams-get-issues-for-a-specific-team.js";
import { teamsGetSeriesForASpecificTeam } from "../funcs/teams-get-series-for-a-specific-team.js";
import { teamsListAllTeamsWithOptionalSearch } from "../funcs/teams-list-all-teams-with-optional-search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Teams extends ClientSDK {
  /**
   * List all teams with optional search
   */
  async listAllTeamsWithOptionalSearch(
    request?: operations.ListAllTeamsWithOptionalSearchRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListAllTeamsWithOptionalSearchResponse> {
    return unwrapAsync(teamsListAllTeamsWithOptionalSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific team
   *
   * @remarks
   * Returns team details without relationship data.
   * Use PRO endpoints for relationship data:
   * - /teams/{id}/characters - Get team members
   * - /teams/{id}/series - Get team's series appearances
   * - /teams/{id}/issues - Get team's issue appearances
   */
  async getASpecificTeam(
    request: operations.GetASpecificTeamRequest,
    options?: RequestOptions,
  ): Promise<operations.GetASpecificTeamResponse> {
    return unwrapAsync(teamsGetASpecificTeam(
      this,
      request,
      options,
    ));
  }

  /**
   * Get characters for a specific team (members)
   *
   * @remarks
   * On the User API (routes/api/data.php), this route is gated by the `pro.api` middleware and returns
   * 402 Payment Required for non-PRO users. The mobile API exposes it without
   * that gate.
   */
  async getCharactersForASpecificTeammembers(
    request: operations.GetCharactersForASpecificTeammembersRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCharactersForASpecificTeammembersResponse> {
    return unwrapAsync(teamsGetCharactersForASpecificTeammembers(
      this,
      request,
      options,
    ));
  }

  /**
   * Get series for a specific team
   *
   * @remarks
   * On the User API (routes/api/data.php), this route is gated by the `pro.api` middleware and returns
   * 402 Payment Required for non-PRO users. The mobile API exposes it without
   * that gate.
   */
  async getSeriesForASpecificTeam(
    request: operations.GetSeriesForASpecificTeamRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSeriesForASpecificTeamResponse> {
    return unwrapAsync(teamsGetSeriesForASpecificTeam(
      this,
      request,
      options,
    ));
  }

  /**
   * Get issues for a specific team
   *
   * @remarks
   * On the User API (routes/api/data.php), this route is gated by the `pro.api` middleware and returns
   * 402 Payment Required for non-PRO users. The mobile API exposes it without
   * that gate.
   */
  async getIssuesForASpecificTeam(
    request: operations.GetIssuesForASpecificTeamRequest,
    options?: RequestOptions,
  ): Promise<operations.GetIssuesForASpecificTeamResponse> {
    return unwrapAsync(teamsGetIssuesForASpecificTeam(
      this,
      request,
      options,
    ));
  }
}
