workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    versedb-api:
        inputs:
            - location: https://versedb.com/api/docs.openapi
        registry:
            location: registry.speakeasyapi.dev/versedb/versedb/versedb-api
targets:
    typescript:
        target: typescript
        source: versedb-api
        output: .
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/versedb/versedb/versedb-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
