/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CheckFollowStatusRequest = {
  /**
   * The content type (title, character, podcast, creator, publisher, team, story_arc, comic_shop, event, user).
   */
  type: string;
  /**
   * The ID of the content.
   */
  id: number;
};

/**
 * Success
 */
export type CheckFollowStatusResponseBody = {
  isFollowing?: boolean | undefined;
};

export type CheckFollowStatusResponse = {
  headers: { [k: string]: Array<string> };
  result: CheckFollowStatusResponseBody;
};

/** @internal */
export type CheckFollowStatusRequest$Outbound = {
  type: string;
  id: number;
};

/** @internal */
export const CheckFollowStatusRequest$outboundSchema: z.ZodMiniType<
  CheckFollowStatusRequest$Outbound,
  CheckFollowStatusRequest
> = z.object({
  type: z.string(),
  id: z.int(),
});

export function checkFollowStatusRequestToJSON(
  checkFollowStatusRequest: CheckFollowStatusRequest,
): string {
  return JSON.stringify(
    CheckFollowStatusRequest$outboundSchema.parse(checkFollowStatusRequest),
  );
}

/** @internal */
export const CheckFollowStatusResponseBody$inboundSchema: z.ZodMiniType<
  CheckFollowStatusResponseBody,
  unknown
> = z.pipe(
  z.object({
    is_following: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_following": "isFollowing",
    });
  }),
);

export function checkFollowStatusResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CheckFollowStatusResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckFollowStatusResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckFollowStatusResponseBody' from JSON`,
  );
}

/** @internal */
export const CheckFollowStatusResponse$inboundSchema: z.ZodMiniType<
  CheckFollowStatusResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => CheckFollowStatusResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function checkFollowStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<CheckFollowStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckFollowStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckFollowStatusResponse' from JSON`,
  );
}
