/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ConvertAListToMixedRequest = {
  /**
   * The list ID.
   */
  listId: number;
};

export type ConvertAListToMixedData = {
  id?: number | undefined;
  entityType?: string | undefined;
};

/**
 * Converted
 */
export type ConvertAListToMixedResponseBody = {
  data?: ConvertAListToMixedData | undefined;
};

export type ConvertAListToMixedResponse = {
  headers: { [k: string]: Array<string> };
  result: ConvertAListToMixedResponseBody;
};

/** @internal */
export type ConvertAListToMixedRequest$Outbound = {
  list_id: number;
};

/** @internal */
export const ConvertAListToMixedRequest$outboundSchema: z.ZodMiniType<
  ConvertAListToMixedRequest$Outbound,
  ConvertAListToMixedRequest
> = z.pipe(
  z.object({
    listId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      listId: "list_id",
    });
  }),
);

export function convertAListToMixedRequestToJSON(
  convertAListToMixedRequest: ConvertAListToMixedRequest,
): string {
  return JSON.stringify(
    ConvertAListToMixedRequest$outboundSchema.parse(convertAListToMixedRequest),
  );
}

/** @internal */
export const ConvertAListToMixedData$inboundSchema: z.ZodMiniType<
  ConvertAListToMixedData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    entity_type: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "entity_type": "entityType",
    });
  }),
);

export function convertAListToMixedDataFromJSON(
  jsonString: string,
): SafeParseResult<ConvertAListToMixedData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConvertAListToMixedData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConvertAListToMixedData' from JSON`,
  );
}

/** @internal */
export const ConvertAListToMixedResponseBody$inboundSchema: z.ZodMiniType<
  ConvertAListToMixedResponseBody,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => ConvertAListToMixedData$inboundSchema)),
});

export function convertAListToMixedResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ConvertAListToMixedResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConvertAListToMixedResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConvertAListToMixedResponseBody' from JSON`,
  );
}

/** @internal */
export const ConvertAListToMixedResponse$inboundSchema: z.ZodMiniType<
  ConvertAListToMixedResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => ConvertAListToMixedResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function convertAListToMixedResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConvertAListToMixedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConvertAListToMixedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConvertAListToMixedResponse' from JSON`,
  );
}
