/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type EditReadingDateRequestBody = {
  /**
   * Date in YYYY-MM-DD format, must not be in the future. Pass null to mark as unread.
   */
  readAt?: string | null | undefined;
  /**
   * Specific variant ID (optional).
   */
  variantId?: number | null | undefined;
};

export type EditReadingDateRequest = {
  /**
   * The issue ID.
   */
  issueId: number;
  body?: EditReadingDateRequestBody | undefined;
};

/**
 * Updated
 */
export type EditReadingDateResponseBody = {
  readAt?: string | undefined;
};

export type EditReadingDateResponse = {
  headers: { [k: string]: Array<string> };
  result?: EditReadingDateResponseBody | undefined;
};

/** @internal */
export type EditReadingDateRequestBody$Outbound = {
  read_at?: string | null | undefined;
  variant_id?: number | null | undefined;
};

/** @internal */
export const EditReadingDateRequestBody$outboundSchema: z.ZodMiniType<
  EditReadingDateRequestBody$Outbound,
  EditReadingDateRequestBody
> = z.pipe(
  z.object({
    readAt: z.optional(z.nullable(z.string())),
    variantId: z.optional(z.nullable(z.int())),
  }),
  z.transform((v) => {
    return remap$(v, {
      readAt: "read_at",
      variantId: "variant_id",
    });
  }),
);

export function editReadingDateRequestBodyToJSON(
  editReadingDateRequestBody: EditReadingDateRequestBody,
): string {
  return JSON.stringify(
    EditReadingDateRequestBody$outboundSchema.parse(editReadingDateRequestBody),
  );
}

/** @internal */
export type EditReadingDateRequest$Outbound = {
  issue_id: number;
  body?: EditReadingDateRequestBody$Outbound | undefined;
};

/** @internal */
export const EditReadingDateRequest$outboundSchema: z.ZodMiniType<
  EditReadingDateRequest$Outbound,
  EditReadingDateRequest
> = z.pipe(
  z.object({
    issueId: z.int(),
    body: z.optional(z.lazy(() => EditReadingDateRequestBody$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      issueId: "issue_id",
    });
  }),
);

export function editReadingDateRequestToJSON(
  editReadingDateRequest: EditReadingDateRequest,
): string {
  return JSON.stringify(
    EditReadingDateRequest$outboundSchema.parse(editReadingDateRequest),
  );
}

/** @internal */
export const EditReadingDateResponseBody$inboundSchema: z.ZodMiniType<
  EditReadingDateResponseBody,
  unknown
> = z.pipe(
  z.object({
    read_at: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "read_at": "readAt",
    });
  }),
);

export function editReadingDateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<EditReadingDateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditReadingDateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditReadingDateResponseBody' from JSON`,
  );
}

/** @internal */
export const EditReadingDateResponse$inboundSchema: z.ZodMiniType<
  EditReadingDateResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: types.optional(
      z.lazy(() => EditReadingDateResponseBody$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function editReadingDateResponseFromJSON(
  jsonString: string,
): SafeParseResult<EditReadingDateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditReadingDateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditReadingDateResponse' from JSON`,
  );
}
