/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type FOCDeadlinesRequest = {
  /**
   * Max results (1-50).
   */
  limit?: number | undefined;
  /**
   * FOC window in days (1-30).
   */
  days?: number | undefined;
  /**
   * Start of FOC window (YYYY-MM-DD). Defaults to today.
   */
  startDate?: string | undefined;
};

export type FOCDeadlinesSeries = {
  id?: number | undefined;
  name?: string | undefined;
};

export type FOCDeadlinesData = {
  id?: number | undefined;
  number?: string | undefined;
  title?: string | undefined;
  coverUrl?: string | undefined;
  releaseDate?: string | undefined;
  focDate?: string | undefined;
  series?: FOCDeadlinesSeries | undefined;
};

export type FOCDeadlinesMeta = {
  focWindowDays?: number | undefined;
  focStart?: string | undefined;
  focEnd?: string | undefined;
  note?: string | undefined;
};

/**
 * Success
 */
export type FOCDeadlinesResponseBody = {
  data?: Array<FOCDeadlinesData> | undefined;
  meta?: FOCDeadlinesMeta | undefined;
};

export type FOCDeadlinesResponse = {
  headers: { [k: string]: Array<string> };
  result: FOCDeadlinesResponseBody;
};

/** @internal */
export type FOCDeadlinesRequest$Outbound = {
  limit?: number | undefined;
  days?: number | undefined;
  start_date?: string | undefined;
};

/** @internal */
export const FOCDeadlinesRequest$outboundSchema: z.ZodMiniType<
  FOCDeadlinesRequest$Outbound,
  FOCDeadlinesRequest
> = z.pipe(
  z.object({
    limit: z.optional(z.int()),
    days: z.optional(z.int()),
    startDate: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      startDate: "start_date",
    });
  }),
);

export function fOCDeadlinesRequestToJSON(
  focDeadlinesRequest: FOCDeadlinesRequest,
): string {
  return JSON.stringify(
    FOCDeadlinesRequest$outboundSchema.parse(focDeadlinesRequest),
  );
}

/** @internal */
export const FOCDeadlinesSeries$inboundSchema: z.ZodMiniType<
  FOCDeadlinesSeries,
  unknown
> = z.object({
  id: types.optional(types.number()),
  name: types.optional(types.string()),
});

export function fOCDeadlinesSeriesFromJSON(
  jsonString: string,
): SafeParseResult<FOCDeadlinesSeries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FOCDeadlinesSeries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FOCDeadlinesSeries' from JSON`,
  );
}

/** @internal */
export const FOCDeadlinesData$inboundSchema: z.ZodMiniType<
  FOCDeadlinesData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    number: types.optional(types.string()),
    title: types.optional(types.string()),
    cover_url: types.optional(types.string()),
    release_date: types.optional(types.string()),
    foc_date: types.optional(types.string()),
    series: types.optional(z.lazy(() => FOCDeadlinesSeries$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "cover_url": "coverUrl",
      "release_date": "releaseDate",
      "foc_date": "focDate",
    });
  }),
);

export function fOCDeadlinesDataFromJSON(
  jsonString: string,
): SafeParseResult<FOCDeadlinesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FOCDeadlinesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FOCDeadlinesData' from JSON`,
  );
}

/** @internal */
export const FOCDeadlinesMeta$inboundSchema: z.ZodMiniType<
  FOCDeadlinesMeta,
  unknown
> = z.pipe(
  z.object({
    foc_window_days: types.optional(types.number()),
    foc_start: types.optional(types.string()),
    foc_end: types.optional(types.string()),
    note: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "foc_window_days": "focWindowDays",
      "foc_start": "focStart",
      "foc_end": "focEnd",
    });
  }),
);

export function fOCDeadlinesMetaFromJSON(
  jsonString: string,
): SafeParseResult<FOCDeadlinesMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FOCDeadlinesMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FOCDeadlinesMeta' from JSON`,
  );
}

/** @internal */
export const FOCDeadlinesResponseBody$inboundSchema: z.ZodMiniType<
  FOCDeadlinesResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(z.lazy(() => FOCDeadlinesData$inboundSchema))),
  meta: types.optional(z.lazy(() => FOCDeadlinesMeta$inboundSchema)),
});

export function fOCDeadlinesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<FOCDeadlinesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FOCDeadlinesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FOCDeadlinesResponseBody' from JSON`,
  );
}

/** @internal */
export const FOCDeadlinesResponse$inboundSchema: z.ZodMiniType<
  FOCDeadlinesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => FOCDeadlinesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function fOCDeadlinesResponseFromJSON(
  jsonString: string,
): SafeParseResult<FOCDeadlinesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FOCDeadlinesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FOCDeadlinesResponse' from JSON`,
  );
}
