/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type FollowUpdatesRequest = {
  /**
   * Max results (1-50).
   */
  limit?: number | undefined;
  /**
   * Lookback window in days (1-90).
   */
  days?: number | undefined;
  /**
   * Page number for pagination.
   */
  page?: number | undefined;
  /**
   * Items per page (1-50).
   */
  perPage?: number | undefined;
};

export type FollowUpdatesSeries = {
  id?: number | undefined;
  name?: string | undefined;
  startYear?: number | undefined;
};

export type FollowUpdatesData = {
  id?: number | undefined;
  issueNumber?: string | undefined;
  coverUrl?: string | undefined;
  releaseDate?: string | undefined;
  series?: FollowUpdatesSeries | undefined;
  followContext?: string | undefined;
  followType?: string | undefined;
};

export type FollowUpdatesMeta = {
  days?: number | undefined;
  totalFollows?: number | undefined;
};

/**
 * Success
 */
export type FollowUpdatesResponseBody = {
  data?: Array<FollowUpdatesData> | undefined;
  meta?: FollowUpdatesMeta | undefined;
};

export type FollowUpdatesResponse = {
  headers: { [k: string]: Array<string> };
  result: FollowUpdatesResponseBody;
};

/** @internal */
export type FollowUpdatesRequest$Outbound = {
  limit?: number | undefined;
  days?: number | undefined;
  page?: number | undefined;
  per_page?: number | undefined;
};

/** @internal */
export const FollowUpdatesRequest$outboundSchema: z.ZodMiniType<
  FollowUpdatesRequest$Outbound,
  FollowUpdatesRequest
> = z.pipe(
  z.object({
    limit: z.optional(z.int()),
    days: z.optional(z.int()),
    page: z.optional(z.int()),
    perPage: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      perPage: "per_page",
    });
  }),
);

export function followUpdatesRequestToJSON(
  followUpdatesRequest: FollowUpdatesRequest,
): string {
  return JSON.stringify(
    FollowUpdatesRequest$outboundSchema.parse(followUpdatesRequest),
  );
}

/** @internal */
export const FollowUpdatesSeries$inboundSchema: z.ZodMiniType<
  FollowUpdatesSeries,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    start_year: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "start_year": "startYear",
    });
  }),
);

export function followUpdatesSeriesFromJSON(
  jsonString: string,
): SafeParseResult<FollowUpdatesSeries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FollowUpdatesSeries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowUpdatesSeries' from JSON`,
  );
}

/** @internal */
export const FollowUpdatesData$inboundSchema: z.ZodMiniType<
  FollowUpdatesData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    issue_number: types.optional(types.string()),
    cover_url: types.optional(types.string()),
    release_date: types.optional(types.string()),
    series: types.optional(z.lazy(() => FollowUpdatesSeries$inboundSchema)),
    follow_context: types.optional(types.string()),
    follow_type: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "issue_number": "issueNumber",
      "cover_url": "coverUrl",
      "release_date": "releaseDate",
      "follow_context": "followContext",
      "follow_type": "followType",
    });
  }),
);

export function followUpdatesDataFromJSON(
  jsonString: string,
): SafeParseResult<FollowUpdatesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FollowUpdatesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowUpdatesData' from JSON`,
  );
}

/** @internal */
export const FollowUpdatesMeta$inboundSchema: z.ZodMiniType<
  FollowUpdatesMeta,
  unknown
> = z.pipe(
  z.object({
    days: types.optional(types.number()),
    total_follows: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_follows": "totalFollows",
    });
  }),
);

export function followUpdatesMetaFromJSON(
  jsonString: string,
): SafeParseResult<FollowUpdatesMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FollowUpdatesMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowUpdatesMeta' from JSON`,
  );
}

/** @internal */
export const FollowUpdatesResponseBody$inboundSchema: z.ZodMiniType<
  FollowUpdatesResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(z.lazy(() => FollowUpdatesData$inboundSchema))),
  meta: types.optional(z.lazy(() => FollowUpdatesMeta$inboundSchema)),
});

export function followUpdatesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<FollowUpdatesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FollowUpdatesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowUpdatesResponseBody' from JSON`,
  );
}

/** @internal */
export const FollowUpdatesResponse$inboundSchema: z.ZodMiniType<
  FollowUpdatesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => FollowUpdatesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function followUpdatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<FollowUpdatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FollowUpdatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowUpdatesResponse' from JSON`,
  );
}
