/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetASpecificPodcastRequest = {
  /**
   * The ID of the podcast.
   */
  podcastId: number;
};

export type PlatformLinks = {
  youtube?: string | undefined;
};

export type GetASpecificPodcastData = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  type?: string | undefined;
  description?: string | undefined;
  language?: string | undefined;
  logoUrl?: string | null | undefined;
  images?: string | null | undefined;
  websiteUrl?: string | null | undefined;
  rssFeedUrl?: string | null | undefined;
  youtubeChannelId?: string | undefined;
  socialLinks?: string | null | undefined;
  platformLinks?: PlatformLinks | undefined;
  followerCount?: number | undefined;
  subscriberCount?: string | null | undefined;
  categories?: Array<any> | undefined;
};

export type GetASpecificPodcastResponseBody = {
  data?: GetASpecificPodcastData | undefined;
};

export type GetASpecificPodcastResponse = {
  headers: { [k: string]: Array<string> };
  result: GetASpecificPodcastResponseBody;
};

/** @internal */
export type GetASpecificPodcastRequest$Outbound = {
  podcast_id: number;
};

/** @internal */
export const GetASpecificPodcastRequest$outboundSchema: z.ZodMiniType<
  GetASpecificPodcastRequest$Outbound,
  GetASpecificPodcastRequest
> = z.pipe(
  z.object({
    podcastId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      podcastId: "podcast_id",
    });
  }),
);

export function getASpecificPodcastRequestToJSON(
  getASpecificPodcastRequest: GetASpecificPodcastRequest,
): string {
  return JSON.stringify(
    GetASpecificPodcastRequest$outboundSchema.parse(getASpecificPodcastRequest),
  );
}

/** @internal */
export const PlatformLinks$inboundSchema: z.ZodMiniType<
  PlatformLinks,
  unknown
> = z.object({
  youtube: types.optional(types.string()),
});

export function platformLinksFromJSON(
  jsonString: string,
): SafeParseResult<PlatformLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformLinks' from JSON`,
  );
}

/** @internal */
export const GetASpecificPodcastData$inboundSchema: z.ZodMiniType<
  GetASpecificPodcastData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    slug: types.optional(types.string()),
    type: types.optional(types.string()),
    description: types.optional(types.string()),
    language: types.optional(types.string()),
    logo_url: z.optional(z.nullable(types.string())),
    images: z.optional(z.nullable(types.string())),
    website_url: z.optional(z.nullable(types.string())),
    rss_feed_url: z.optional(z.nullable(types.string())),
    youtube_channel_id: types.optional(types.string()),
    social_links: z.optional(z.nullable(types.string())),
    platform_links: types.optional(z.lazy(() => PlatformLinks$inboundSchema)),
    follower_count: types.optional(types.number()),
    subscriber_count: z.optional(z.nullable(types.string())),
    categories: types.optional(z.array(z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "logo_url": "logoUrl",
      "website_url": "websiteUrl",
      "rss_feed_url": "rssFeedUrl",
      "youtube_channel_id": "youtubeChannelId",
      "social_links": "socialLinks",
      "platform_links": "platformLinks",
      "follower_count": "followerCount",
      "subscriber_count": "subscriberCount",
    });
  }),
);

export function getASpecificPodcastDataFromJSON(
  jsonString: string,
): SafeParseResult<GetASpecificPodcastData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetASpecificPodcastData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetASpecificPodcastData' from JSON`,
  );
}

/** @internal */
export const GetASpecificPodcastResponseBody$inboundSchema: z.ZodMiniType<
  GetASpecificPodcastResponseBody,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => GetASpecificPodcastData$inboundSchema)),
});

export function getASpecificPodcastResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetASpecificPodcastResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetASpecificPodcastResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetASpecificPodcastResponseBody' from JSON`,
  );
}

/** @internal */
export const GetASpecificPodcastResponse$inboundSchema: z.ZodMiniType<
  GetASpecificPodcastResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetASpecificPodcastResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getASpecificPodcastResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetASpecificPodcastResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetASpecificPodcastResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetASpecificPodcastResponse' from JSON`,
  );
}
