/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetAchievementsForTheAuthenticatedUserRequest = {
  /**
   * Include in-progress achievements. Default: false.
   */
  includeProgress?: boolean | undefined;
  /**
   * Include all achievements grouped by category. Default: false.
   */
  includeAll?: boolean | undefined;
};

export type GetAchievementsForTheAuthenticatedUserData = {
  earned?: Array<any> | undefined;
  totalEarned?: number | undefined;
};

export type GetAchievementsForTheAuthenticatedUserResponseBody = {
  data?: GetAchievementsForTheAuthenticatedUserData | undefined;
};

export type GetAchievementsForTheAuthenticatedUserResponse = {
  headers: { [k: string]: Array<string> };
  result: GetAchievementsForTheAuthenticatedUserResponseBody;
};

/** @internal */
export type GetAchievementsForTheAuthenticatedUserRequest$Outbound = {
  include_progress?: boolean | undefined;
  include_all?: boolean | undefined;
};

/** @internal */
export const GetAchievementsForTheAuthenticatedUserRequest$outboundSchema:
  z.ZodMiniType<
    GetAchievementsForTheAuthenticatedUserRequest$Outbound,
    GetAchievementsForTheAuthenticatedUserRequest
  > = z.pipe(
    z.object({
      includeProgress: z.optional(z.boolean()),
      includeAll: z.optional(z.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        includeProgress: "include_progress",
        includeAll: "include_all",
      });
    }),
  );

export function getAchievementsForTheAuthenticatedUserRequestToJSON(
  getAchievementsForTheAuthenticatedUserRequest:
    GetAchievementsForTheAuthenticatedUserRequest,
): string {
  return JSON.stringify(
    GetAchievementsForTheAuthenticatedUserRequest$outboundSchema.parse(
      getAchievementsForTheAuthenticatedUserRequest,
    ),
  );
}

/** @internal */
export const GetAchievementsForTheAuthenticatedUserData$inboundSchema:
  z.ZodMiniType<GetAchievementsForTheAuthenticatedUserData, unknown> = z.pipe(
    z.object({
      earned: types.optional(z.array(z.any())),
      total_earned: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "total_earned": "totalEarned",
      });
    }),
  );

export function getAchievementsForTheAuthenticatedUserDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAchievementsForTheAuthenticatedUserData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAchievementsForTheAuthenticatedUserData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAchievementsForTheAuthenticatedUserData' from JSON`,
  );
}

/** @internal */
export const GetAchievementsForTheAuthenticatedUserResponseBody$inboundSchema:
  z.ZodMiniType<GetAchievementsForTheAuthenticatedUserResponseBody, unknown> = z
    .object({
      data: types.optional(
        z.lazy(() => GetAchievementsForTheAuthenticatedUserData$inboundSchema),
      ),
    });

export function getAchievementsForTheAuthenticatedUserResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAchievementsForTheAuthenticatedUserResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAchievementsForTheAuthenticatedUserResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAchievementsForTheAuthenticatedUserResponseBody' from JSON`,
  );
}

/** @internal */
export const GetAchievementsForTheAuthenticatedUserResponse$inboundSchema:
  z.ZodMiniType<GetAchievementsForTheAuthenticatedUserResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result: z.lazy(() =>
          GetAchievementsForTheAuthenticatedUserResponseBody$inboundSchema
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function getAchievementsForTheAuthenticatedUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAchievementsForTheAuthenticatedUserResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAchievementsForTheAuthenticatedUserResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAchievementsForTheAuthenticatedUserResponse' from JSON`,
  );
}
