/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetCharacterSeriesRequest = {
  /**
   * The character ID.
   */
  characterId: number;
  /**
   * Results per page (max 50).
   */
  limit?: number | undefined;
};

export type GetCharacterSeriesData = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  startYear?: number | undefined;
  endYear?: number | undefined;
  imageUrl?: string | undefined;
};

export type GetCharacterSeriesMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type GetCharacterSeriesResponseBody = {
  data?: Array<GetCharacterSeriesData> | undefined;
  meta?: GetCharacterSeriesMeta | undefined;
};

export type GetCharacterSeriesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetCharacterSeriesResponseBody;
};

/** @internal */
export type GetCharacterSeriesRequest$Outbound = {
  character_id: number;
  limit?: number | undefined;
};

/** @internal */
export const GetCharacterSeriesRequest$outboundSchema: z.ZodMiniType<
  GetCharacterSeriesRequest$Outbound,
  GetCharacterSeriesRequest
> = z.pipe(
  z.object({
    characterId: z.int(),
    limit: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      characterId: "character_id",
    });
  }),
);

export function getCharacterSeriesRequestToJSON(
  getCharacterSeriesRequest: GetCharacterSeriesRequest,
): string {
  return JSON.stringify(
    GetCharacterSeriesRequest$outboundSchema.parse(getCharacterSeriesRequest),
  );
}

/** @internal */
export const GetCharacterSeriesData$inboundSchema: z.ZodMiniType<
  GetCharacterSeriesData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    slug: types.optional(types.string()),
    start_year: types.optional(types.number()),
    end_year: types.optional(types.number()),
    image_url: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "start_year": "startYear",
      "end_year": "endYear",
      "image_url": "imageUrl",
    });
  }),
);

export function getCharacterSeriesDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCharacterSeriesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCharacterSeriesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCharacterSeriesData' from JSON`,
  );
}

/** @internal */
export const GetCharacterSeriesMeta$inboundSchema: z.ZodMiniType<
  GetCharacterSeriesMeta,
  unknown
> = z.pipe(
  z.object({
    current_page: types.optional(types.number()),
    last_page: types.optional(types.number()),
    per_page: types.optional(types.number()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_page": "currentPage",
      "last_page": "lastPage",
      "per_page": "perPage",
    });
  }),
);

export function getCharacterSeriesMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetCharacterSeriesMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCharacterSeriesMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCharacterSeriesMeta' from JSON`,
  );
}

/** @internal */
export const GetCharacterSeriesResponseBody$inboundSchema: z.ZodMiniType<
  GetCharacterSeriesResponseBody,
  unknown
> = z.object({
  data: types.optional(
    z.array(z.lazy(() => GetCharacterSeriesData$inboundSchema)),
  ),
  meta: types.optional(z.lazy(() => GetCharacterSeriesMeta$inboundSchema)),
});

export function getCharacterSeriesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetCharacterSeriesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCharacterSeriesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCharacterSeriesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetCharacterSeriesResponse$inboundSchema: z.ZodMiniType<
  GetCharacterSeriesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetCharacterSeriesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getCharacterSeriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCharacterSeriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCharacterSeriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCharacterSeriesResponse' from JSON`,
  );
}
