/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetSeriesCreatorsRequest = {
  /**
   * The series ID.
   */
  id: number;
};

export type GetSeriesCreatorsRole = {
  id?: number | undefined;
  name?: string | undefined;
};

export type GetSeriesCreatorsData = {
  id?: number | undefined;
  name?: string | undefined;
  role?: GetSeriesCreatorsRole | undefined;
};

export type GetSeriesCreatorsMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type GetSeriesCreatorsResponseBody = {
  data?: Array<GetSeriesCreatorsData> | undefined;
  meta?: GetSeriesCreatorsMeta | undefined;
};

export type GetSeriesCreatorsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetSeriesCreatorsResponseBody;
};

/** @internal */
export type GetSeriesCreatorsRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetSeriesCreatorsRequest$outboundSchema: z.ZodMiniType<
  GetSeriesCreatorsRequest$Outbound,
  GetSeriesCreatorsRequest
> = z.object({
  id: z.int(),
});

export function getSeriesCreatorsRequestToJSON(
  getSeriesCreatorsRequest: GetSeriesCreatorsRequest,
): string {
  return JSON.stringify(
    GetSeriesCreatorsRequest$outboundSchema.parse(getSeriesCreatorsRequest),
  );
}

/** @internal */
export const GetSeriesCreatorsRole$inboundSchema: z.ZodMiniType<
  GetSeriesCreatorsRole,
  unknown
> = z.object({
  id: types.optional(types.number()),
  name: types.optional(types.string()),
});

export function getSeriesCreatorsRoleFromJSON(
  jsonString: string,
): SafeParseResult<GetSeriesCreatorsRole, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSeriesCreatorsRole$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSeriesCreatorsRole' from JSON`,
  );
}

/** @internal */
export const GetSeriesCreatorsData$inboundSchema: z.ZodMiniType<
  GetSeriesCreatorsData,
  unknown
> = z.object({
  id: types.optional(types.number()),
  name: types.optional(types.string()),
  role: types.optional(z.lazy(() => GetSeriesCreatorsRole$inboundSchema)),
});

export function getSeriesCreatorsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetSeriesCreatorsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSeriesCreatorsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSeriesCreatorsData' from JSON`,
  );
}

/** @internal */
export const GetSeriesCreatorsMeta$inboundSchema: z.ZodMiniType<
  GetSeriesCreatorsMeta,
  unknown
> = z.pipe(
  z.object({
    current_page: types.optional(types.number()),
    last_page: types.optional(types.number()),
    per_page: types.optional(types.number()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_page": "currentPage",
      "last_page": "lastPage",
      "per_page": "perPage",
    });
  }),
);

export function getSeriesCreatorsMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetSeriesCreatorsMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSeriesCreatorsMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSeriesCreatorsMeta' from JSON`,
  );
}

/** @internal */
export const GetSeriesCreatorsResponseBody$inboundSchema: z.ZodMiniType<
  GetSeriesCreatorsResponseBody,
  unknown
> = z.object({
  data: types.optional(
    z.array(z.lazy(() => GetSeriesCreatorsData$inboundSchema)),
  ),
  meta: types.optional(z.lazy(() => GetSeriesCreatorsMeta$inboundSchema)),
});

export function getSeriesCreatorsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetSeriesCreatorsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSeriesCreatorsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSeriesCreatorsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetSeriesCreatorsResponse$inboundSchema: z.ZodMiniType<
  GetSeriesCreatorsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetSeriesCreatorsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getSeriesCreatorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSeriesCreatorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSeriesCreatorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSeriesCreatorsResponse' from JSON`,
  );
}
