/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetPublisherDetailsRequest = {
  /**
   * The ID of the publisher.
   */
  publisherId: number;
};

export type GetPublisherDetailsImages = {
  tileSm?: string | undefined;
  profileMd?: string | undefined;
  fullLg?: string | undefined;
};

export type GetPublisherDetailsData = {
  id?: number | undefined;
  name?: string | undefined;
  description?: string | undefined;
  foundedYear?: number | undefined;
  website?: string | undefined;
  headquarters?: string | undefined;
  parentCompany?: string | undefined;
  status?: string | undefined;
  logoUrl?: string | undefined;
  images?: GetPublisherDetailsImages | undefined;
  firstPublishedYear?: number | undefined;
  aliases?: Array<string> | undefined;
};

/**
 * Success
 */
export type GetPublisherDetailsResponseBody = {
  data?: GetPublisherDetailsData | undefined;
};

export type GetPublisherDetailsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetPublisherDetailsResponseBody;
};

/** @internal */
export type GetPublisherDetailsRequest$Outbound = {
  publisher_id: number;
};

/** @internal */
export const GetPublisherDetailsRequest$outboundSchema: z.ZodMiniType<
  GetPublisherDetailsRequest$Outbound,
  GetPublisherDetailsRequest
> = z.pipe(
  z.object({
    publisherId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      publisherId: "publisher_id",
    });
  }),
);

export function getPublisherDetailsRequestToJSON(
  getPublisherDetailsRequest: GetPublisherDetailsRequest,
): string {
  return JSON.stringify(
    GetPublisherDetailsRequest$outboundSchema.parse(getPublisherDetailsRequest),
  );
}

/** @internal */
export const GetPublisherDetailsImages$inboundSchema: z.ZodMiniType<
  GetPublisherDetailsImages,
  unknown
> = z.pipe(
  z.object({
    tile_sm: types.optional(types.string()),
    profile_md: types.optional(types.string()),
    full_lg: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tile_sm": "tileSm",
      "profile_md": "profileMd",
      "full_lg": "fullLg",
    });
  }),
);

export function getPublisherDetailsImagesFromJSON(
  jsonString: string,
): SafeParseResult<GetPublisherDetailsImages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPublisherDetailsImages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPublisherDetailsImages' from JSON`,
  );
}

/** @internal */
export const GetPublisherDetailsData$inboundSchema: z.ZodMiniType<
  GetPublisherDetailsData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    description: types.optional(types.string()),
    founded_year: types.optional(types.number()),
    website: types.optional(types.string()),
    headquarters: types.optional(types.string()),
    parent_company: types.optional(types.string()),
    status: types.optional(types.string()),
    logo_url: types.optional(types.string()),
    images: types.optional(
      z.lazy(() => GetPublisherDetailsImages$inboundSchema),
    ),
    first_published_year: types.optional(types.number()),
    aliases: types.optional(z.array(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "founded_year": "foundedYear",
      "parent_company": "parentCompany",
      "logo_url": "logoUrl",
      "first_published_year": "firstPublishedYear",
    });
  }),
);

export function getPublisherDetailsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetPublisherDetailsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPublisherDetailsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPublisherDetailsData' from JSON`,
  );
}

/** @internal */
export const GetPublisherDetailsResponseBody$inboundSchema: z.ZodMiniType<
  GetPublisherDetailsResponseBody,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => GetPublisherDetailsData$inboundSchema)),
});

export function getPublisherDetailsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetPublisherDetailsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPublisherDetailsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPublisherDetailsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetPublisherDetailsResponse$inboundSchema: z.ZodMiniType<
  GetPublisherDetailsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetPublisherDetailsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getPublisherDetailsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPublisherDetailsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPublisherDetailsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPublisherDetailsResponse' from JSON`,
  );
}
