/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetActivityFeedRequest = {
  /**
   * Number of results per page (max 100).
   */
  perPage?: number | undefined;
};

export type GetActivityFeedMeta = {
  currentPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
  lastPage?: number | undefined;
};

export type GetActivityFeedResponseBody = {
  data?: Array<any> | undefined;
  meta?: GetActivityFeedMeta | undefined;
};

export type GetActivityFeedResponse = {
  headers: { [k: string]: Array<string> };
  result: GetActivityFeedResponseBody;
};

/** @internal */
export type GetActivityFeedRequest$Outbound = {
  per_page?: number | undefined;
};

/** @internal */
export const GetActivityFeedRequest$outboundSchema: z.ZodMiniType<
  GetActivityFeedRequest$Outbound,
  GetActivityFeedRequest
> = z.pipe(
  z.object({
    perPage: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      perPage: "per_page",
    });
  }),
);

export function getActivityFeedRequestToJSON(
  getActivityFeedRequest: GetActivityFeedRequest,
): string {
  return JSON.stringify(
    GetActivityFeedRequest$outboundSchema.parse(getActivityFeedRequest),
  );
}

/** @internal */
export const GetActivityFeedMeta$inboundSchema: z.ZodMiniType<
  GetActivityFeedMeta,
  unknown
> = z.pipe(
  z.object({
    current_page: types.optional(types.number()),
    per_page: types.optional(types.number()),
    total: types.optional(types.number()),
    last_page: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_page": "currentPage",
      "per_page": "perPage",
      "last_page": "lastPage",
    });
  }),
);

export function getActivityFeedMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetActivityFeedMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActivityFeedMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActivityFeedMeta' from JSON`,
  );
}

/** @internal */
export const GetActivityFeedResponseBody$inboundSchema: z.ZodMiniType<
  GetActivityFeedResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(z.any())),
  meta: types.optional(z.lazy(() => GetActivityFeedMeta$inboundSchema)),
});

export function getActivityFeedResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetActivityFeedResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActivityFeedResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActivityFeedResponseBody' from JSON`,
  );
}

/** @internal */
export const GetActivityFeedResponse$inboundSchema: z.ZodMiniType<
  GetActivityFeedResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetActivityFeedResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getActivityFeedResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetActivityFeedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActivityFeedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActivityFeedResponse' from JSON`,
  );
}
