/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetListRequest = {
  /**
   * The list ID.
   */
  listId: number;
};

export type GetListUser = {
  id?: number | undefined;
  username?: string | undefined;
  name?: string | undefined;
};

export type GetListListable = {
  id?: number | undefined;
  number?: string | undefined;
};

export type GetListItem = {
  id?: number | undefined;
  position?: number | undefined;
  note?: string | undefined;
  listable?: GetListListable | undefined;
};

export type GetListData = {
  id?: number | undefined;
  title?: string | undefined;
  description?: string | undefined;
  entityType?: string | undefined;
  isRanked?: boolean | undefined;
  isPrivate?: boolean | undefined;
  itemsCount?: number | undefined;
  likesCount?: number | undefined;
  savesCount?: number | undefined;
  user?: GetListUser | undefined;
  items?: Array<GetListItem> | undefined;
  createdAt?: string | undefined;
};

/**
 * Success
 */
export type GetListResponseBody = {
  data?: GetListData | undefined;
};

export type GetListResponse = {
  headers: { [k: string]: Array<string> };
  result: GetListResponseBody;
};

/** @internal */
export type GetListRequest$Outbound = {
  list_id: number;
};

/** @internal */
export const GetListRequest$outboundSchema: z.ZodMiniType<
  GetListRequest$Outbound,
  GetListRequest
> = z.pipe(
  z.object({
    listId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      listId: "list_id",
    });
  }),
);

export function getListRequestToJSON(getListRequest: GetListRequest): string {
  return JSON.stringify(GetListRequest$outboundSchema.parse(getListRequest));
}

/** @internal */
export const GetListUser$inboundSchema: z.ZodMiniType<GetListUser, unknown> = z
  .object({
    id: types.optional(types.number()),
    username: types.optional(types.string()),
    name: types.optional(types.string()),
  });

export function getListUserFromJSON(
  jsonString: string,
): SafeParseResult<GetListUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetListUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetListUser' from JSON`,
  );
}

/** @internal */
export const GetListListable$inboundSchema: z.ZodMiniType<
  GetListListable,
  unknown
> = z.object({
  id: types.optional(types.number()),
  number: types.optional(types.string()),
});

export function getListListableFromJSON(
  jsonString: string,
): SafeParseResult<GetListListable, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetListListable$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetListListable' from JSON`,
  );
}

/** @internal */
export const GetListItem$inboundSchema: z.ZodMiniType<GetListItem, unknown> = z
  .object({
    id: types.optional(types.number()),
    position: types.optional(types.number()),
    note: types.optional(types.string()),
    listable: types.optional(z.lazy(() => GetListListable$inboundSchema)),
  });

export function getListItemFromJSON(
  jsonString: string,
): SafeParseResult<GetListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetListItem' from JSON`,
  );
}

/** @internal */
export const GetListData$inboundSchema: z.ZodMiniType<GetListData, unknown> = z
  .pipe(
    z.object({
      id: types.optional(types.number()),
      title: types.optional(types.string()),
      description: types.optional(types.string()),
      entity_type: types.optional(types.string()),
      is_ranked: types.optional(types.boolean()),
      is_private: types.optional(types.boolean()),
      items_count: types.optional(types.number()),
      likes_count: types.optional(types.number()),
      saves_count: types.optional(types.number()),
      user: types.optional(z.lazy(() => GetListUser$inboundSchema)),
      items: types.optional(z.array(z.lazy(() => GetListItem$inboundSchema))),
      created_at: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "entity_type": "entityType",
        "is_ranked": "isRanked",
        "is_private": "isPrivate",
        "items_count": "itemsCount",
        "likes_count": "likesCount",
        "saves_count": "savesCount",
        "created_at": "createdAt",
      });
    }),
  );

export function getListDataFromJSON(
  jsonString: string,
): SafeParseResult<GetListData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetListData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetListData' from JSON`,
  );
}

/** @internal */
export const GetListResponseBody$inboundSchema: z.ZodMiniType<
  GetListResponseBody,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => GetListData$inboundSchema)),
});

export function getListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetListResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetListResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetListResponseBody' from JSON`,
  );
}

/** @internal */
export const GetListResponse$inboundSchema: z.ZodMiniType<
  GetListResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetListResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getListResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetListResponse' from JSON`,
  );
}
