/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponseBody = {
  subscribed?: boolean | undefined;
  subscribedAt?: string | undefined;
};

export type GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponse = {
  headers: { [k: string]: Array<string> };
  result: GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponseBody;
};

/** @internal */
export const GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponseBody$inboundSchema:
  z.ZodMiniType<
    GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponseBody,
    unknown
  > = z.pipe(
    z.object({
      subscribed: types.optional(types.boolean()),
      subscribed_at: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "subscribed_at": "subscribedAt",
      });
    }),
  );

export function getTheAuthenticatedUsersNewsletterSubscriptionStatusResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponseBody' from JSON`,
  );
}

/** @internal */
export const GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponse$inboundSchema:
  z.ZodMiniType<
    GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getTheAuthenticatedUsersNewsletterSubscriptionStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetTheAuthenticatedUsersNewsletterSubscriptionStatusResponse' from JSON`,
  );
}
