/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetKeyIssueReasonsRequest = {
  /**
   * The issue ID.
   */
  issueId: number;
};

export type GetKeyIssueReasonsData = {
  id?: number | undefined;
  name?: string | undefined;
  category?: string | undefined;
  description?: string | undefined;
  notes?: string | undefined;
  source?: string | undefined;
};

/**
 * Success
 */
export type GetKeyIssueReasonsResponseBody = {
  data?: Array<GetKeyIssueReasonsData> | undefined;
};

export type GetKeyIssueReasonsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetKeyIssueReasonsResponseBody;
};

/** @internal */
export type GetKeyIssueReasonsRequest$Outbound = {
  issue_id: number;
};

/** @internal */
export const GetKeyIssueReasonsRequest$outboundSchema: z.ZodMiniType<
  GetKeyIssueReasonsRequest$Outbound,
  GetKeyIssueReasonsRequest
> = z.pipe(
  z.object({
    issueId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      issueId: "issue_id",
    });
  }),
);

export function getKeyIssueReasonsRequestToJSON(
  getKeyIssueReasonsRequest: GetKeyIssueReasonsRequest,
): string {
  return JSON.stringify(
    GetKeyIssueReasonsRequest$outboundSchema.parse(getKeyIssueReasonsRequest),
  );
}

/** @internal */
export const GetKeyIssueReasonsData$inboundSchema: z.ZodMiniType<
  GetKeyIssueReasonsData,
  unknown
> = z.object({
  id: types.optional(types.number()),
  name: types.optional(types.string()),
  category: types.optional(types.string()),
  description: types.optional(types.string()),
  notes: types.optional(types.string()),
  source: types.optional(types.string()),
});

export function getKeyIssueReasonsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetKeyIssueReasonsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetKeyIssueReasonsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetKeyIssueReasonsData' from JSON`,
  );
}

/** @internal */
export const GetKeyIssueReasonsResponseBody$inboundSchema: z.ZodMiniType<
  GetKeyIssueReasonsResponseBody,
  unknown
> = z.object({
  data: types.optional(
    z.array(z.lazy(() => GetKeyIssueReasonsData$inboundSchema)),
  ),
});

export function getKeyIssueReasonsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetKeyIssueReasonsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetKeyIssueReasonsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetKeyIssueReasonsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetKeyIssueReasonsResponse$inboundSchema: z.ZodMiniType<
  GetKeyIssueReasonsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetKeyIssueReasonsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getKeyIssueReasonsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetKeyIssueReasonsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetKeyIssueReasonsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetKeyIssueReasonsResponse' from JSON`,
  );
}
