/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewRequest =
  {
    /**
     * The ID of the issue.
     */
    issueId: number;
  };

export type GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewData = {
  gradeType?: string | undefined;
  gradeValue?: string | null | undefined;
  gradeDisplay?: string | undefined;
  avgPriceUsd?: string | undefined;
  minPriceUsd?: string | undefined;
  maxPriceUsd?: string | undefined;
  medianPriceUsd?: string | undefined;
  salesCount?: number | undefined;
  snapshotDate?: string | undefined;
};

export type PriceEstimates = {
  low?: number | undefined;
  mid?: number | undefined;
  high?: number | undefined;
};

export type GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewMeta = {
  issueId?: number | undefined;
  estimatedRawValue?: string | undefined;
  estimated98Value?: string | undefined;
  priceEstimates?: PriceEstimates | undefined;
  priceTrend?: string | undefined;
  isPro?: boolean | undefined;
};

/**
 * Success
 */
export type GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponseBody =
  {
    data?:
      | Array<GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewData>
      | undefined;
    meta?:
      | GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewMeta
      | undefined;
  };

export type GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponseBody;
  };

/** @internal */
export type GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewRequest$Outbound =
  {
    issue_id: number;
  };

/** @internal */
export const GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewRequest$outboundSchema:
  z.ZodMiniType<
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewRequest$Outbound,
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewRequest
  > = z.pipe(
    z.object({
      issueId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        issueId: "issue_id",
      });
    }),
  );

export function getAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewRequestToJSON(
  getAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewRequest:
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewRequest,
): string {
  return JSON.stringify(
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewRequest$outboundSchema
      .parse(
        getAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewRequest,
      ),
  );
}

/** @internal */
export const GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewData$inboundSchema:
  z.ZodMiniType<
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewData,
    unknown
  > = z.pipe(
    z.object({
      grade_type: types.optional(types.string()),
      grade_value: z.optional(z.nullable(types.string())),
      grade_display: types.optional(types.string()),
      avg_price_usd: types.optional(types.string()),
      min_price_usd: types.optional(types.string()),
      max_price_usd: types.optional(types.string()),
      median_price_usd: types.optional(types.string()),
      sales_count: types.optional(types.number()),
      snapshot_date: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "grade_type": "gradeType",
        "grade_value": "gradeValue",
        "grade_display": "gradeDisplay",
        "avg_price_usd": "avgPriceUsd",
        "min_price_usd": "minPriceUsd",
        "max_price_usd": "maxPriceUsd",
        "median_price_usd": "medianPriceUsd",
        "sales_count": "salesCount",
        "snapshot_date": "snapshotDate",
      });
    }),
  );

export function getAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewData$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewData' from JSON`,
  );
}

/** @internal */
export const PriceEstimates$inboundSchema: z.ZodMiniType<
  PriceEstimates,
  unknown
> = z.object({
  low: types.optional(types.number()),
  mid: types.optional(types.number()),
  high: types.optional(types.number()),
});

export function priceEstimatesFromJSON(
  jsonString: string,
): SafeParseResult<PriceEstimates, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PriceEstimates$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PriceEstimates' from JSON`,
  );
}

/** @internal */
export const GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewMeta$inboundSchema:
  z.ZodMiniType<
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewMeta,
    unknown
  > = z.pipe(
    z.object({
      issue_id: types.optional(types.number()),
      estimated_raw_value: types.optional(types.string()),
      estimated_98_value: types.optional(types.string()),
      price_estimates: types.optional(
        z.lazy(() => PriceEstimates$inboundSchema),
      ),
      price_trend: types.optional(types.string()),
      is_pro: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "issue_id": "issueId",
        "estimated_raw_value": "estimatedRawValue",
        "estimated_98_value": "estimated98Value",
        "price_estimates": "priceEstimates",
        "price_trend": "priceTrend",
        "is_pro": "isPro",
      });
    }),
  );

export function getAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewMetaFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewMeta,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewMeta$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewMeta' from JSON`,
  );
}

/** @internal */
export const GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponseBody$inboundSchema:
  z.ZodMiniType<
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponseBody,
    unknown
  > = z.object({
    data: types.optional(
      z.array(z.lazy(() =>
        GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewData$inboundSchema
      )),
    ),
    meta: types.optional(
      z.lazy(() =>
        GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewMeta$inboundSchema
      ),
    ),
  });

export function getAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponseBody' from JSON`,
  );
}

/** @internal */
export const GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponse$inboundSchema:
  z.ZodMiniType<
    GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetAllPriceSnapshotsForAllGradesOfAnIssueforPricingOverviewResponse' from JSON`,
  );
}
