/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetCharactersForASpecificTeammembersRequest = {
  /**
   * The ID of the team.
   */
  teamId: number;
};

export type GetCharactersForASpecificTeammembersImages = {
  tileSm?: string | undefined;
  profileMd?: string | undefined;
  fullLg?: string | undefined;
};

export type GetCharactersForASpecificTeammembersData = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  realName?: string | undefined;
  aliases?: Array<string> | undefined;
  race?: string | undefined;
  imageUrl?: string | undefined;
  images?: GetCharactersForASpecificTeammembersImages | undefined;
  appearancesCount?: number | undefined;
  publisherName?: string | undefined;
  pivotRole?: string | undefined;
  pivotJoinedDate?: string | undefined;
  pivotIsSpoiler?: boolean | undefined;
};

export type GetCharactersForASpecificTeammembersMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type GetCharactersForASpecificTeammembersResponseBody = {
  data?: Array<GetCharactersForASpecificTeammembersData> | undefined;
  meta?: GetCharactersForASpecificTeammembersMeta | undefined;
};

export type GetCharactersForASpecificTeammembersResponse = {
  headers: { [k: string]: Array<string> };
  result: GetCharactersForASpecificTeammembersResponseBody;
};

/** @internal */
export type GetCharactersForASpecificTeammembersRequest$Outbound = {
  team_id: number;
};

/** @internal */
export const GetCharactersForASpecificTeammembersRequest$outboundSchema:
  z.ZodMiniType<
    GetCharactersForASpecificTeammembersRequest$Outbound,
    GetCharactersForASpecificTeammembersRequest
  > = z.pipe(
    z.object({
      teamId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        teamId: "team_id",
      });
    }),
  );

export function getCharactersForASpecificTeammembersRequestToJSON(
  getCharactersForASpecificTeammembersRequest:
    GetCharactersForASpecificTeammembersRequest,
): string {
  return JSON.stringify(
    GetCharactersForASpecificTeammembersRequest$outboundSchema.parse(
      getCharactersForASpecificTeammembersRequest,
    ),
  );
}

/** @internal */
export const GetCharactersForASpecificTeammembersImages$inboundSchema:
  z.ZodMiniType<GetCharactersForASpecificTeammembersImages, unknown> = z.pipe(
    z.object({
      tile_sm: types.optional(types.string()),
      profile_md: types.optional(types.string()),
      full_lg: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "tile_sm": "tileSm",
        "profile_md": "profileMd",
        "full_lg": "fullLg",
      });
    }),
  );

export function getCharactersForASpecificTeammembersImagesFromJSON(
  jsonString: string,
): SafeParseResult<
  GetCharactersForASpecificTeammembersImages,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetCharactersForASpecificTeammembersImages$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetCharactersForASpecificTeammembersImages' from JSON`,
  );
}

/** @internal */
export const GetCharactersForASpecificTeammembersData$inboundSchema:
  z.ZodMiniType<GetCharactersForASpecificTeammembersData, unknown> = z.pipe(
    z.object({
      id: types.optional(types.number()),
      name: types.optional(types.string()),
      slug: types.optional(types.string()),
      real_name: types.optional(types.string()),
      aliases: types.optional(z.array(types.string())),
      race: types.optional(types.string()),
      image_url: types.optional(types.string()),
      images: types.optional(z.lazy(() =>
        GetCharactersForASpecificTeammembersImages$inboundSchema
      )),
      appearances_count: types.optional(types.number()),
      publisher_name: types.optional(types.string()),
      pivot_role: types.optional(types.string()),
      pivot_joined_date: types.optional(types.string()),
      pivot_is_spoiler: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "real_name": "realName",
        "image_url": "imageUrl",
        "appearances_count": "appearancesCount",
        "publisher_name": "publisherName",
        "pivot_role": "pivotRole",
        "pivot_joined_date": "pivotJoinedDate",
        "pivot_is_spoiler": "pivotIsSpoiler",
      });
    }),
  );

export function getCharactersForASpecificTeammembersDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetCharactersForASpecificTeammembersData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetCharactersForASpecificTeammembersData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetCharactersForASpecificTeammembersData' from JSON`,
  );
}

/** @internal */
export const GetCharactersForASpecificTeammembersMeta$inboundSchema:
  z.ZodMiniType<GetCharactersForASpecificTeammembersMeta, unknown> = z.pipe(
    z.object({
      current_page: types.optional(types.number()),
      last_page: types.optional(types.number()),
      per_page: types.optional(types.number()),
      total: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "current_page": "currentPage",
        "last_page": "lastPage",
        "per_page": "perPage",
      });
    }),
  );

export function getCharactersForASpecificTeammembersMetaFromJSON(
  jsonString: string,
): SafeParseResult<
  GetCharactersForASpecificTeammembersMeta,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetCharactersForASpecificTeammembersMeta$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetCharactersForASpecificTeammembersMeta' from JSON`,
  );
}

/** @internal */
export const GetCharactersForASpecificTeammembersResponseBody$inboundSchema:
  z.ZodMiniType<GetCharactersForASpecificTeammembersResponseBody, unknown> = z
    .object({
      data: types.optional(
        z.array(z.lazy(() =>
          GetCharactersForASpecificTeammembersData$inboundSchema
        )),
      ),
      meta: types.optional(
        z.lazy(() => GetCharactersForASpecificTeammembersMeta$inboundSchema),
      ),
    });

export function getCharactersForASpecificTeammembersResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetCharactersForASpecificTeammembersResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetCharactersForASpecificTeammembersResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetCharactersForASpecificTeammembersResponseBody' from JSON`,
  );
}

/** @internal */
export const GetCharactersForASpecificTeammembersResponse$inboundSchema:
  z.ZodMiniType<GetCharactersForASpecificTeammembersResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetCharactersForASpecificTeammembersResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getCharactersForASpecificTeammembersResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetCharactersForASpecificTeammembersResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetCharactersForASpecificTeammembersResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetCharactersForASpecificTeammembersResponse' from JSON`,
  );
}
