/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetASpecificUniverseRequest = {
  /**
   * The ID of the universe.
   */
  universeId: number;
};

export type GetASpecificUniverseData = {
  id?: number | undefined;
  name?: string | undefined;
  description?: string | undefined;
};

/**
 * Success
 */
export type GetASpecificUniverseResponseBody = {
  data?: GetASpecificUniverseData | undefined;
};

export type GetASpecificUniverseResponse = {
  headers: { [k: string]: Array<string> };
  result: GetASpecificUniverseResponseBody;
};

/** @internal */
export type GetASpecificUniverseRequest$Outbound = {
  universe_id: number;
};

/** @internal */
export const GetASpecificUniverseRequest$outboundSchema: z.ZodMiniType<
  GetASpecificUniverseRequest$Outbound,
  GetASpecificUniverseRequest
> = z.pipe(
  z.object({
    universeId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      universeId: "universe_id",
    });
  }),
);

export function getASpecificUniverseRequestToJSON(
  getASpecificUniverseRequest: GetASpecificUniverseRequest,
): string {
  return JSON.stringify(
    GetASpecificUniverseRequest$outboundSchema.parse(
      getASpecificUniverseRequest,
    ),
  );
}

/** @internal */
export const GetASpecificUniverseData$inboundSchema: z.ZodMiniType<
  GetASpecificUniverseData,
  unknown
> = z.object({
  id: types.optional(types.number()),
  name: types.optional(types.string()),
  description: types.optional(types.string()),
});

export function getASpecificUniverseDataFromJSON(
  jsonString: string,
): SafeParseResult<GetASpecificUniverseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetASpecificUniverseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetASpecificUniverseData' from JSON`,
  );
}

/** @internal */
export const GetASpecificUniverseResponseBody$inboundSchema: z.ZodMiniType<
  GetASpecificUniverseResponseBody,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => GetASpecificUniverseData$inboundSchema)),
});

export function getASpecificUniverseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetASpecificUniverseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetASpecificUniverseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetASpecificUniverseResponseBody' from JSON`,
  );
}

/** @internal */
export const GetASpecificUniverseResponse$inboundSchema: z.ZodMiniType<
  GetASpecificUniverseResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetASpecificUniverseResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getASpecificUniverseResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetASpecificUniverseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetASpecificUniverseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetASpecificUniverseResponse' from JSON`,
  );
}
