/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetCreatorDetailsRequest = {
  /**
   * The creator ID.
   */
  creatorId: number;
};

export type GetCreatorDetailsRole = {
  id?: number | undefined;
  name?: string | undefined;
};

export type GetCreatorDetailsImages = {
  tileSm?: string | undefined;
  profileMd?: string | undefined;
  fullLg?: string | undefined;
};

export type GetCreatorDetailsLinks = {
  website?: string | undefined;
  twitter?: string | undefined;
};

export type Award = {
  name?: string | undefined;
  year?: number | undefined;
};

export type GetCreatorDetailsData = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  role?: GetCreatorDetailsRole | undefined;
  photoUrl?: string | undefined;
  images?: GetCreatorDetailsImages | undefined;
  biography?: string | undefined;
  gender?: string | undefined;
  birth?: string | undefined;
  death?: string | null | undefined;
  birthPlace?: string | undefined;
  country?: string | undefined;
  aliases?: Array<any> | undefined;
  links?: GetCreatorDetailsLinks | undefined;
  awards?: Array<Award> | undefined;
};

/**
 * Success
 */
export type GetCreatorDetailsResponseBody = {
  data?: GetCreatorDetailsData | undefined;
};

export type GetCreatorDetailsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetCreatorDetailsResponseBody;
};

/** @internal */
export type GetCreatorDetailsRequest$Outbound = {
  creator_id: number;
};

/** @internal */
export const GetCreatorDetailsRequest$outboundSchema: z.ZodMiniType<
  GetCreatorDetailsRequest$Outbound,
  GetCreatorDetailsRequest
> = z.pipe(
  z.object({
    creatorId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      creatorId: "creator_id",
    });
  }),
);

export function getCreatorDetailsRequestToJSON(
  getCreatorDetailsRequest: GetCreatorDetailsRequest,
): string {
  return JSON.stringify(
    GetCreatorDetailsRequest$outboundSchema.parse(getCreatorDetailsRequest),
  );
}

/** @internal */
export const GetCreatorDetailsRole$inboundSchema: z.ZodMiniType<
  GetCreatorDetailsRole,
  unknown
> = z.object({
  id: types.optional(types.number()),
  name: types.optional(types.string()),
});

export function getCreatorDetailsRoleFromJSON(
  jsonString: string,
): SafeParseResult<GetCreatorDetailsRole, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreatorDetailsRole$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreatorDetailsRole' from JSON`,
  );
}

/** @internal */
export const GetCreatorDetailsImages$inboundSchema: z.ZodMiniType<
  GetCreatorDetailsImages,
  unknown
> = z.pipe(
  z.object({
    tile_sm: types.optional(types.string()),
    profile_md: types.optional(types.string()),
    full_lg: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tile_sm": "tileSm",
      "profile_md": "profileMd",
      "full_lg": "fullLg",
    });
  }),
);

export function getCreatorDetailsImagesFromJSON(
  jsonString: string,
): SafeParseResult<GetCreatorDetailsImages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreatorDetailsImages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreatorDetailsImages' from JSON`,
  );
}

/** @internal */
export const GetCreatorDetailsLinks$inboundSchema: z.ZodMiniType<
  GetCreatorDetailsLinks,
  unknown
> = z.object({
  website: types.optional(types.string()),
  twitter: types.optional(types.string()),
});

export function getCreatorDetailsLinksFromJSON(
  jsonString: string,
): SafeParseResult<GetCreatorDetailsLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreatorDetailsLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreatorDetailsLinks' from JSON`,
  );
}

/** @internal */
export const Award$inboundSchema: z.ZodMiniType<Award, unknown> = z.object({
  name: types.optional(types.string()),
  year: types.optional(types.number()),
});

export function awardFromJSON(
  jsonString: string,
): SafeParseResult<Award, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Award$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Award' from JSON`,
  );
}

/** @internal */
export const GetCreatorDetailsData$inboundSchema: z.ZodMiniType<
  GetCreatorDetailsData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    slug: types.optional(types.string()),
    role: types.optional(z.lazy(() => GetCreatorDetailsRole$inboundSchema)),
    photo_url: types.optional(types.string()),
    images: types.optional(z.lazy(() => GetCreatorDetailsImages$inboundSchema)),
    biography: types.optional(types.string()),
    gender: types.optional(types.string()),
    birth: types.optional(types.string()),
    death: z.optional(z.nullable(types.string())),
    birth_place: types.optional(types.string()),
    country: types.optional(types.string()),
    aliases: types.optional(z.array(z.any())),
    links: types.optional(z.lazy(() => GetCreatorDetailsLinks$inboundSchema)),
    awards: types.optional(z.array(z.lazy(() => Award$inboundSchema))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "photo_url": "photoUrl",
      "birth_place": "birthPlace",
    });
  }),
);

export function getCreatorDetailsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCreatorDetailsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreatorDetailsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreatorDetailsData' from JSON`,
  );
}

/** @internal */
export const GetCreatorDetailsResponseBody$inboundSchema: z.ZodMiniType<
  GetCreatorDetailsResponseBody,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => GetCreatorDetailsData$inboundSchema)),
});

export function getCreatorDetailsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetCreatorDetailsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreatorDetailsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreatorDetailsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetCreatorDetailsResponse$inboundSchema: z.ZodMiniType<
  GetCreatorDetailsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetCreatorDetailsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getCreatorDetailsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCreatorDetailsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreatorDetailsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreatorDetailsResponse' from JSON`,
  );
}
