/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetStoryArcsForASpecificIssueRequest = {
  /**
   * The ID of the issue.
   */
  issueId: number;
};

export type GetStoryArcsForASpecificIssueImages = {
  coverSm?: string | undefined;
  coverMd?: string | undefined;
  coverLg?: string | undefined;
};

export type GetStoryArcsForASpecificIssueData = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  type?: string | undefined;
  status?: string | undefined;
  imageUrl?: string | undefined;
  images?: GetStoryArcsForASpecificIssueImages | undefined;
  issuesCount?: number | undefined;
};

export type GetStoryArcsForASpecificIssueMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type GetStoryArcsForASpecificIssueResponseBody = {
  data?: Array<GetStoryArcsForASpecificIssueData> | undefined;
  meta?: GetStoryArcsForASpecificIssueMeta | undefined;
};

export type GetStoryArcsForASpecificIssueResponse = {
  headers: { [k: string]: Array<string> };
  result: GetStoryArcsForASpecificIssueResponseBody;
};

/** @internal */
export type GetStoryArcsForASpecificIssueRequest$Outbound = {
  issue_id: number;
};

/** @internal */
export const GetStoryArcsForASpecificIssueRequest$outboundSchema: z.ZodMiniType<
  GetStoryArcsForASpecificIssueRequest$Outbound,
  GetStoryArcsForASpecificIssueRequest
> = z.pipe(
  z.object({
    issueId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      issueId: "issue_id",
    });
  }),
);

export function getStoryArcsForASpecificIssueRequestToJSON(
  getStoryArcsForASpecificIssueRequest: GetStoryArcsForASpecificIssueRequest,
): string {
  return JSON.stringify(
    GetStoryArcsForASpecificIssueRequest$outboundSchema.parse(
      getStoryArcsForASpecificIssueRequest,
    ),
  );
}

/** @internal */
export const GetStoryArcsForASpecificIssueImages$inboundSchema: z.ZodMiniType<
  GetStoryArcsForASpecificIssueImages,
  unknown
> = z.pipe(
  z.object({
    cover_sm: types.optional(types.string()),
    cover_md: types.optional(types.string()),
    cover_lg: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "cover_sm": "coverSm",
      "cover_md": "coverMd",
      "cover_lg": "coverLg",
    });
  }),
);

export function getStoryArcsForASpecificIssueImagesFromJSON(
  jsonString: string,
): SafeParseResult<GetStoryArcsForASpecificIssueImages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetStoryArcsForASpecificIssueImages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStoryArcsForASpecificIssueImages' from JSON`,
  );
}

/** @internal */
export const GetStoryArcsForASpecificIssueData$inboundSchema: z.ZodMiniType<
  GetStoryArcsForASpecificIssueData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    slug: types.optional(types.string()),
    type: types.optional(types.string()),
    status: types.optional(types.string()),
    image_url: types.optional(types.string()),
    images: types.optional(
      z.lazy(() => GetStoryArcsForASpecificIssueImages$inboundSchema),
    ),
    issues_count: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "image_url": "imageUrl",
      "issues_count": "issuesCount",
    });
  }),
);

export function getStoryArcsForASpecificIssueDataFromJSON(
  jsonString: string,
): SafeParseResult<GetStoryArcsForASpecificIssueData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStoryArcsForASpecificIssueData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStoryArcsForASpecificIssueData' from JSON`,
  );
}

/** @internal */
export const GetStoryArcsForASpecificIssueMeta$inboundSchema: z.ZodMiniType<
  GetStoryArcsForASpecificIssueMeta,
  unknown
> = z.pipe(
  z.object({
    current_page: types.optional(types.number()),
    last_page: types.optional(types.number()),
    per_page: types.optional(types.number()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_page": "currentPage",
      "last_page": "lastPage",
      "per_page": "perPage",
    });
  }),
);

export function getStoryArcsForASpecificIssueMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetStoryArcsForASpecificIssueMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStoryArcsForASpecificIssueMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStoryArcsForASpecificIssueMeta' from JSON`,
  );
}

/** @internal */
export const GetStoryArcsForASpecificIssueResponseBody$inboundSchema:
  z.ZodMiniType<GetStoryArcsForASpecificIssueResponseBody, unknown> = z.object({
    data: types.optional(
      z.array(z.lazy(() => GetStoryArcsForASpecificIssueData$inboundSchema)),
    ),
    meta: types.optional(
      z.lazy(() => GetStoryArcsForASpecificIssueMeta$inboundSchema),
    ),
  });

export function getStoryArcsForASpecificIssueResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetStoryArcsForASpecificIssueResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetStoryArcsForASpecificIssueResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetStoryArcsForASpecificIssueResponseBody' from JSON`,
  );
}

/** @internal */
export const GetStoryArcsForASpecificIssueResponse$inboundSchema: z.ZodMiniType<
  GetStoryArcsForASpecificIssueResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() =>
      GetStoryArcsForASpecificIssueResponseBody$inboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getStoryArcsForASpecificIssueResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetStoryArcsForASpecificIssueResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetStoryArcsForASpecificIssueResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStoryArcsForASpecificIssueResponse' from JSON`,
  );
}
