/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetCharacterTeamsRequest = {
  /**
   * The character ID.
   */
  characterId: number;
  /**
   * Results per page (max 50).
   */
  limit?: number | undefined;
};

export type Membership = {
  role?: string | undefined;
  joinedDate?: string | undefined;
  leftDate?: string | null | undefined;
};

export type GetCharacterTeamsData = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  imageUrl?: string | undefined;
  membership?: Membership | undefined;
};

export type GetCharacterTeamsMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type GetCharacterTeamsResponseBody = {
  data?: Array<GetCharacterTeamsData> | undefined;
  meta?: GetCharacterTeamsMeta | undefined;
};

export type GetCharacterTeamsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetCharacterTeamsResponseBody;
};

/** @internal */
export type GetCharacterTeamsRequest$Outbound = {
  character_id: number;
  limit?: number | undefined;
};

/** @internal */
export const GetCharacterTeamsRequest$outboundSchema: z.ZodMiniType<
  GetCharacterTeamsRequest$Outbound,
  GetCharacterTeamsRequest
> = z.pipe(
  z.object({
    characterId: z.int(),
    limit: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      characterId: "character_id",
    });
  }),
);

export function getCharacterTeamsRequestToJSON(
  getCharacterTeamsRequest: GetCharacterTeamsRequest,
): string {
  return JSON.stringify(
    GetCharacterTeamsRequest$outboundSchema.parse(getCharacterTeamsRequest),
  );
}

/** @internal */
export const Membership$inboundSchema: z.ZodMiniType<Membership, unknown> = z
  .pipe(
    z.object({
      role: types.optional(types.string()),
      joined_date: types.optional(types.string()),
      left_date: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "joined_date": "joinedDate",
        "left_date": "leftDate",
      });
    }),
  );

export function membershipFromJSON(
  jsonString: string,
): SafeParseResult<Membership, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Membership$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Membership' from JSON`,
  );
}

/** @internal */
export const GetCharacterTeamsData$inboundSchema: z.ZodMiniType<
  GetCharacterTeamsData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    slug: types.optional(types.string()),
    image_url: types.optional(types.string()),
    membership: types.optional(z.lazy(() => Membership$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "image_url": "imageUrl",
    });
  }),
);

export function getCharacterTeamsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCharacterTeamsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCharacterTeamsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCharacterTeamsData' from JSON`,
  );
}

/** @internal */
export const GetCharacterTeamsMeta$inboundSchema: z.ZodMiniType<
  GetCharacterTeamsMeta,
  unknown
> = z.pipe(
  z.object({
    current_page: types.optional(types.number()),
    last_page: types.optional(types.number()),
    per_page: types.optional(types.number()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_page": "currentPage",
      "last_page": "lastPage",
      "per_page": "perPage",
    });
  }),
);

export function getCharacterTeamsMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetCharacterTeamsMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCharacterTeamsMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCharacterTeamsMeta' from JSON`,
  );
}

/** @internal */
export const GetCharacterTeamsResponseBody$inboundSchema: z.ZodMiniType<
  GetCharacterTeamsResponseBody,
  unknown
> = z.object({
  data: types.optional(
    z.array(z.lazy(() => GetCharacterTeamsData$inboundSchema)),
  ),
  meta: types.optional(z.lazy(() => GetCharacterTeamsMeta$inboundSchema)),
});

export function getCharacterTeamsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetCharacterTeamsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCharacterTeamsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCharacterTeamsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetCharacterTeamsResponse$inboundSchema: z.ZodMiniType<
  GetCharacterTeamsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetCharacterTeamsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getCharacterTeamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCharacterTeamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCharacterTeamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCharacterTeamsResponse' from JSON`,
  );
}
