/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetASpecificPodcastEpisodeRequest = {
  /**
   * The ID of the podcast.
   */
  podcastId: number;
  /**
   * The ID of the episode.
   */
  episodeId: number;
};

export type GetASpecificPodcastEpisodeData = {
  id?: number | undefined;
  podcastId?: number | undefined;
  title?: string | undefined;
  description?: string | undefined;
  audioUrl?: string | undefined;
  videoUrl?: string | null | undefined;
  isVideo?: boolean | undefined;
  artworkUrl?: string | undefined;
  pubDate?: string | undefined;
  duration?: number | undefined;
  durationFormatted?: string | undefined;
};

/**
 * Success
 */
export type GetASpecificPodcastEpisodeResponseBody = {
  data?: GetASpecificPodcastEpisodeData | undefined;
};

export type GetASpecificPodcastEpisodeResponse = {
  headers: { [k: string]: Array<string> };
  result: GetASpecificPodcastEpisodeResponseBody;
};

/** @internal */
export type GetASpecificPodcastEpisodeRequest$Outbound = {
  podcast_id: number;
  episode_id: number;
};

/** @internal */
export const GetASpecificPodcastEpisodeRequest$outboundSchema: z.ZodMiniType<
  GetASpecificPodcastEpisodeRequest$Outbound,
  GetASpecificPodcastEpisodeRequest
> = z.pipe(
  z.object({
    podcastId: z.int(),
    episodeId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      podcastId: "podcast_id",
      episodeId: "episode_id",
    });
  }),
);

export function getASpecificPodcastEpisodeRequestToJSON(
  getASpecificPodcastEpisodeRequest: GetASpecificPodcastEpisodeRequest,
): string {
  return JSON.stringify(
    GetASpecificPodcastEpisodeRequest$outboundSchema.parse(
      getASpecificPodcastEpisodeRequest,
    ),
  );
}

/** @internal */
export const GetASpecificPodcastEpisodeData$inboundSchema: z.ZodMiniType<
  GetASpecificPodcastEpisodeData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    podcast_id: types.optional(types.number()),
    title: types.optional(types.string()),
    description: types.optional(types.string()),
    audio_url: types.optional(types.string()),
    video_url: z.optional(z.nullable(types.string())),
    is_video: types.optional(types.boolean()),
    artwork_url: types.optional(types.string()),
    pub_date: types.optional(types.string()),
    duration: types.optional(types.number()),
    duration_formatted: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "podcast_id": "podcastId",
      "audio_url": "audioUrl",
      "video_url": "videoUrl",
      "is_video": "isVideo",
      "artwork_url": "artworkUrl",
      "pub_date": "pubDate",
      "duration_formatted": "durationFormatted",
    });
  }),
);

export function getASpecificPodcastEpisodeDataFromJSON(
  jsonString: string,
): SafeParseResult<GetASpecificPodcastEpisodeData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetASpecificPodcastEpisodeData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetASpecificPodcastEpisodeData' from JSON`,
  );
}

/** @internal */
export const GetASpecificPodcastEpisodeResponseBody$inboundSchema:
  z.ZodMiniType<GetASpecificPodcastEpisodeResponseBody, unknown> = z.object({
    data: types.optional(
      z.lazy(() => GetASpecificPodcastEpisodeData$inboundSchema),
    ),
  });

export function getASpecificPodcastEpisodeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetASpecificPodcastEpisodeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetASpecificPodcastEpisodeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetASpecificPodcastEpisodeResponseBody' from JSON`,
  );
}

/** @internal */
export const GetASpecificPodcastEpisodeResponse$inboundSchema: z.ZodMiniType<
  GetASpecificPodcastEpisodeResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetASpecificPodcastEpisodeResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getASpecificPodcastEpisodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetASpecificPodcastEpisodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetASpecificPodcastEpisodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetASpecificPodcastEpisodeResponse' from JSON`,
  );
}
