/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetAComicShopRequest = {
  /**
   * The shop ID.
   */
  shopId: number;
};

export type GetAComicShopData = {
  id?: number | undefined;
  name?: string | undefined;
  description?: string | undefined;
  address?: string | undefined;
  city?: string | undefined;
  stateProvince?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;
  phone?: string | undefined;
  website?: string | null | undefined;
  email?: string | undefined;
  latitude?: string | undefined;
  longitude?: string | undefined;
  fullAddress?: string | undefined;
  logoUrl?: string | null | undefined;
  images?: string | null | undefined;
  operatingHours?: string | null | undefined;
  services?: Array<any> | undefined;
  events?: Array<any> | undefined;
  isFavorited?: boolean | undefined;
};

export type GetAComicShopResponseBody = {
  data?: GetAComicShopData | undefined;
};

export type GetAComicShopResponse = {
  headers: { [k: string]: Array<string> };
  result: GetAComicShopResponseBody;
};

/** @internal */
export type GetAComicShopRequest$Outbound = {
  shop_id: number;
};

/** @internal */
export const GetAComicShopRequest$outboundSchema: z.ZodMiniType<
  GetAComicShopRequest$Outbound,
  GetAComicShopRequest
> = z.pipe(
  z.object({
    shopId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      shopId: "shop_id",
    });
  }),
);

export function getAComicShopRequestToJSON(
  getAComicShopRequest: GetAComicShopRequest,
): string {
  return JSON.stringify(
    GetAComicShopRequest$outboundSchema.parse(getAComicShopRequest),
  );
}

/** @internal */
export const GetAComicShopData$inboundSchema: z.ZodMiniType<
  GetAComicShopData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    description: types.optional(types.string()),
    address: types.optional(types.string()),
    city: types.optional(types.string()),
    state_province: types.optional(types.string()),
    postal_code: types.optional(types.string()),
    country: types.optional(types.string()),
    phone: types.optional(types.string()),
    website: z.optional(z.nullable(types.string())),
    email: types.optional(types.string()),
    latitude: types.optional(types.string()),
    longitude: types.optional(types.string()),
    full_address: types.optional(types.string()),
    logo_url: z.optional(z.nullable(types.string())),
    images: z.optional(z.nullable(types.string())),
    operating_hours: z.optional(z.nullable(types.string())),
    services: types.optional(z.array(z.any())),
    events: types.optional(z.array(z.any())),
    is_favorited: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "state_province": "stateProvince",
      "postal_code": "postalCode",
      "full_address": "fullAddress",
      "logo_url": "logoUrl",
      "operating_hours": "operatingHours",
      "is_favorited": "isFavorited",
    });
  }),
);

export function getAComicShopDataFromJSON(
  jsonString: string,
): SafeParseResult<GetAComicShopData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAComicShopData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAComicShopData' from JSON`,
  );
}

/** @internal */
export const GetAComicShopResponseBody$inboundSchema: z.ZodMiniType<
  GetAComicShopResponseBody,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => GetAComicShopData$inboundSchema)),
});

export function getAComicShopResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetAComicShopResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAComicShopResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAComicShopResponseBody' from JSON`,
  );
}

/** @internal */
export const GetAComicShopResponse$inboundSchema: z.ZodMiniType<
  GetAComicShopResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetAComicShopResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getAComicShopResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAComicShopResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAComicShopResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAComicShopResponse' from JSON`,
  );
}
