/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type LikeListOrReactToItRequestBody = {
  /**
   * One of heart, laugh, wow, fire, clap, confused. Omit for a plain like.
   */
  reaction?: string | undefined;
};

export type LikeListOrReactToItRequest = {
  /**
   * The list ID.
   */
  listId: number;
  body?: LikeListOrReactToItRequestBody | undefined;
};

export type LikeListOrReactToItReaction2 = {
  reaction?: string | undefined;
  emoji?: string | undefined;
  label?: string | undefined;
  count?: number | undefined;
};

/**
 * Liked
 */
export type LikeListOrReactToItResponseBody = {
  message?: string | undefined;
  liked?: boolean | undefined;
  likesCount?: number | undefined;
  myReaction?: string | undefined;
  reactions?: Array<LikeListOrReactToItReaction2> | undefined;
};

/**
 * Already Liked
 */
export type LikeListOrReactToItResponseBody2 = {
  message?: string | undefined;
  liked?: boolean | undefined;
};

export type LikeListOrReactToItReaction1 = {
  reaction?: string | undefined;
  emoji?: string | undefined;
  label?: string | undefined;
  count?: number | undefined;
};

/**
 * Reaction changed
 */
export type LikeListOrReactToItResponseBody1 = {
  message?: string | undefined;
  liked?: boolean | undefined;
  likesCount?: number | undefined;
  myReaction?: string | undefined;
  reactions?: Array<LikeListOrReactToItReaction1> | undefined;
};

/**
 * Success.
 */
export type LikeListOrReactToItResponseBodyUnion =
  | LikeListOrReactToItResponseBody1
  | LikeListOrReactToItResponseBody2;

export type LikeListOrReactToItResponseResult =
  | LikeListOrReactToItResponseBody1
  | LikeListOrReactToItResponseBody2
  | LikeListOrReactToItResponseBody;

export type LikeListOrReactToItResponse = {
  headers: { [k: string]: Array<string> };
  result:
    | LikeListOrReactToItResponseBody1
    | LikeListOrReactToItResponseBody2
    | LikeListOrReactToItResponseBody;
};

/** @internal */
export type LikeListOrReactToItRequestBody$Outbound = {
  reaction?: string | undefined;
};

/** @internal */
export const LikeListOrReactToItRequestBody$outboundSchema: z.ZodMiniType<
  LikeListOrReactToItRequestBody$Outbound,
  LikeListOrReactToItRequestBody
> = z.object({
  reaction: z.optional(z.string()),
});

export function likeListOrReactToItRequestBodyToJSON(
  likeListOrReactToItRequestBody: LikeListOrReactToItRequestBody,
): string {
  return JSON.stringify(
    LikeListOrReactToItRequestBody$outboundSchema.parse(
      likeListOrReactToItRequestBody,
    ),
  );
}

/** @internal */
export type LikeListOrReactToItRequest$Outbound = {
  list_id: number;
  body?: LikeListOrReactToItRequestBody$Outbound | undefined;
};

/** @internal */
export const LikeListOrReactToItRequest$outboundSchema: z.ZodMiniType<
  LikeListOrReactToItRequest$Outbound,
  LikeListOrReactToItRequest
> = z.pipe(
  z.object({
    listId: z.int(),
    body: z.optional(
      z.lazy(() => LikeListOrReactToItRequestBody$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      listId: "list_id",
    });
  }),
);

export function likeListOrReactToItRequestToJSON(
  likeListOrReactToItRequest: LikeListOrReactToItRequest,
): string {
  return JSON.stringify(
    LikeListOrReactToItRequest$outboundSchema.parse(likeListOrReactToItRequest),
  );
}

/** @internal */
export const LikeListOrReactToItReaction2$inboundSchema: z.ZodMiniType<
  LikeListOrReactToItReaction2,
  unknown
> = z.object({
  reaction: types.optional(types.string()),
  emoji: types.optional(types.string()),
  label: types.optional(types.string()),
  count: types.optional(types.number()),
});

export function likeListOrReactToItReaction2FromJSON(
  jsonString: string,
): SafeParseResult<LikeListOrReactToItReaction2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LikeListOrReactToItReaction2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LikeListOrReactToItReaction2' from JSON`,
  );
}

/** @internal */
export const LikeListOrReactToItResponseBody$inboundSchema: z.ZodMiniType<
  LikeListOrReactToItResponseBody,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    liked: types.optional(types.boolean()),
    likes_count: types.optional(types.number()),
    my_reaction: types.optional(types.string()),
    reactions: types.optional(
      z.array(z.lazy(() => LikeListOrReactToItReaction2$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "likes_count": "likesCount",
      "my_reaction": "myReaction",
    });
  }),
);

export function likeListOrReactToItResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<LikeListOrReactToItResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LikeListOrReactToItResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LikeListOrReactToItResponseBody' from JSON`,
  );
}

/** @internal */
export const LikeListOrReactToItResponseBody2$inboundSchema: z.ZodMiniType<
  LikeListOrReactToItResponseBody2,
  unknown
> = z.object({
  message: types.optional(types.string()),
  liked: types.optional(types.boolean()),
});

export function likeListOrReactToItResponseBody2FromJSON(
  jsonString: string,
): SafeParseResult<LikeListOrReactToItResponseBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LikeListOrReactToItResponseBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LikeListOrReactToItResponseBody2' from JSON`,
  );
}

/** @internal */
export const LikeListOrReactToItReaction1$inboundSchema: z.ZodMiniType<
  LikeListOrReactToItReaction1,
  unknown
> = z.object({
  reaction: types.optional(types.string()),
  emoji: types.optional(types.string()),
  label: types.optional(types.string()),
  count: types.optional(types.number()),
});

export function likeListOrReactToItReaction1FromJSON(
  jsonString: string,
): SafeParseResult<LikeListOrReactToItReaction1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LikeListOrReactToItReaction1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LikeListOrReactToItReaction1' from JSON`,
  );
}

/** @internal */
export const LikeListOrReactToItResponseBody1$inboundSchema: z.ZodMiniType<
  LikeListOrReactToItResponseBody1,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    liked: types.optional(types.boolean()),
    likes_count: types.optional(types.number()),
    my_reaction: types.optional(types.string()),
    reactions: types.optional(
      z.array(z.lazy(() => LikeListOrReactToItReaction1$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "likes_count": "likesCount",
      "my_reaction": "myReaction",
    });
  }),
);

export function likeListOrReactToItResponseBody1FromJSON(
  jsonString: string,
): SafeParseResult<LikeListOrReactToItResponseBody1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LikeListOrReactToItResponseBody1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LikeListOrReactToItResponseBody1' from JSON`,
  );
}

/** @internal */
export const LikeListOrReactToItResponseBodyUnion$inboundSchema: z.ZodMiniType<
  LikeListOrReactToItResponseBodyUnion,
  unknown
> = smartUnion([
  z.lazy(() => LikeListOrReactToItResponseBody1$inboundSchema),
  z.lazy(() => LikeListOrReactToItResponseBody2$inboundSchema),
]);

export function likeListOrReactToItResponseBodyUnionFromJSON(
  jsonString: string,
): SafeParseResult<LikeListOrReactToItResponseBodyUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LikeListOrReactToItResponseBodyUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LikeListOrReactToItResponseBodyUnion' from JSON`,
  );
}

/** @internal */
export const LikeListOrReactToItResponseResult$inboundSchema: z.ZodMiniType<
  LikeListOrReactToItResponseResult,
  unknown
> = smartUnion([
  smartUnion([
    z.lazy(() => LikeListOrReactToItResponseBody1$inboundSchema),
    z.lazy(() => LikeListOrReactToItResponseBody2$inboundSchema),
  ]),
  z.lazy(() => LikeListOrReactToItResponseBody$inboundSchema),
]);

export function likeListOrReactToItResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<LikeListOrReactToItResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LikeListOrReactToItResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LikeListOrReactToItResponseResult' from JSON`,
  );
}

/** @internal */
export const LikeListOrReactToItResponse$inboundSchema: z.ZodMiniType<
  LikeListOrReactToItResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: smartUnion([
      smartUnion([
        z.lazy(() => LikeListOrReactToItResponseBody1$inboundSchema),
        z.lazy(() => LikeListOrReactToItResponseBody2$inboundSchema),
      ]),
      z.lazy(() => LikeListOrReactToItResponseBody$inboundSchema),
    ]),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function likeListOrReactToItResponseFromJSON(
  jsonString: string,
): SafeParseResult<LikeListOrReactToItResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LikeListOrReactToItResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LikeListOrReactToItResponse' from JSON`,
  );
}
