/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListAllStoryArcsWithOptionalSearchRequest = {
  /**
   * Search by story arc name.
   */
  q?: string | undefined;
  /**
   * Filter by status.
   */
  status?: string | undefined;
  /**
   * Filter by type.
   */
  type?: string | undefined;
  /**
   * Number of results per page (max 50).
   */
  limit?: number | undefined;
};

export type ListAllStoryArcsWithOptionalSearchImages = {
  coverSm?: string | undefined;
  coverMd?: string | undefined;
  coverLg?: string | undefined;
};

export type ListAllStoryArcsWithOptionalSearchPrimaryUniverse = {
  id?: number | undefined;
  name?: string | undefined;
};

export type ListAllStoryArcsWithOptionalSearchData = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  type?: string | undefined;
  status?: string | undefined;
  imageUrl?: string | undefined;
  images?: ListAllStoryArcsWithOptionalSearchImages | undefined;
  issuesCount?: number | undefined;
  primaryUniverse?:
    | ListAllStoryArcsWithOptionalSearchPrimaryUniverse
    | undefined;
};

export type ListAllStoryArcsWithOptionalSearchMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type ListAllStoryArcsWithOptionalSearchResponseBody = {
  data?: Array<ListAllStoryArcsWithOptionalSearchData> | undefined;
  meta?: ListAllStoryArcsWithOptionalSearchMeta | undefined;
};

export type ListAllStoryArcsWithOptionalSearchResponse = {
  headers: { [k: string]: Array<string> };
  result: ListAllStoryArcsWithOptionalSearchResponseBody;
};

/** @internal */
export type ListAllStoryArcsWithOptionalSearchRequest$Outbound = {
  q?: string | undefined;
  status?: string | undefined;
  type?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const ListAllStoryArcsWithOptionalSearchRequest$outboundSchema:
  z.ZodMiniType<
    ListAllStoryArcsWithOptionalSearchRequest$Outbound,
    ListAllStoryArcsWithOptionalSearchRequest
  > = z.object({
    q: z.optional(z.string()),
    status: z.optional(z.string()),
    type: z.optional(z.string()),
    limit: z.optional(z.int()),
  });

export function listAllStoryArcsWithOptionalSearchRequestToJSON(
  listAllStoryArcsWithOptionalSearchRequest:
    ListAllStoryArcsWithOptionalSearchRequest,
): string {
  return JSON.stringify(
    ListAllStoryArcsWithOptionalSearchRequest$outboundSchema.parse(
      listAllStoryArcsWithOptionalSearchRequest,
    ),
  );
}

/** @internal */
export const ListAllStoryArcsWithOptionalSearchImages$inboundSchema:
  z.ZodMiniType<ListAllStoryArcsWithOptionalSearchImages, unknown> = z.pipe(
    z.object({
      cover_sm: types.optional(types.string()),
      cover_md: types.optional(types.string()),
      cover_lg: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "cover_sm": "coverSm",
        "cover_md": "coverMd",
        "cover_lg": "coverLg",
      });
    }),
  );

export function listAllStoryArcsWithOptionalSearchImagesFromJSON(
  jsonString: string,
): SafeParseResult<
  ListAllStoryArcsWithOptionalSearchImages,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllStoryArcsWithOptionalSearchImages$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListAllStoryArcsWithOptionalSearchImages' from JSON`,
  );
}

/** @internal */
export const ListAllStoryArcsWithOptionalSearchPrimaryUniverse$inboundSchema:
  z.ZodMiniType<ListAllStoryArcsWithOptionalSearchPrimaryUniverse, unknown> = z
    .object({
      id: types.optional(types.number()),
      name: types.optional(types.string()),
    });

export function listAllStoryArcsWithOptionalSearchPrimaryUniverseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListAllStoryArcsWithOptionalSearchPrimaryUniverse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllStoryArcsWithOptionalSearchPrimaryUniverse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListAllStoryArcsWithOptionalSearchPrimaryUniverse' from JSON`,
  );
}

/** @internal */
export const ListAllStoryArcsWithOptionalSearchData$inboundSchema:
  z.ZodMiniType<ListAllStoryArcsWithOptionalSearchData, unknown> = z.pipe(
    z.object({
      id: types.optional(types.number()),
      name: types.optional(types.string()),
      slug: types.optional(types.string()),
      type: types.optional(types.string()),
      status: types.optional(types.string()),
      image_url: types.optional(types.string()),
      images: types.optional(z.lazy(() =>
        ListAllStoryArcsWithOptionalSearchImages$inboundSchema
      )),
      issues_count: types.optional(types.number()),
      primary_universe: types.optional(z.lazy(() =>
        ListAllStoryArcsWithOptionalSearchPrimaryUniverse$inboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        "image_url": "imageUrl",
        "issues_count": "issuesCount",
        "primary_universe": "primaryUniverse",
      });
    }),
  );

export function listAllStoryArcsWithOptionalSearchDataFromJSON(
  jsonString: string,
): SafeParseResult<ListAllStoryArcsWithOptionalSearchData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllStoryArcsWithOptionalSearchData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAllStoryArcsWithOptionalSearchData' from JSON`,
  );
}

/** @internal */
export const ListAllStoryArcsWithOptionalSearchMeta$inboundSchema:
  z.ZodMiniType<ListAllStoryArcsWithOptionalSearchMeta, unknown> = z.pipe(
    z.object({
      current_page: types.optional(types.number()),
      last_page: types.optional(types.number()),
      per_page: types.optional(types.number()),
      total: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "current_page": "currentPage",
        "last_page": "lastPage",
        "per_page": "perPage",
      });
    }),
  );

export function listAllStoryArcsWithOptionalSearchMetaFromJSON(
  jsonString: string,
): SafeParseResult<ListAllStoryArcsWithOptionalSearchMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllStoryArcsWithOptionalSearchMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAllStoryArcsWithOptionalSearchMeta' from JSON`,
  );
}

/** @internal */
export const ListAllStoryArcsWithOptionalSearchResponseBody$inboundSchema:
  z.ZodMiniType<ListAllStoryArcsWithOptionalSearchResponseBody, unknown> = z
    .object({
      data: types.optional(
        z.array(z.lazy(() =>
          ListAllStoryArcsWithOptionalSearchData$inboundSchema
        )),
      ),
      meta: types.optional(
        z.lazy(() => ListAllStoryArcsWithOptionalSearchMeta$inboundSchema),
      ),
    });

export function listAllStoryArcsWithOptionalSearchResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  ListAllStoryArcsWithOptionalSearchResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllStoryArcsWithOptionalSearchResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListAllStoryArcsWithOptionalSearchResponseBody' from JSON`,
  );
}

/** @internal */
export const ListAllStoryArcsWithOptionalSearchResponse$inboundSchema:
  z.ZodMiniType<ListAllStoryArcsWithOptionalSearchResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        ListAllStoryArcsWithOptionalSearchResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function listAllStoryArcsWithOptionalSearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListAllStoryArcsWithOptionalSearchResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllStoryArcsWithOptionalSearchResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListAllStoryArcsWithOptionalSearchResponse' from JSON`,
  );
}
