/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListSeriesRequest = {
  /**
   * Search by series name.
   */
  q?: string | undefined;
  /**
   * Filter by title ID.
   */
  titleId?: number | undefined;
  /**
   * Filter by publisher ID.
   */
  publisherId?: number | undefined;
  /**
   * Filter by series status (Ongoing, Completed, Canceled).
   */
  status?: string | undefined;
  /**
   * Comma-separated genre IDs. Returns a series carrying any one of them.
   */
  genreIds?: string | undefined;
  /**
   * Comma-separated publisher IDs. Returns a series published by any one of them; use this instead of publisher_id to pass more than one.
   */
  publisherIds?: string | undefined;
  /**
   * Comma-separated creator IDs. Returns a series credited to any one of them.
   */
  creatorIds?: string | undefined;
  /**
   * Comma-separated character IDs. Returns a series any one of them appears in.
   */
  characterIds?: string | undefined;
  /**
   * Comma-separated ISO 639-1 language codes. Returns a series published in any one of them.
   */
  languages?: string | undefined;
  /**
   * Filter by medium (comic, manga, manhwa, manhua, bande_dessinee, magazine).
   */
  medium?: string | undefined;
  /**
   * Filter by publication type (regular_series, limited_series, one_shot, graphic_novel, graphic_novel_series, collected_edition, special).
   */
  publicationType?: string | undefined;
  /**
   * Filter by physical format (Standard, Deluxe, Omnibus, TPB, Hardcover, Other).
   */
  format?: string | undefined;
  /**
   * Filter by the year the series began.
   */
  startYear?: number | undefined;
  /**
   * Filter by the year the series ended.
   */
  endYear?: number | undefined;
  /**
   * Filter by the decade the series began, written as a four-digit year ending in s. Accepts 1900s through the current decade.
   */
  decade?: string | undefined;
  /**
   * Return only series whose start year has already arrived.
   */
  hideUnreleased?: boolean | undefined;
  /**
   * Sort field (name, start_year, average_rating, latest_release_date, cached_issues_count).
   */
  sort?: string | undefined;
  /**
   * Sort direction (asc, desc).
   */
  direction?: string | undefined;
  /**
   * Number of results per page (max 50).
   */
  limit?: number | undefined;
};

export type ListSeriesData = {
  id?: number | undefined;
  titleId?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  number?: number | undefined;
  startYear?: number | undefined;
  endYear?: number | undefined;
  coverUrl?: string | undefined;
  publicationType?: string | undefined;
  format?: string | undefined;
  status?: string | undefined;
  originalLanguage?: string | undefined;
  cachedIssuesCount?: number | undefined;
  averageRating?: number | undefined;
  totalReviews?: number | undefined;
  issuesAverageRating?: number | undefined;
  issuesRatedCount?: number | undefined;
  contentRatingLabel?: string | undefined;
  minAge?: number | undefined;
  isNsfw?: boolean | undefined;
};

export type ListSeriesMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type ListSeriesResponseBody = {
  data?: Array<ListSeriesData> | undefined;
  meta?: ListSeriesMeta | undefined;
};

export type ListSeriesResponse = {
  headers: { [k: string]: Array<string> };
  result: ListSeriesResponseBody;
};

/** @internal */
export type ListSeriesRequest$Outbound = {
  q?: string | undefined;
  title_id?: number | undefined;
  publisher_id?: number | undefined;
  status?: string | undefined;
  genre_ids?: string | undefined;
  publisher_ids?: string | undefined;
  creator_ids?: string | undefined;
  character_ids?: string | undefined;
  languages?: string | undefined;
  medium?: string | undefined;
  publication_type?: string | undefined;
  format?: string | undefined;
  start_year?: number | undefined;
  end_year?: number | undefined;
  decade?: string | undefined;
  hide_unreleased?: boolean | undefined;
  sort?: string | undefined;
  direction?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const ListSeriesRequest$outboundSchema: z.ZodMiniType<
  ListSeriesRequest$Outbound,
  ListSeriesRequest
> = z.pipe(
  z.object({
    q: z.optional(z.string()),
    titleId: z.optional(z.int()),
    publisherId: z.optional(z.int()),
    status: z.optional(z.string()),
    genreIds: z.optional(z.string()),
    publisherIds: z.optional(z.string()),
    creatorIds: z.optional(z.string()),
    characterIds: z.optional(z.string()),
    languages: z.optional(z.string()),
    medium: z.optional(z.string()),
    publicationType: z.optional(z.string()),
    format: z.optional(z.string()),
    startYear: z.optional(z.int()),
    endYear: z.optional(z.int()),
    decade: z.optional(z.string()),
    hideUnreleased: z.optional(z.boolean()),
    sort: z.optional(z.string()),
    direction: z.optional(z.string()),
    limit: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      titleId: "title_id",
      publisherId: "publisher_id",
      genreIds: "genre_ids",
      publisherIds: "publisher_ids",
      creatorIds: "creator_ids",
      characterIds: "character_ids",
      publicationType: "publication_type",
      startYear: "start_year",
      endYear: "end_year",
      hideUnreleased: "hide_unreleased",
    });
  }),
);

export function listSeriesRequestToJSON(
  listSeriesRequest: ListSeriesRequest,
): string {
  return JSON.stringify(
    ListSeriesRequest$outboundSchema.parse(listSeriesRequest),
  );
}

/** @internal */
export const ListSeriesData$inboundSchema: z.ZodMiniType<
  ListSeriesData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    title_id: types.optional(types.number()),
    name: types.optional(types.string()),
    slug: types.optional(types.string()),
    number: types.optional(types.number()),
    start_year: types.optional(types.number()),
    end_year: types.optional(types.number()),
    cover_url: types.optional(types.string()),
    publication_type: types.optional(types.string()),
    format: types.optional(types.string()),
    status: types.optional(types.string()),
    original_language: types.optional(types.string()),
    cached_issues_count: types.optional(types.number()),
    average_rating: types.optional(types.number()),
    total_reviews: types.optional(types.number()),
    issues_average_rating: types.optional(types.number()),
    issues_rated_count: types.optional(types.number()),
    content_rating_label: types.optional(types.string()),
    min_age: types.optional(types.number()),
    is_nsfw: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "title_id": "titleId",
      "start_year": "startYear",
      "end_year": "endYear",
      "cover_url": "coverUrl",
      "publication_type": "publicationType",
      "original_language": "originalLanguage",
      "cached_issues_count": "cachedIssuesCount",
      "average_rating": "averageRating",
      "total_reviews": "totalReviews",
      "issues_average_rating": "issuesAverageRating",
      "issues_rated_count": "issuesRatedCount",
      "content_rating_label": "contentRatingLabel",
      "min_age": "minAge",
      "is_nsfw": "isNsfw",
    });
  }),
);

export function listSeriesDataFromJSON(
  jsonString: string,
): SafeParseResult<ListSeriesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSeriesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSeriesData' from JSON`,
  );
}

/** @internal */
export const ListSeriesMeta$inboundSchema: z.ZodMiniType<
  ListSeriesMeta,
  unknown
> = z.pipe(
  z.object({
    current_page: types.optional(types.number()),
    last_page: types.optional(types.number()),
    per_page: types.optional(types.number()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_page": "currentPage",
      "last_page": "lastPage",
      "per_page": "perPage",
    });
  }),
);

export function listSeriesMetaFromJSON(
  jsonString: string,
): SafeParseResult<ListSeriesMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSeriesMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSeriesMeta' from JSON`,
  );
}

/** @internal */
export const ListSeriesResponseBody$inboundSchema: z.ZodMiniType<
  ListSeriesResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(z.lazy(() => ListSeriesData$inboundSchema))),
  meta: types.optional(z.lazy(() => ListSeriesMeta$inboundSchema)),
});

export function listSeriesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListSeriesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSeriesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSeriesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListSeriesResponse$inboundSchema: z.ZodMiniType<
  ListSeriesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => ListSeriesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listSeriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSeriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSeriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSeriesResponse' from JSON`,
  );
}
