/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListPullListRequest = {
  /**
   * Items per page (max 100).
   */
  perPage?: number | undefined;
};

export type ListPullListPublisher = {
  id?: number | undefined;
  name?: string | undefined;
};

export type ListPullListSeries = {
  id?: number | undefined;
  name?: string | undefined;
  publisher?: ListPullListPublisher | undefined;
  coverUrl?: string | undefined;
};

export type ListPullListData = {
  id?: number | undefined;
  series?: ListPullListSeries | undefined;
  addedAt?: string | undefined;
};

export type ListPullListMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type ListPullListResponseBody = {
  data?: Array<ListPullListData> | undefined;
  meta?: ListPullListMeta | undefined;
};

export type ListPullListResponse = {
  headers: { [k: string]: Array<string> };
  result: ListPullListResponseBody;
};

/** @internal */
export type ListPullListRequest$Outbound = {
  per_page?: number | undefined;
};

/** @internal */
export const ListPullListRequest$outboundSchema: z.ZodMiniType<
  ListPullListRequest$Outbound,
  ListPullListRequest
> = z.pipe(
  z.object({
    perPage: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      perPage: "per_page",
    });
  }),
);

export function listPullListRequestToJSON(
  listPullListRequest: ListPullListRequest,
): string {
  return JSON.stringify(
    ListPullListRequest$outboundSchema.parse(listPullListRequest),
  );
}

/** @internal */
export const ListPullListPublisher$inboundSchema: z.ZodMiniType<
  ListPullListPublisher,
  unknown
> = z.object({
  id: types.optional(types.number()),
  name: types.optional(types.string()),
});

export function listPullListPublisherFromJSON(
  jsonString: string,
): SafeParseResult<ListPullListPublisher, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPullListPublisher$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPullListPublisher' from JSON`,
  );
}

/** @internal */
export const ListPullListSeries$inboundSchema: z.ZodMiniType<
  ListPullListSeries,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    publisher: types.optional(
      z.lazy(() => ListPullListPublisher$inboundSchema),
    ),
    cover_url: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "cover_url": "coverUrl",
    });
  }),
);

export function listPullListSeriesFromJSON(
  jsonString: string,
): SafeParseResult<ListPullListSeries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPullListSeries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPullListSeries' from JSON`,
  );
}

/** @internal */
export const ListPullListData$inboundSchema: z.ZodMiniType<
  ListPullListData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    series: types.optional(z.lazy(() => ListPullListSeries$inboundSchema)),
    added_at: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "added_at": "addedAt",
    });
  }),
);

export function listPullListDataFromJSON(
  jsonString: string,
): SafeParseResult<ListPullListData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPullListData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPullListData' from JSON`,
  );
}

/** @internal */
export const ListPullListMeta$inboundSchema: z.ZodMiniType<
  ListPullListMeta,
  unknown
> = z.pipe(
  z.object({
    current_page: types.optional(types.number()),
    last_page: types.optional(types.number()),
    per_page: types.optional(types.number()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_page": "currentPage",
      "last_page": "lastPage",
      "per_page": "perPage",
    });
  }),
);

export function listPullListMetaFromJSON(
  jsonString: string,
): SafeParseResult<ListPullListMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPullListMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPullListMeta' from JSON`,
  );
}

/** @internal */
export const ListPullListResponseBody$inboundSchema: z.ZodMiniType<
  ListPullListResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(z.lazy(() => ListPullListData$inboundSchema))),
  meta: types.optional(z.lazy(() => ListPullListMeta$inboundSchema)),
});

export function listPullListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListPullListResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPullListResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPullListResponseBody' from JSON`,
  );
}

/** @internal */
export const ListPullListResponse$inboundSchema: z.ZodMiniType<
  ListPullListResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => ListPullListResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listPullListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPullListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPullListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPullListResponse' from JSON`,
  );
}
