/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListKeyIssueReasonsRequest = {
  /**
   * Filter by category (appearance, story, creator, market, media).
   */
  category?: string | undefined;
};

export type ListKeyIssueReasonsData = {
  id?: number | undefined;
  name?: string | undefined;
  category?: string | undefined;
  description?: string | undefined;
};

/**
 * Success
 */
export type ListKeyIssueReasonsResponseBody = {
  data?: Array<ListKeyIssueReasonsData> | undefined;
};

export type ListKeyIssueReasonsResponse = {
  headers: { [k: string]: Array<string> };
  result: ListKeyIssueReasonsResponseBody;
};

/** @internal */
export type ListKeyIssueReasonsRequest$Outbound = {
  category?: string | undefined;
};

/** @internal */
export const ListKeyIssueReasonsRequest$outboundSchema: z.ZodMiniType<
  ListKeyIssueReasonsRequest$Outbound,
  ListKeyIssueReasonsRequest
> = z.object({
  category: z.optional(z.string()),
});

export function listKeyIssueReasonsRequestToJSON(
  listKeyIssueReasonsRequest: ListKeyIssueReasonsRequest,
): string {
  return JSON.stringify(
    ListKeyIssueReasonsRequest$outboundSchema.parse(listKeyIssueReasonsRequest),
  );
}

/** @internal */
export const ListKeyIssueReasonsData$inboundSchema: z.ZodMiniType<
  ListKeyIssueReasonsData,
  unknown
> = z.object({
  id: types.optional(types.number()),
  name: types.optional(types.string()),
  category: types.optional(types.string()),
  description: types.optional(types.string()),
});

export function listKeyIssueReasonsDataFromJSON(
  jsonString: string,
): SafeParseResult<ListKeyIssueReasonsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListKeyIssueReasonsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListKeyIssueReasonsData' from JSON`,
  );
}

/** @internal */
export const ListKeyIssueReasonsResponseBody$inboundSchema: z.ZodMiniType<
  ListKeyIssueReasonsResponseBody,
  unknown
> = z.object({
  data: types.optional(
    z.array(z.lazy(() => ListKeyIssueReasonsData$inboundSchema)),
  ),
});

export function listKeyIssueReasonsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListKeyIssueReasonsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListKeyIssueReasonsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListKeyIssueReasonsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListKeyIssueReasonsResponse$inboundSchema: z.ZodMiniType<
  ListKeyIssueReasonsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => ListKeyIssueReasonsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listKeyIssueReasonsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListKeyIssueReasonsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListKeyIssueReasonsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListKeyIssueReasonsResponse' from JSON`,
  );
}
