/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListSeriesRequest = {
  /**
   * Search by series name.
   */
  q?: string | undefined;
  /**
   * Filter by title ID.
   */
  titleId?: number | undefined;
  /**
   * Sort field (name, start_year, created_at, updated_at, average_rating).
   */
  sort?: string | undefined;
  /**
   * Sort direction (asc, desc).
   */
  direction?: string | undefined;
  /**
   * Number of results per page (max 50).
   */
  limit?: number | undefined;
};

export type ListSeriesData = {
  id?: number | undefined;
  titleId?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  number?: number | undefined;
  startYear?: number | undefined;
  endYear?: number | undefined;
  coverUrl?: string | undefined;
  publicationType?: string | undefined;
  format?: string | undefined;
  status?: string | undefined;
  originalLanguage?: string | undefined;
  cachedIssuesCount?: number | undefined;
  averageRating?: number | undefined;
  totalReviews?: number | undefined;
  ageRating?: string | undefined;
  isNsfw?: boolean | undefined;
};

export type ListSeriesMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type ListSeriesResponseBody = {
  data?: Array<ListSeriesData> | undefined;
  meta?: ListSeriesMeta | undefined;
};

export type ListSeriesResponse = {
  headers: { [k: string]: Array<string> };
  result: ListSeriesResponseBody;
};

/** @internal */
export type ListSeriesRequest$Outbound = {
  q?: string | undefined;
  title_id?: number | undefined;
  sort?: string | undefined;
  direction?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const ListSeriesRequest$outboundSchema: z.ZodMiniType<
  ListSeriesRequest$Outbound,
  ListSeriesRequest
> = z.pipe(
  z.object({
    q: z.optional(z.string()),
    titleId: z.optional(z.int()),
    sort: z.optional(z.string()),
    direction: z.optional(z.string()),
    limit: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      titleId: "title_id",
    });
  }),
);

export function listSeriesRequestToJSON(
  listSeriesRequest: ListSeriesRequest,
): string {
  return JSON.stringify(
    ListSeriesRequest$outboundSchema.parse(listSeriesRequest),
  );
}

/** @internal */
export const ListSeriesData$inboundSchema: z.ZodMiniType<
  ListSeriesData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    title_id: types.optional(types.number()),
    name: types.optional(types.string()),
    slug: types.optional(types.string()),
    number: types.optional(types.number()),
    start_year: types.optional(types.number()),
    end_year: types.optional(types.number()),
    cover_url: types.optional(types.string()),
    publication_type: types.optional(types.string()),
    format: types.optional(types.string()),
    status: types.optional(types.string()),
    original_language: types.optional(types.string()),
    cached_issues_count: types.optional(types.number()),
    average_rating: types.optional(types.number()),
    total_reviews: types.optional(types.number()),
    age_rating: types.optional(types.string()),
    is_nsfw: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "title_id": "titleId",
      "start_year": "startYear",
      "end_year": "endYear",
      "cover_url": "coverUrl",
      "publication_type": "publicationType",
      "original_language": "originalLanguage",
      "cached_issues_count": "cachedIssuesCount",
      "average_rating": "averageRating",
      "total_reviews": "totalReviews",
      "age_rating": "ageRating",
      "is_nsfw": "isNsfw",
    });
  }),
);

export function listSeriesDataFromJSON(
  jsonString: string,
): SafeParseResult<ListSeriesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSeriesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSeriesData' from JSON`,
  );
}

/** @internal */
export const ListSeriesMeta$inboundSchema: z.ZodMiniType<
  ListSeriesMeta,
  unknown
> = z.pipe(
  z.object({
    current_page: types.optional(types.number()),
    last_page: types.optional(types.number()),
    per_page: types.optional(types.number()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_page": "currentPage",
      "last_page": "lastPage",
      "per_page": "perPage",
    });
  }),
);

export function listSeriesMetaFromJSON(
  jsonString: string,
): SafeParseResult<ListSeriesMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSeriesMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSeriesMeta' from JSON`,
  );
}

/** @internal */
export const ListSeriesResponseBody$inboundSchema: z.ZodMiniType<
  ListSeriesResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(z.lazy(() => ListSeriesData$inboundSchema))),
  meta: types.optional(z.lazy(() => ListSeriesMeta$inboundSchema)),
});

export function listSeriesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListSeriesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSeriesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSeriesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListSeriesResponse$inboundSchema: z.ZodMiniType<
  ListSeriesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => ListSeriesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listSeriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSeriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSeriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSeriesResponse' from JSON`,
  );
}
