/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListWishlistRequest = {
  /**
   * Items per page (max 100).
   */
  perPage?: number | undefined;
};

export type ListWishlistSeries = {
  id?: number | undefined;
  name?: string | undefined;
  startYear?: number | undefined;
};

export type ListWishlistEntity = {
  id?: number | undefined;
  name?: string | undefined;
  issueNumber?: string | undefined;
  imageUrl?: string | undefined;
  publisher?: string | undefined;
  series?: ListWishlistSeries | undefined;
};

export type ListWishlistData = {
  id?: number | undefined;
  position?: string | null | undefined;
  note?: string | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  variantId?: string | null | undefined;
  entityType?: string | undefined;
  entity?: ListWishlistEntity | undefined;
};

export type ListWishlistMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type ListWishlistResponseBody = {
  data?: Array<ListWishlistData> | undefined;
  meta?: ListWishlistMeta | undefined;
};

export type ListWishlistResponse = {
  headers: { [k: string]: Array<string> };
  result: ListWishlistResponseBody;
};

/** @internal */
export type ListWishlistRequest$Outbound = {
  per_page?: number | undefined;
};

/** @internal */
export const ListWishlistRequest$outboundSchema: z.ZodMiniType<
  ListWishlistRequest$Outbound,
  ListWishlistRequest
> = z.pipe(
  z.object({
    perPage: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      perPage: "per_page",
    });
  }),
);

export function listWishlistRequestToJSON(
  listWishlistRequest: ListWishlistRequest,
): string {
  return JSON.stringify(
    ListWishlistRequest$outboundSchema.parse(listWishlistRequest),
  );
}

/** @internal */
export const ListWishlistSeries$inboundSchema: z.ZodMiniType<
  ListWishlistSeries,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    start_year: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "start_year": "startYear",
    });
  }),
);

export function listWishlistSeriesFromJSON(
  jsonString: string,
): SafeParseResult<ListWishlistSeries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWishlistSeries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWishlistSeries' from JSON`,
  );
}

/** @internal */
export const ListWishlistEntity$inboundSchema: z.ZodMiniType<
  ListWishlistEntity,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    issue_number: types.optional(types.string()),
    image_url: types.optional(types.string()),
    publisher: types.optional(types.string()),
    series: types.optional(z.lazy(() => ListWishlistSeries$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "issue_number": "issueNumber",
      "image_url": "imageUrl",
    });
  }),
);

export function listWishlistEntityFromJSON(
  jsonString: string,
): SafeParseResult<ListWishlistEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWishlistEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWishlistEntity' from JSON`,
  );
}

/** @internal */
export const ListWishlistData$inboundSchema: z.ZodMiniType<
  ListWishlistData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    position: z.optional(z.nullable(types.string())),
    note: z.optional(z.nullable(types.string())),
    created_at: types.optional(types.string()),
    updated_at: types.optional(types.string()),
    variant_id: z.optional(z.nullable(types.string())),
    entity_type: types.optional(types.string()),
    entity: types.optional(z.lazy(() => ListWishlistEntity$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "variant_id": "variantId",
      "entity_type": "entityType",
    });
  }),
);

export function listWishlistDataFromJSON(
  jsonString: string,
): SafeParseResult<ListWishlistData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWishlistData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWishlistData' from JSON`,
  );
}

/** @internal */
export const ListWishlistMeta$inboundSchema: z.ZodMiniType<
  ListWishlistMeta,
  unknown
> = z.pipe(
  z.object({
    current_page: types.optional(types.number()),
    last_page: types.optional(types.number()),
    per_page: types.optional(types.number()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_page": "currentPage",
      "last_page": "lastPage",
      "per_page": "perPage",
    });
  }),
);

export function listWishlistMetaFromJSON(
  jsonString: string,
): SafeParseResult<ListWishlistMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWishlistMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWishlistMeta' from JSON`,
  );
}

/** @internal */
export const ListWishlistResponseBody$inboundSchema: z.ZodMiniType<
  ListWishlistResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(z.lazy(() => ListWishlistData$inboundSchema))),
  meta: types.optional(z.lazy(() => ListWishlistMeta$inboundSchema)),
});

export function listWishlistResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListWishlistResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWishlistResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWishlistResponseBody' from JSON`,
  );
}

/** @internal */
export const ListWishlistResponse$inboundSchema: z.ZodMiniType<
  ListWishlistResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => ListWishlistResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listWishlistResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListWishlistResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWishlistResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWishlistResponse' from JSON`,
  );
}
