/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListAllPodcastsWithOptionalSearchRequest = {
  /**
   * Search by podcast name.
   */
  q?: string | undefined;
  /**
   * Filter by type (podcast or youtube).
   */
  type?: string | undefined;
  /**
   * Filter by language code (e.g., en, ja, fr).
   */
  language?: string | undefined;
  /**
   * Number of results per page (max 50).
   */
  limit?: number | undefined;
};

export type ListAllPodcastsWithOptionalSearchLinks = {
  first?: string | undefined;
  last?: string | undefined;
  prev?: string | null | undefined;
  next?: string | null | undefined;
};

export type ListAllPodcastsWithOptionalSearchLink = {
  url?: string | null | undefined;
  label?: string | undefined;
  page?: string | null | undefined;
  active?: boolean | undefined;
};

export type ListAllPodcastsWithOptionalSearchMeta = {
  currentPage?: number | undefined;
  from?: string | null | undefined;
  lastPage?: number | undefined;
  links?: Array<ListAllPodcastsWithOptionalSearchLink> | undefined;
  path?: string | undefined;
  perPage?: number | undefined;
  to?: string | null | undefined;
  total?: number | undefined;
};

export type ListAllPodcastsWithOptionalSearchResponseBody = {
  data?: Array<any> | undefined;
  links?: ListAllPodcastsWithOptionalSearchLinks | undefined;
  meta?: ListAllPodcastsWithOptionalSearchMeta | undefined;
};

export type ListAllPodcastsWithOptionalSearchResponse = {
  headers: { [k: string]: Array<string> };
  result: ListAllPodcastsWithOptionalSearchResponseBody;
};

/** @internal */
export type ListAllPodcastsWithOptionalSearchRequest$Outbound = {
  q?: string | undefined;
  type?: string | undefined;
  language?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const ListAllPodcastsWithOptionalSearchRequest$outboundSchema:
  z.ZodMiniType<
    ListAllPodcastsWithOptionalSearchRequest$Outbound,
    ListAllPodcastsWithOptionalSearchRequest
  > = z.object({
    q: z.optional(z.string()),
    type: z.optional(z.string()),
    language: z.optional(z.string()),
    limit: z.optional(z.int()),
  });

export function listAllPodcastsWithOptionalSearchRequestToJSON(
  listAllPodcastsWithOptionalSearchRequest:
    ListAllPodcastsWithOptionalSearchRequest,
): string {
  return JSON.stringify(
    ListAllPodcastsWithOptionalSearchRequest$outboundSchema.parse(
      listAllPodcastsWithOptionalSearchRequest,
    ),
  );
}

/** @internal */
export const ListAllPodcastsWithOptionalSearchLinks$inboundSchema:
  z.ZodMiniType<ListAllPodcastsWithOptionalSearchLinks, unknown> = z.object({
    first: types.optional(types.string()),
    last: types.optional(types.string()),
    prev: z.optional(z.nullable(types.string())),
    next: z.optional(z.nullable(types.string())),
  });

export function listAllPodcastsWithOptionalSearchLinksFromJSON(
  jsonString: string,
): SafeParseResult<ListAllPodcastsWithOptionalSearchLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllPodcastsWithOptionalSearchLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAllPodcastsWithOptionalSearchLinks' from JSON`,
  );
}

/** @internal */
export const ListAllPodcastsWithOptionalSearchLink$inboundSchema: z.ZodMiniType<
  ListAllPodcastsWithOptionalSearchLink,
  unknown
> = z.object({
  url: z.optional(z.nullable(types.string())),
  label: types.optional(types.string()),
  page: z.optional(z.nullable(types.string())),
  active: types.optional(types.boolean()),
});

export function listAllPodcastsWithOptionalSearchLinkFromJSON(
  jsonString: string,
): SafeParseResult<ListAllPodcastsWithOptionalSearchLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllPodcastsWithOptionalSearchLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAllPodcastsWithOptionalSearchLink' from JSON`,
  );
}

/** @internal */
export const ListAllPodcastsWithOptionalSearchMeta$inboundSchema: z.ZodMiniType<
  ListAllPodcastsWithOptionalSearchMeta,
  unknown
> = z.pipe(
  z.object({
    current_page: types.optional(types.number()),
    from: z.optional(z.nullable(types.string())),
    last_page: types.optional(types.number()),
    links: types.optional(
      z.array(
        z.lazy(() => ListAllPodcastsWithOptionalSearchLink$inboundSchema),
      ),
    ),
    path: types.optional(types.string()),
    per_page: types.optional(types.number()),
    to: z.optional(z.nullable(types.string())),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_page": "currentPage",
      "last_page": "lastPage",
      "per_page": "perPage",
    });
  }),
);

export function listAllPodcastsWithOptionalSearchMetaFromJSON(
  jsonString: string,
): SafeParseResult<ListAllPodcastsWithOptionalSearchMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllPodcastsWithOptionalSearchMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAllPodcastsWithOptionalSearchMeta' from JSON`,
  );
}

/** @internal */
export const ListAllPodcastsWithOptionalSearchResponseBody$inboundSchema:
  z.ZodMiniType<ListAllPodcastsWithOptionalSearchResponseBody, unknown> = z
    .object({
      data: types.optional(z.array(z.any())),
      links: types.optional(
        z.lazy(() => ListAllPodcastsWithOptionalSearchLinks$inboundSchema),
      ),
      meta: types.optional(
        z.lazy(() => ListAllPodcastsWithOptionalSearchMeta$inboundSchema),
      ),
    });

export function listAllPodcastsWithOptionalSearchResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  ListAllPodcastsWithOptionalSearchResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllPodcastsWithOptionalSearchResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListAllPodcastsWithOptionalSearchResponseBody' from JSON`,
  );
}

/** @internal */
export const ListAllPodcastsWithOptionalSearchResponse$inboundSchema:
  z.ZodMiniType<ListAllPodcastsWithOptionalSearchResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        ListAllPodcastsWithOptionalSearchResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function listAllPodcastsWithOptionalSearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListAllPodcastsWithOptionalSearchResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllPodcastsWithOptionalSearchResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListAllPodcastsWithOptionalSearchResponse' from JSON`,
  );
}
