/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListTitlesRequest = {
  /**
   * Search by title name.
   */
  q?: string | undefined;
  /**
   * Filter by publisher ID.
   */
  publisher?: number | undefined;
  /**
   * Number of results per page (max 50).
   */
  limit?: number | undefined;
};

export type ListTitlesImages = {
  coverSm?: string | undefined;
  coverMd?: string | undefined;
  coverLg?: string | undefined;
};

export type ListTitlesData = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  startYear?: number | undefined;
  endYear?: string | null | undefined;
  status?: string | undefined;
  type?: string | undefined;
  imageUrl?: string | undefined;
  images?: ListTitlesImages | undefined;
  averageRating?: number | undefined;
  seriesCount?: number | undefined;
  issuesCount?: number | undefined;
  ageRating?: string | undefined;
  isNsfw?: boolean | undefined;
};

export type ListTitlesMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type ListTitlesResponseBody = {
  data?: Array<ListTitlesData> | undefined;
  meta?: ListTitlesMeta | undefined;
};

export type ListTitlesResponse = {
  headers: { [k: string]: Array<string> };
  result: ListTitlesResponseBody;
};

/** @internal */
export type ListTitlesRequest$Outbound = {
  q?: string | undefined;
  publisher?: number | undefined;
  limit?: number | undefined;
};

/** @internal */
export const ListTitlesRequest$outboundSchema: z.ZodMiniType<
  ListTitlesRequest$Outbound,
  ListTitlesRequest
> = z.object({
  q: z.optional(z.string()),
  publisher: z.optional(z.int()),
  limit: z.optional(z.int()),
});

export function listTitlesRequestToJSON(
  listTitlesRequest: ListTitlesRequest,
): string {
  return JSON.stringify(
    ListTitlesRequest$outboundSchema.parse(listTitlesRequest),
  );
}

/** @internal */
export const ListTitlesImages$inboundSchema: z.ZodMiniType<
  ListTitlesImages,
  unknown
> = z.pipe(
  z.object({
    cover_sm: types.optional(types.string()),
    cover_md: types.optional(types.string()),
    cover_lg: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "cover_sm": "coverSm",
      "cover_md": "coverMd",
      "cover_lg": "coverLg",
    });
  }),
);

export function listTitlesImagesFromJSON(
  jsonString: string,
): SafeParseResult<ListTitlesImages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTitlesImages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTitlesImages' from JSON`,
  );
}

/** @internal */
export const ListTitlesData$inboundSchema: z.ZodMiniType<
  ListTitlesData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    slug: types.optional(types.string()),
    start_year: types.optional(types.number()),
    end_year: z.optional(z.nullable(types.string())),
    status: types.optional(types.string()),
    type: types.optional(types.string()),
    image_url: types.optional(types.string()),
    images: types.optional(z.lazy(() => ListTitlesImages$inboundSchema)),
    average_rating: types.optional(types.number()),
    series_count: types.optional(types.number()),
    issues_count: types.optional(types.number()),
    age_rating: types.optional(types.string()),
    is_nsfw: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "start_year": "startYear",
      "end_year": "endYear",
      "image_url": "imageUrl",
      "average_rating": "averageRating",
      "series_count": "seriesCount",
      "issues_count": "issuesCount",
      "age_rating": "ageRating",
      "is_nsfw": "isNsfw",
    });
  }),
);

export function listTitlesDataFromJSON(
  jsonString: string,
): SafeParseResult<ListTitlesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTitlesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTitlesData' from JSON`,
  );
}

/** @internal */
export const ListTitlesMeta$inboundSchema: z.ZodMiniType<
  ListTitlesMeta,
  unknown
> = z.pipe(
  z.object({
    current_page: types.optional(types.number()),
    last_page: types.optional(types.number()),
    per_page: types.optional(types.number()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_page": "currentPage",
      "last_page": "lastPage",
      "per_page": "perPage",
    });
  }),
);

export function listTitlesMetaFromJSON(
  jsonString: string,
): SafeParseResult<ListTitlesMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTitlesMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTitlesMeta' from JSON`,
  );
}

/** @internal */
export const ListTitlesResponseBody$inboundSchema: z.ZodMiniType<
  ListTitlesResponseBody,
  unknown
> = z.object({
  data: types.optional(z.array(z.lazy(() => ListTitlesData$inboundSchema))),
  meta: types.optional(z.lazy(() => ListTitlesMeta$inboundSchema)),
});

export function listTitlesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListTitlesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTitlesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTitlesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListTitlesResponse$inboundSchema: z.ZodMiniType<
  ListTitlesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => ListTitlesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listTitlesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTitlesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTitlesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTitlesResponse' from JSON`,
  );
}
