/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListAllPublishersWithOptionalSearchRequest = {
  /**
   * Search by publisher name.
   */
  q?: string | undefined;
  /**
   * Number of results per page (max 50).
   */
  limit?: number | undefined;
};

export type ListAllPublishersWithOptionalSearchImages = {
  tileSm?: string | undefined;
  profileMd?: string | undefined;
  fullLg?: string | undefined;
};

export type ListAllPublishersWithOptionalSearchData = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  foundedYear?: number | undefined;
  headquarters?: string | undefined;
  status?: string | undefined;
  seriesCount?: number | undefined;
  logoUrl?: string | undefined;
  images?: ListAllPublishersWithOptionalSearchImages | undefined;
};

export type ListAllPublishersWithOptionalSearchMeta = {
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
};

/**
 * Success
 */
export type ListAllPublishersWithOptionalSearchResponseBody = {
  data?: Array<ListAllPublishersWithOptionalSearchData> | undefined;
  meta?: ListAllPublishersWithOptionalSearchMeta | undefined;
};

export type ListAllPublishersWithOptionalSearchResponse = {
  headers: { [k: string]: Array<string> };
  result: ListAllPublishersWithOptionalSearchResponseBody;
};

/** @internal */
export type ListAllPublishersWithOptionalSearchRequest$Outbound = {
  q?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const ListAllPublishersWithOptionalSearchRequest$outboundSchema:
  z.ZodMiniType<
    ListAllPublishersWithOptionalSearchRequest$Outbound,
    ListAllPublishersWithOptionalSearchRequest
  > = z.object({
    q: z.optional(z.string()),
    limit: z.optional(z.int()),
  });

export function listAllPublishersWithOptionalSearchRequestToJSON(
  listAllPublishersWithOptionalSearchRequest:
    ListAllPublishersWithOptionalSearchRequest,
): string {
  return JSON.stringify(
    ListAllPublishersWithOptionalSearchRequest$outboundSchema.parse(
      listAllPublishersWithOptionalSearchRequest,
    ),
  );
}

/** @internal */
export const ListAllPublishersWithOptionalSearchImages$inboundSchema:
  z.ZodMiniType<ListAllPublishersWithOptionalSearchImages, unknown> = z.pipe(
    z.object({
      tile_sm: types.optional(types.string()),
      profile_md: types.optional(types.string()),
      full_lg: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "tile_sm": "tileSm",
        "profile_md": "profileMd",
        "full_lg": "fullLg",
      });
    }),
  );

export function listAllPublishersWithOptionalSearchImagesFromJSON(
  jsonString: string,
): SafeParseResult<
  ListAllPublishersWithOptionalSearchImages,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllPublishersWithOptionalSearchImages$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListAllPublishersWithOptionalSearchImages' from JSON`,
  );
}

/** @internal */
export const ListAllPublishersWithOptionalSearchData$inboundSchema:
  z.ZodMiniType<ListAllPublishersWithOptionalSearchData, unknown> = z.pipe(
    z.object({
      id: types.optional(types.number()),
      name: types.optional(types.string()),
      slug: types.optional(types.string()),
      founded_year: types.optional(types.number()),
      headquarters: types.optional(types.string()),
      status: types.optional(types.string()),
      series_count: types.optional(types.number()),
      logo_url: types.optional(types.string()),
      images: types.optional(z.lazy(() =>
        ListAllPublishersWithOptionalSearchImages$inboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        "founded_year": "foundedYear",
        "series_count": "seriesCount",
        "logo_url": "logoUrl",
      });
    }),
  );

export function listAllPublishersWithOptionalSearchDataFromJSON(
  jsonString: string,
): SafeParseResult<
  ListAllPublishersWithOptionalSearchData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllPublishersWithOptionalSearchData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListAllPublishersWithOptionalSearchData' from JSON`,
  );
}

/** @internal */
export const ListAllPublishersWithOptionalSearchMeta$inboundSchema:
  z.ZodMiniType<ListAllPublishersWithOptionalSearchMeta, unknown> = z.pipe(
    z.object({
      current_page: types.optional(types.number()),
      last_page: types.optional(types.number()),
      per_page: types.optional(types.number()),
      total: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "current_page": "currentPage",
        "last_page": "lastPage",
        "per_page": "perPage",
      });
    }),
  );

export function listAllPublishersWithOptionalSearchMetaFromJSON(
  jsonString: string,
): SafeParseResult<
  ListAllPublishersWithOptionalSearchMeta,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllPublishersWithOptionalSearchMeta$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListAllPublishersWithOptionalSearchMeta' from JSON`,
  );
}

/** @internal */
export const ListAllPublishersWithOptionalSearchResponseBody$inboundSchema:
  z.ZodMiniType<ListAllPublishersWithOptionalSearchResponseBody, unknown> = z
    .object({
      data: types.optional(
        z.array(z.lazy(() =>
          ListAllPublishersWithOptionalSearchData$inboundSchema
        )),
      ),
      meta: types.optional(
        z.lazy(() => ListAllPublishersWithOptionalSearchMeta$inboundSchema),
      ),
    });

export function listAllPublishersWithOptionalSearchResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  ListAllPublishersWithOptionalSearchResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllPublishersWithOptionalSearchResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListAllPublishersWithOptionalSearchResponseBody' from JSON`,
  );
}

/** @internal */
export const ListAllPublishersWithOptionalSearchResponse$inboundSchema:
  z.ZodMiniType<ListAllPublishersWithOptionalSearchResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        ListAllPublishersWithOptionalSearchResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function listAllPublishersWithOptionalSearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListAllPublishersWithOptionalSearchResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListAllPublishersWithOptionalSearchResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListAllPublishersWithOptionalSearchResponse' from JSON`,
  );
}
