/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type LookupByUPCRequest = {
  /**
   * The UPC barcode.
   */
  upc: string;
};

export type MatchVariant = {
  variantId?: string | null | undefined;
  variantName?: string | undefined;
  coverUrl?: string | undefined;
};

export type Match = {
  issueId?: number | undefined;
  seriesName?: string | undefined;
  seriesId?: number | undefined;
  issueNumber?: string | undefined;
  coverUrl?: string | undefined;
  variantName?: string | null | undefined;
  suggestedVariantId?: string | null | undefined;
  variants?: Array<MatchVariant> | undefined;
  publisherName?: string | undefined;
  releaseDate?: string | undefined;
  startYear?: number | undefined;
};

export type LookupByUPCSeries = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  startYear?: number | undefined;
  volumeNumber?: number | undefined;
};

export type LookupByUPCPublisher = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
};

export type LookupByUPCData = {
  id?: number | undefined;
  slug?: string | undefined;
  seriesId?: number | undefined;
  titleId?: number | undefined;
  issueNumber?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  releaseDate?: string | undefined;
  coverDate?: string | undefined;
  coverUrl?: string | undefined;
  upc?: string | undefined;
  series?: LookupByUPCSeries | undefined;
  publisher?: LookupByUPCPublisher | undefined;
};

export type LookupByUPCVariant = {
  variantId?: string | null | undefined;
  variantName?: string | undefined;
  coverUrl?: string | undefined;
};

/**
 * Success
 */
export type LookupByUPCResponseBody = {
  data?: LookupByUPCData | undefined;
  suggestedVariantId?: number | undefined;
  variants?: Array<LookupByUPCVariant> | undefined;
};

export type LookupByUPCResponse = {
  headers: { [k: string]: Array<string> };
  result: LookupByUPCResponseBody;
};

/** @internal */
export type LookupByUPCRequest$Outbound = {
  upc: string;
};

/** @internal */
export const LookupByUPCRequest$outboundSchema: z.ZodMiniType<
  LookupByUPCRequest$Outbound,
  LookupByUPCRequest
> = z.object({
  upc: z.string(),
});

export function lookupByUPCRequestToJSON(
  lookupByUPCRequest: LookupByUPCRequest,
): string {
  return JSON.stringify(
    LookupByUPCRequest$outboundSchema.parse(lookupByUPCRequest),
  );
}

/** @internal */
export const MatchVariant$inboundSchema: z.ZodMiniType<MatchVariant, unknown> =
  z.pipe(
    z.object({
      variant_id: z.optional(z.nullable(types.string())),
      variant_name: types.optional(types.string()),
      cover_url: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "variant_id": "variantId",
        "variant_name": "variantName",
        "cover_url": "coverUrl",
      });
    }),
  );

export function matchVariantFromJSON(
  jsonString: string,
): SafeParseResult<MatchVariant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MatchVariant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MatchVariant' from JSON`,
  );
}

/** @internal */
export const Match$inboundSchema: z.ZodMiniType<Match, unknown> = z.pipe(
  z.object({
    issue_id: types.optional(types.number()),
    series_name: types.optional(types.string()),
    series_id: types.optional(types.number()),
    issue_number: types.optional(types.string()),
    cover_url: types.optional(types.string()),
    variant_name: z.optional(z.nullable(types.string())),
    suggested_variant_id: z.optional(z.nullable(types.string())),
    variants: types.optional(z.array(z.lazy(() => MatchVariant$inboundSchema))),
    publisher_name: types.optional(types.string()),
    release_date: types.optional(types.string()),
    start_year: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "issue_id": "issueId",
      "series_name": "seriesName",
      "series_id": "seriesId",
      "issue_number": "issueNumber",
      "cover_url": "coverUrl",
      "variant_name": "variantName",
      "suggested_variant_id": "suggestedVariantId",
      "publisher_name": "publisherName",
      "release_date": "releaseDate",
      "start_year": "startYear",
    });
  }),
);

export function matchFromJSON(
  jsonString: string,
): SafeParseResult<Match, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Match$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Match' from JSON`,
  );
}

/** @internal */
export const LookupByUPCSeries$inboundSchema: z.ZodMiniType<
  LookupByUPCSeries,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    slug: types.optional(types.string()),
    start_year: types.optional(types.number()),
    volume_number: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "start_year": "startYear",
      "volume_number": "volumeNumber",
    });
  }),
);

export function lookupByUPCSeriesFromJSON(
  jsonString: string,
): SafeParseResult<LookupByUPCSeries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByUPCSeries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByUPCSeries' from JSON`,
  );
}

/** @internal */
export const LookupByUPCPublisher$inboundSchema: z.ZodMiniType<
  LookupByUPCPublisher,
  unknown
> = z.object({
  id: types.optional(types.number()),
  name: types.optional(types.string()),
  slug: types.optional(types.string()),
});

export function lookupByUPCPublisherFromJSON(
  jsonString: string,
): SafeParseResult<LookupByUPCPublisher, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByUPCPublisher$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByUPCPublisher' from JSON`,
  );
}

/** @internal */
export const LookupByUPCData$inboundSchema: z.ZodMiniType<
  LookupByUPCData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    slug: types.optional(types.string()),
    series_id: types.optional(types.number()),
    title_id: types.optional(types.number()),
    issue_number: types.optional(types.string()),
    name: types.optional(types.string()),
    description: types.optional(types.string()),
    release_date: types.optional(types.string()),
    cover_date: types.optional(types.string()),
    cover_url: types.optional(types.string()),
    upc: types.optional(types.string()),
    series: types.optional(z.lazy(() => LookupByUPCSeries$inboundSchema)),
    publisher: types.optional(z.lazy(() => LookupByUPCPublisher$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "series_id": "seriesId",
      "title_id": "titleId",
      "issue_number": "issueNumber",
      "release_date": "releaseDate",
      "cover_date": "coverDate",
      "cover_url": "coverUrl",
    });
  }),
);

export function lookupByUPCDataFromJSON(
  jsonString: string,
): SafeParseResult<LookupByUPCData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByUPCData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByUPCData' from JSON`,
  );
}

/** @internal */
export const LookupByUPCVariant$inboundSchema: z.ZodMiniType<
  LookupByUPCVariant,
  unknown
> = z.pipe(
  z.object({
    variant_id: z.optional(z.nullable(types.string())),
    variant_name: types.optional(types.string()),
    cover_url: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "variant_id": "variantId",
      "variant_name": "variantName",
      "cover_url": "coverUrl",
    });
  }),
);

export function lookupByUPCVariantFromJSON(
  jsonString: string,
): SafeParseResult<LookupByUPCVariant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByUPCVariant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByUPCVariant' from JSON`,
  );
}

/** @internal */
export const LookupByUPCResponseBody$inboundSchema: z.ZodMiniType<
  LookupByUPCResponseBody,
  unknown
> = z.pipe(
  z.object({
    data: types.optional(z.lazy(() => LookupByUPCData$inboundSchema)),
    suggested_variant_id: types.optional(types.number()),
    variants: types.optional(
      z.array(z.lazy(() => LookupByUPCVariant$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "suggested_variant_id": "suggestedVariantId",
    });
  }),
);

export function lookupByUPCResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<LookupByUPCResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByUPCResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByUPCResponseBody' from JSON`,
  );
}

/** @internal */
export const LookupByUPCResponse$inboundSchema: z.ZodMiniType<
  LookupByUPCResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => LookupByUPCResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function lookupByUPCResponseFromJSON(
  jsonString: string,
): SafeParseResult<LookupByUPCResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByUPCResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByUPCResponse' from JSON`,
  );
}
