/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type LookupByDistributorCodeRequest = {
  /**
   * A Lunar or Universal code.
   */
  code: string;
};

export type LookupByDistributorCodeMatchVariant = {
  variantId?: string | null | undefined;
  variantName?: string | undefined;
  coverUrl?: string | undefined;
  upc?: string | undefined;
  lunarCode?: string | undefined;
  universalCode?: string | null | undefined;
  diamondCode?: string | null | undefined;
};

export type LookupByDistributorCodeMatch = {
  issueId?: number | undefined;
  seriesName?: string | undefined;
  seriesId?: number | undefined;
  issueNumber?: string | undefined;
  coverUrl?: string | undefined;
  variantName?: string | null | undefined;
  suggestedVariantId?: string | null | undefined;
  variants?: Array<LookupByDistributorCodeMatchVariant> | undefined;
  publisherName?: string | undefined;
  releaseDate?: string | undefined;
  startYear?: number | undefined;
};

export type LookupByDistributorCodeSeries = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  startYear?: number | undefined;
  volumeNumber?: number | undefined;
};

export type LookupByDistributorCodePublisher = {
  id?: number | undefined;
  name?: string | undefined;
  slug?: string | undefined;
};

export type LookupByDistributorCodeData = {
  id?: number | undefined;
  slug?: string | undefined;
  seriesId?: number | undefined;
  titleId?: number | undefined;
  issueNumber?: string | undefined;
  name?: string | undefined;
  solicitation?: string | undefined;
  releaseDate?: string | undefined;
  coverUrl?: string | undefined;
  upc?: string | undefined;
  lunarCode?: string | undefined;
  universalCode?: string | undefined;
  diamondCode?: string | null | undefined;
  series?: LookupByDistributorCodeSeries | undefined;
  publisher?: LookupByDistributorCodePublisher | undefined;
};

export type LookupByDistributorCodeVariant = {
  variantId?: string | null | undefined;
  variantName?: string | undefined;
  coverUrl?: string | undefined;
  upc?: string | undefined;
  lunarCode?: string | undefined;
  universalCode?: string | undefined;
  diamondCode?: string | null | undefined;
};

/**
 * Success
 */
export type LookupByDistributorCodeResponseBody = {
  data?: LookupByDistributorCodeData | undefined;
  suggestedVariantId?: number | undefined;
  variants?: Array<LookupByDistributorCodeVariant> | undefined;
};

export type LookupByDistributorCodeResponse = {
  headers: { [k: string]: Array<string> };
  result: LookupByDistributorCodeResponseBody;
};

/** @internal */
export type LookupByDistributorCodeRequest$Outbound = {
  code: string;
};

/** @internal */
export const LookupByDistributorCodeRequest$outboundSchema: z.ZodMiniType<
  LookupByDistributorCodeRequest$Outbound,
  LookupByDistributorCodeRequest
> = z.object({
  code: z.string(),
});

export function lookupByDistributorCodeRequestToJSON(
  lookupByDistributorCodeRequest: LookupByDistributorCodeRequest,
): string {
  return JSON.stringify(
    LookupByDistributorCodeRequest$outboundSchema.parse(
      lookupByDistributorCodeRequest,
    ),
  );
}

/** @internal */
export const LookupByDistributorCodeMatchVariant$inboundSchema: z.ZodMiniType<
  LookupByDistributorCodeMatchVariant,
  unknown
> = z.pipe(
  z.object({
    variant_id: z.optional(z.nullable(types.string())),
    variant_name: types.optional(types.string()),
    cover_url: types.optional(types.string()),
    upc: types.optional(types.string()),
    lunar_code: types.optional(types.string()),
    universal_code: z.optional(z.nullable(types.string())),
    diamond_code: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "variant_id": "variantId",
      "variant_name": "variantName",
      "cover_url": "coverUrl",
      "lunar_code": "lunarCode",
      "universal_code": "universalCode",
      "diamond_code": "diamondCode",
    });
  }),
);

export function lookupByDistributorCodeMatchVariantFromJSON(
  jsonString: string,
): SafeParseResult<LookupByDistributorCodeMatchVariant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LookupByDistributorCodeMatchVariant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByDistributorCodeMatchVariant' from JSON`,
  );
}

/** @internal */
export const LookupByDistributorCodeMatch$inboundSchema: z.ZodMiniType<
  LookupByDistributorCodeMatch,
  unknown
> = z.pipe(
  z.object({
    issue_id: types.optional(types.number()),
    series_name: types.optional(types.string()),
    series_id: types.optional(types.number()),
    issue_number: types.optional(types.string()),
    cover_url: types.optional(types.string()),
    variant_name: z.optional(z.nullable(types.string())),
    suggested_variant_id: z.optional(z.nullable(types.string())),
    variants: types.optional(
      z.array(z.lazy(() => LookupByDistributorCodeMatchVariant$inboundSchema)),
    ),
    publisher_name: types.optional(types.string()),
    release_date: types.optional(types.string()),
    start_year: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "issue_id": "issueId",
      "series_name": "seriesName",
      "series_id": "seriesId",
      "issue_number": "issueNumber",
      "cover_url": "coverUrl",
      "variant_name": "variantName",
      "suggested_variant_id": "suggestedVariantId",
      "publisher_name": "publisherName",
      "release_date": "releaseDate",
      "start_year": "startYear",
    });
  }),
);

export function lookupByDistributorCodeMatchFromJSON(
  jsonString: string,
): SafeParseResult<LookupByDistributorCodeMatch, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByDistributorCodeMatch$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByDistributorCodeMatch' from JSON`,
  );
}

/** @internal */
export const LookupByDistributorCodeSeries$inboundSchema: z.ZodMiniType<
  LookupByDistributorCodeSeries,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
    slug: types.optional(types.string()),
    start_year: types.optional(types.number()),
    volume_number: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "start_year": "startYear",
      "volume_number": "volumeNumber",
    });
  }),
);

export function lookupByDistributorCodeSeriesFromJSON(
  jsonString: string,
): SafeParseResult<LookupByDistributorCodeSeries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByDistributorCodeSeries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByDistributorCodeSeries' from JSON`,
  );
}

/** @internal */
export const LookupByDistributorCodePublisher$inboundSchema: z.ZodMiniType<
  LookupByDistributorCodePublisher,
  unknown
> = z.object({
  id: types.optional(types.number()),
  name: types.optional(types.string()),
  slug: types.optional(types.string()),
});

export function lookupByDistributorCodePublisherFromJSON(
  jsonString: string,
): SafeParseResult<LookupByDistributorCodePublisher, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByDistributorCodePublisher$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByDistributorCodePublisher' from JSON`,
  );
}

/** @internal */
export const LookupByDistributorCodeData$inboundSchema: z.ZodMiniType<
  LookupByDistributorCodeData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    slug: types.optional(types.string()),
    series_id: types.optional(types.number()),
    title_id: types.optional(types.number()),
    issue_number: types.optional(types.string()),
    name: types.optional(types.string()),
    solicitation: types.optional(types.string()),
    release_date: types.optional(types.string()),
    cover_url: types.optional(types.string()),
    upc: types.optional(types.string()),
    lunar_code: types.optional(types.string()),
    universal_code: types.optional(types.string()),
    diamond_code: z.optional(z.nullable(types.string())),
    series: types.optional(
      z.lazy(() => LookupByDistributorCodeSeries$inboundSchema),
    ),
    publisher: types.optional(
      z.lazy(() => LookupByDistributorCodePublisher$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "series_id": "seriesId",
      "title_id": "titleId",
      "issue_number": "issueNumber",
      "release_date": "releaseDate",
      "cover_url": "coverUrl",
      "lunar_code": "lunarCode",
      "universal_code": "universalCode",
      "diamond_code": "diamondCode",
    });
  }),
);

export function lookupByDistributorCodeDataFromJSON(
  jsonString: string,
): SafeParseResult<LookupByDistributorCodeData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByDistributorCodeData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByDistributorCodeData' from JSON`,
  );
}

/** @internal */
export const LookupByDistributorCodeVariant$inboundSchema: z.ZodMiniType<
  LookupByDistributorCodeVariant,
  unknown
> = z.pipe(
  z.object({
    variant_id: z.optional(z.nullable(types.string())),
    variant_name: types.optional(types.string()),
    cover_url: types.optional(types.string()),
    upc: types.optional(types.string()),
    lunar_code: types.optional(types.string()),
    universal_code: types.optional(types.string()),
    diamond_code: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "variant_id": "variantId",
      "variant_name": "variantName",
      "cover_url": "coverUrl",
      "lunar_code": "lunarCode",
      "universal_code": "universalCode",
      "diamond_code": "diamondCode",
    });
  }),
);

export function lookupByDistributorCodeVariantFromJSON(
  jsonString: string,
): SafeParseResult<LookupByDistributorCodeVariant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByDistributorCodeVariant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByDistributorCodeVariant' from JSON`,
  );
}

/** @internal */
export const LookupByDistributorCodeResponseBody$inboundSchema: z.ZodMiniType<
  LookupByDistributorCodeResponseBody,
  unknown
> = z.pipe(
  z.object({
    data: types.optional(
      z.lazy(() => LookupByDistributorCodeData$inboundSchema),
    ),
    suggested_variant_id: types.optional(types.number()),
    variants: types.optional(
      z.array(z.lazy(() => LookupByDistributorCodeVariant$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "suggested_variant_id": "suggestedVariantId",
    });
  }),
);

export function lookupByDistributorCodeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<LookupByDistributorCodeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LookupByDistributorCodeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByDistributorCodeResponseBody' from JSON`,
  );
}

/** @internal */
export const LookupByDistributorCodeResponse$inboundSchema: z.ZodMiniType<
  LookupByDistributorCodeResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => LookupByDistributorCodeResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function lookupByDistributorCodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<LookupByDistributorCodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupByDistributorCodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupByDistributorCodeResponse' from JSON`,
  );
}
