/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type MarkAsUnreadRequestBody = {
  /**
   * Specific variant ID (optional).
   */
  variantId?: number | null | undefined;
};

export type MarkAsUnreadRequest = {
  /**
   * The issue ID.
   */
  issueId: number;
  body?: MarkAsUnreadRequestBody | undefined;
};

export type MarkAsUnreadResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type MarkAsUnreadRequestBody$Outbound = {
  variant_id?: number | null | undefined;
};

/** @internal */
export const MarkAsUnreadRequestBody$outboundSchema: z.ZodMiniType<
  MarkAsUnreadRequestBody$Outbound,
  MarkAsUnreadRequestBody
> = z.pipe(
  z.object({
    variantId: z.optional(z.nullable(z.int())),
  }),
  z.transform((v) => {
    return remap$(v, {
      variantId: "variant_id",
    });
  }),
);

export function markAsUnreadRequestBodyToJSON(
  markAsUnreadRequestBody: MarkAsUnreadRequestBody,
): string {
  return JSON.stringify(
    MarkAsUnreadRequestBody$outboundSchema.parse(markAsUnreadRequestBody),
  );
}

/** @internal */
export type MarkAsUnreadRequest$Outbound = {
  issue_id: number;
  body?: MarkAsUnreadRequestBody$Outbound | undefined;
};

/** @internal */
export const MarkAsUnreadRequest$outboundSchema: z.ZodMiniType<
  MarkAsUnreadRequest$Outbound,
  MarkAsUnreadRequest
> = z.pipe(
  z.object({
    issueId: z.int(),
    body: z.optional(z.lazy(() => MarkAsUnreadRequestBody$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      issueId: "issue_id",
    });
  }),
);

export function markAsUnreadRequestToJSON(
  markAsUnreadRequest: MarkAsUnreadRequest,
): string {
  return JSON.stringify(
    MarkAsUnreadRequest$outboundSchema.parse(markAsUnreadRequest),
  );
}

/** @internal */
export const MarkAsUnreadResponse$inboundSchema: z.ZodMiniType<
  MarkAsUnreadResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
    });
  }),
);

export function markAsUnreadResponseFromJSON(
  jsonString: string,
): SafeParseResult<MarkAsUnreadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarkAsUnreadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarkAsUnreadResponse' from JSON`,
  );
}
