/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type MarkTheCopysOpenLoanReturnedRequestBody = {
  /**
   * The day it came back (YYYY-MM-DD). Defaults to today. Must be a valid date.
   */
  returnedAt?: string | null | undefined;
};

export type MarkTheCopysOpenLoanReturnedRequest = {
  /**
   * The collection item ID.
   */
  collectionItemId: number;
  body?: MarkTheCopysOpenLoanReturnedRequestBody | undefined;
};

export type MarkTheCopysOpenLoanReturnedData = {
  id?: number | undefined;
  loan?: string | null | undefined;
};

/**
 * Returned
 */
export type MarkTheCopysOpenLoanReturnedResponseBody = {
  data?: MarkTheCopysOpenLoanReturnedData | undefined;
};

export type MarkTheCopysOpenLoanReturnedResponse = {
  headers: { [k: string]: Array<string> };
  result: MarkTheCopysOpenLoanReturnedResponseBody;
};

/** @internal */
export type MarkTheCopysOpenLoanReturnedRequestBody$Outbound = {
  returned_at?: string | null | undefined;
};

/** @internal */
export const MarkTheCopysOpenLoanReturnedRequestBody$outboundSchema:
  z.ZodMiniType<
    MarkTheCopysOpenLoanReturnedRequestBody$Outbound,
    MarkTheCopysOpenLoanReturnedRequestBody
  > = z.pipe(
    z.object({
      returnedAt: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        returnedAt: "returned_at",
      });
    }),
  );

export function markTheCopysOpenLoanReturnedRequestBodyToJSON(
  markTheCopysOpenLoanReturnedRequestBody:
    MarkTheCopysOpenLoanReturnedRequestBody,
): string {
  return JSON.stringify(
    MarkTheCopysOpenLoanReturnedRequestBody$outboundSchema.parse(
      markTheCopysOpenLoanReturnedRequestBody,
    ),
  );
}

/** @internal */
export type MarkTheCopysOpenLoanReturnedRequest$Outbound = {
  collectionItem_id: number;
  body?: MarkTheCopysOpenLoanReturnedRequestBody$Outbound | undefined;
};

/** @internal */
export const MarkTheCopysOpenLoanReturnedRequest$outboundSchema: z.ZodMiniType<
  MarkTheCopysOpenLoanReturnedRequest$Outbound,
  MarkTheCopysOpenLoanReturnedRequest
> = z.pipe(
  z.object({
    collectionItemId: z.int(),
    body: z.optional(
      z.lazy(() => MarkTheCopysOpenLoanReturnedRequestBody$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      collectionItemId: "collectionItem_id",
    });
  }),
);

export function markTheCopysOpenLoanReturnedRequestToJSON(
  markTheCopysOpenLoanReturnedRequest: MarkTheCopysOpenLoanReturnedRequest,
): string {
  return JSON.stringify(
    MarkTheCopysOpenLoanReturnedRequest$outboundSchema.parse(
      markTheCopysOpenLoanReturnedRequest,
    ),
  );
}

/** @internal */
export const MarkTheCopysOpenLoanReturnedData$inboundSchema: z.ZodMiniType<
  MarkTheCopysOpenLoanReturnedData,
  unknown
> = z.object({
  id: types.optional(types.number()),
  loan: z.optional(z.nullable(types.string())),
});

export function markTheCopysOpenLoanReturnedDataFromJSON(
  jsonString: string,
): SafeParseResult<MarkTheCopysOpenLoanReturnedData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarkTheCopysOpenLoanReturnedData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarkTheCopysOpenLoanReturnedData' from JSON`,
  );
}

/** @internal */
export const MarkTheCopysOpenLoanReturnedResponseBody$inboundSchema:
  z.ZodMiniType<MarkTheCopysOpenLoanReturnedResponseBody, unknown> = z.object({
    data: types.optional(
      z.lazy(() => MarkTheCopysOpenLoanReturnedData$inboundSchema),
    ),
  });

export function markTheCopysOpenLoanReturnedResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  MarkTheCopysOpenLoanReturnedResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MarkTheCopysOpenLoanReturnedResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'MarkTheCopysOpenLoanReturnedResponseBody' from JSON`,
  );
}

/** @internal */
export const MarkTheCopysOpenLoanReturnedResponse$inboundSchema: z.ZodMiniType<
  MarkTheCopysOpenLoanReturnedResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() =>
      MarkTheCopysOpenLoanReturnedResponseBody$inboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function markTheCopysOpenLoanReturnedResponseFromJSON(
  jsonString: string,
): SafeParseResult<MarkTheCopysOpenLoanReturnedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MarkTheCopysOpenLoanReturnedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarkTheCopysOpenLoanReturnedResponse' from JSON`,
  );
}
