/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SaveListRequest = {
  /**
   * The list ID.
   */
  listId: number;
};

/**
 * Saved
 */
export type SaveListResponseBody2 = {
  message?: string | undefined;
  saved?: boolean | undefined;
  savesCount?: number | undefined;
};

/**
 * Already Saved
 */
export type SaveListResponseBody1 = {
  message?: string | undefined;
  saved?: boolean | undefined;
};

export type SaveListResponseResult =
  | SaveListResponseBody1
  | SaveListResponseBody2;

export type SaveListResponse = {
  headers: { [k: string]: Array<string> };
  result: SaveListResponseBody1 | SaveListResponseBody2;
};

/** @internal */
export type SaveListRequest$Outbound = {
  list_id: number;
};

/** @internal */
export const SaveListRequest$outboundSchema: z.ZodMiniType<
  SaveListRequest$Outbound,
  SaveListRequest
> = z.pipe(
  z.object({
    listId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      listId: "list_id",
    });
  }),
);

export function saveListRequestToJSON(
  saveListRequest: SaveListRequest,
): string {
  return JSON.stringify(SaveListRequest$outboundSchema.parse(saveListRequest));
}

/** @internal */
export const SaveListResponseBody2$inboundSchema: z.ZodMiniType<
  SaveListResponseBody2,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    saved: types.optional(types.boolean()),
    saves_count: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "saves_count": "savesCount",
    });
  }),
);

export function saveListResponseBody2FromJSON(
  jsonString: string,
): SafeParseResult<SaveListResponseBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SaveListResponseBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SaveListResponseBody2' from JSON`,
  );
}

/** @internal */
export const SaveListResponseBody1$inboundSchema: z.ZodMiniType<
  SaveListResponseBody1,
  unknown
> = z.object({
  message: types.optional(types.string()),
  saved: types.optional(types.boolean()),
});

export function saveListResponseBody1FromJSON(
  jsonString: string,
): SafeParseResult<SaveListResponseBody1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SaveListResponseBody1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SaveListResponseBody1' from JSON`,
  );
}

/** @internal */
export const SaveListResponseResult$inboundSchema: z.ZodMiniType<
  SaveListResponseResult,
  unknown
> = smartUnion([
  z.lazy(() => SaveListResponseBody1$inboundSchema),
  z.lazy(() => SaveListResponseBody2$inboundSchema),
]);

export function saveListResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<SaveListResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SaveListResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SaveListResponseResult' from JSON`,
  );
}

/** @internal */
export const SaveListResponse$inboundSchema: z.ZodMiniType<
  SaveListResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: smartUnion([
      z.lazy(() => SaveListResponseBody1$inboundSchema),
      z.lazy(() => SaveListResponseBody2$inboundSchema),
    ]),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function saveListResponseFromJSON(
  jsonString: string,
): SafeParseResult<SaveListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SaveListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SaveListResponse' from JSON`,
  );
}
