/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type StopAListUpdatingItselfRequest = {
  /**
   * The list ID.
   */
  listId: number;
};

export type StopAListUpdatingItselfData = {
  id?: number | undefined;
  entityType?: string | undefined;
};

/**
 * Success
 */
export type StopAListUpdatingItselfResponseBody = {
  data?: StopAListUpdatingItselfData | undefined;
};

export type StopAListUpdatingItselfResponse = {
  headers: { [k: string]: Array<string> };
  result: StopAListUpdatingItselfResponseBody;
};

/** @internal */
export type StopAListUpdatingItselfRequest$Outbound = {
  list_id: number;
};

/** @internal */
export const StopAListUpdatingItselfRequest$outboundSchema: z.ZodMiniType<
  StopAListUpdatingItselfRequest$Outbound,
  StopAListUpdatingItselfRequest
> = z.pipe(
  z.object({
    listId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      listId: "list_id",
    });
  }),
);

export function stopAListUpdatingItselfRequestToJSON(
  stopAListUpdatingItselfRequest: StopAListUpdatingItselfRequest,
): string {
  return JSON.stringify(
    StopAListUpdatingItselfRequest$outboundSchema.parse(
      stopAListUpdatingItselfRequest,
    ),
  );
}

/** @internal */
export const StopAListUpdatingItselfData$inboundSchema: z.ZodMiniType<
  StopAListUpdatingItselfData,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.number()),
    entity_type: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "entity_type": "entityType",
    });
  }),
);

export function stopAListUpdatingItselfDataFromJSON(
  jsonString: string,
): SafeParseResult<StopAListUpdatingItselfData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StopAListUpdatingItselfData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StopAListUpdatingItselfData' from JSON`,
  );
}

/** @internal */
export const StopAListUpdatingItselfResponseBody$inboundSchema: z.ZodMiniType<
  StopAListUpdatingItselfResponseBody,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => StopAListUpdatingItselfData$inboundSchema)),
});

export function stopAListUpdatingItselfResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<StopAListUpdatingItselfResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      StopAListUpdatingItselfResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StopAListUpdatingItselfResponseBody' from JSON`,
  );
}

/** @internal */
export const StopAListUpdatingItselfResponse$inboundSchema: z.ZodMiniType<
  StopAListUpdatingItselfResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => StopAListUpdatingItselfResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function stopAListUpdatingItselfResponseFromJSON(
  jsonString: string,
): SafeParseResult<StopAListUpdatingItselfResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StopAListUpdatingItselfResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StopAListUpdatingItselfResponse' from JSON`,
  );
}
