/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SubscribeTheAuthenticatedUserToTheNewsletterResponseBody = {
  message?: string | undefined;
  subscribed?: boolean | undefined;
};

export type SubscribeTheAuthenticatedUserToTheNewsletterResponse = {
  headers: { [k: string]: Array<string> };
  result: SubscribeTheAuthenticatedUserToTheNewsletterResponseBody;
};

/** @internal */
export const SubscribeTheAuthenticatedUserToTheNewsletterResponseBody$inboundSchema:
  z.ZodMiniType<
    SubscribeTheAuthenticatedUserToTheNewsletterResponseBody,
    unknown
  > = z.object({
    message: types.optional(types.string()),
    subscribed: types.optional(types.boolean()),
  });

export function subscribeTheAuthenticatedUserToTheNewsletterResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  SubscribeTheAuthenticatedUserToTheNewsletterResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SubscribeTheAuthenticatedUserToTheNewsletterResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'SubscribeTheAuthenticatedUserToTheNewsletterResponseBody' from JSON`,
  );
}

/** @internal */
export const SubscribeTheAuthenticatedUserToTheNewsletterResponse$inboundSchema:
  z.ZodMiniType<SubscribeTheAuthenticatedUserToTheNewsletterResponse, unknown> =
    z.pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result: z.lazy(() =>
          SubscribeTheAuthenticatedUserToTheNewsletterResponseBody$inboundSchema
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function subscribeTheAuthenticatedUserToTheNewsletterResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  SubscribeTheAuthenticatedUserToTheNewsletterResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SubscribeTheAuthenticatedUserToTheNewsletterResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SubscribeTheAuthenticatedUserToTheNewsletterResponse' from JSON`,
  );
}
