/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type UnlikeListRequest = {
  /**
   * The list ID.
   */
  listId: number;
};

/**
 * Not Liked
 */
export type UnlikeListResponseBody2 = {
  message?: string | undefined;
  liked?: boolean | undefined;
};

/**
 * Unliked
 */
export type UnlikeListResponseBody1 = {
  message?: string | undefined;
  liked?: boolean | undefined;
  likesCount?: number | undefined;
};

export type UnlikeListResponseBody =
  | UnlikeListResponseBody1
  | UnlikeListResponseBody2;

export type UnlikeListResponse = {
  headers: { [k: string]: Array<string> };
  result: UnlikeListResponseBody1 | UnlikeListResponseBody2;
};

/** @internal */
export type UnlikeListRequest$Outbound = {
  list_id: number;
};

/** @internal */
export const UnlikeListRequest$outboundSchema: z.ZodMiniType<
  UnlikeListRequest$Outbound,
  UnlikeListRequest
> = z.pipe(
  z.object({
    listId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      listId: "list_id",
    });
  }),
);

export function unlikeListRequestToJSON(
  unlikeListRequest: UnlikeListRequest,
): string {
  return JSON.stringify(
    UnlikeListRequest$outboundSchema.parse(unlikeListRequest),
  );
}

/** @internal */
export const UnlikeListResponseBody2$inboundSchema: z.ZodMiniType<
  UnlikeListResponseBody2,
  unknown
> = z.object({
  message: types.optional(types.string()),
  liked: types.optional(types.boolean()),
});

export function unlikeListResponseBody2FromJSON(
  jsonString: string,
): SafeParseResult<UnlikeListResponseBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnlikeListResponseBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnlikeListResponseBody2' from JSON`,
  );
}

/** @internal */
export const UnlikeListResponseBody1$inboundSchema: z.ZodMiniType<
  UnlikeListResponseBody1,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    liked: types.optional(types.boolean()),
    likes_count: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "likes_count": "likesCount",
    });
  }),
);

export function unlikeListResponseBody1FromJSON(
  jsonString: string,
): SafeParseResult<UnlikeListResponseBody1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnlikeListResponseBody1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnlikeListResponseBody1' from JSON`,
  );
}

/** @internal */
export const UnlikeListResponseBody$inboundSchema: z.ZodMiniType<
  UnlikeListResponseBody,
  unknown
> = smartUnion([
  z.lazy(() => UnlikeListResponseBody1$inboundSchema),
  z.lazy(() => UnlikeListResponseBody2$inboundSchema),
]);

export function unlikeListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UnlikeListResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnlikeListResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnlikeListResponseBody' from JSON`,
  );
}

/** @internal */
export const UnlikeListResponse$inboundSchema: z.ZodMiniType<
  UnlikeListResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: smartUnion([
      z.lazy(() => UnlikeListResponseBody1$inboundSchema),
      z.lazy(() => UnlikeListResponseBody2$inboundSchema),
    ]),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function unlikeListResponseFromJSON(
  jsonString: string,
): SafeParseResult<UnlikeListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnlikeListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnlikeListResponse' from JSON`,
  );
}
