/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type UpdateFollowPreferencesRequestBody = {
  /**
   * Receive email notifications.
   */
  emailNotifications?: boolean | undefined;
  /**
   * Receive push notifications.
   */
  pushNotifications?: boolean | undefined;
};

export type UpdateFollowPreferencesRequest = {
  /**
   * The content type (title, character, podcast, creator, publisher, team, story_arc, comic_shop, event, user).
   */
  type: string;
  /**
   * The ID of the followed content.
   */
  id: number;
  body?: UpdateFollowPreferencesRequestBody | undefined;
};

export type UpdateFollowPreferencesPreferences = {
  emailNotifications?: boolean | undefined;
  pushNotifications?: boolean | undefined;
};

/**
 * Success
 */
export type UpdateFollowPreferencesResponseBody = {
  message?: string | undefined;
  preferences?: UpdateFollowPreferencesPreferences | undefined;
};

export type UpdateFollowPreferencesResponse = {
  headers: { [k: string]: Array<string> };
  result: UpdateFollowPreferencesResponseBody;
};

/** @internal */
export type UpdateFollowPreferencesRequestBody$Outbound = {
  email_notifications?: boolean | undefined;
  push_notifications?: boolean | undefined;
};

/** @internal */
export const UpdateFollowPreferencesRequestBody$outboundSchema: z.ZodMiniType<
  UpdateFollowPreferencesRequestBody$Outbound,
  UpdateFollowPreferencesRequestBody
> = z.pipe(
  z.object({
    emailNotifications: z.optional(z.boolean()),
    pushNotifications: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      emailNotifications: "email_notifications",
      pushNotifications: "push_notifications",
    });
  }),
);

export function updateFollowPreferencesRequestBodyToJSON(
  updateFollowPreferencesRequestBody: UpdateFollowPreferencesRequestBody,
): string {
  return JSON.stringify(
    UpdateFollowPreferencesRequestBody$outboundSchema.parse(
      updateFollowPreferencesRequestBody,
    ),
  );
}

/** @internal */
export type UpdateFollowPreferencesRequest$Outbound = {
  type: string;
  id: number;
  body?: UpdateFollowPreferencesRequestBody$Outbound | undefined;
};

/** @internal */
export const UpdateFollowPreferencesRequest$outboundSchema: z.ZodMiniType<
  UpdateFollowPreferencesRequest$Outbound,
  UpdateFollowPreferencesRequest
> = z.object({
  type: z.string(),
  id: z.int(),
  body: z.optional(
    z.lazy(() => UpdateFollowPreferencesRequestBody$outboundSchema),
  ),
});

export function updateFollowPreferencesRequestToJSON(
  updateFollowPreferencesRequest: UpdateFollowPreferencesRequest,
): string {
  return JSON.stringify(
    UpdateFollowPreferencesRequest$outboundSchema.parse(
      updateFollowPreferencesRequest,
    ),
  );
}

/** @internal */
export const UpdateFollowPreferencesPreferences$inboundSchema: z.ZodMiniType<
  UpdateFollowPreferencesPreferences,
  unknown
> = z.pipe(
  z.object({
    email_notifications: types.optional(types.boolean()),
    push_notifications: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "email_notifications": "emailNotifications",
      "push_notifications": "pushNotifications",
    });
  }),
);

export function updateFollowPreferencesPreferencesFromJSON(
  jsonString: string,
): SafeParseResult<UpdateFollowPreferencesPreferences, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateFollowPreferencesPreferences$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateFollowPreferencesPreferences' from JSON`,
  );
}

/** @internal */
export const UpdateFollowPreferencesResponseBody$inboundSchema: z.ZodMiniType<
  UpdateFollowPreferencesResponseBody,
  unknown
> = z.object({
  message: types.optional(types.string()),
  preferences: types.optional(
    z.lazy(() => UpdateFollowPreferencesPreferences$inboundSchema),
  ),
});

export function updateFollowPreferencesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateFollowPreferencesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateFollowPreferencesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateFollowPreferencesResponseBody' from JSON`,
  );
}

/** @internal */
export const UpdateFollowPreferencesResponse$inboundSchema: z.ZodMiniType<
  UpdateFollowPreferencesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => UpdateFollowPreferencesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function updateFollowPreferencesResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateFollowPreferencesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateFollowPreferencesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateFollowPreferencesResponse' from JSON`,
  );
}
