/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * The list status. One of: `published`, `draft`.
 */
export const Status = {
  Published: "published",
  Draft: "draft",
} as const;
/**
 * The list status. One of: `published`, `draft`.
 */
export type Status = ClosedEnum<typeof Status>;

export type UpdateListRequestBody = {
  /**
   * List title (max 100 chars).
   */
  title?: string | undefined;
  /**
   * List description (max 500 chars).
   */
  description?: string | null | undefined;
  /**
   * Whether items are ranked.
   */
  isRanked?: boolean | undefined;
  /**
   * Whether the list is private.
   */
  isPrivate?: boolean | undefined;
  /**
   * The list status. One of: `published`, `draft`.
   */
  status?: Status | undefined;
};

export type UpdateListRequest = {
  /**
   * The list ID.
   */
  listId: number;
  body?: UpdateListRequestBody | undefined;
};

export type UpdateListData = {
  id?: number | undefined;
  title?: string | undefined;
  description?: string | undefined;
};

/**
 * Success
 */
export type UpdateListResponseBody = {
  data?: UpdateListData | undefined;
};

export type UpdateListResponse = {
  headers: { [k: string]: Array<string> };
  result: UpdateListResponseBody;
};

/** @internal */
export const Status$outboundSchema: z.ZodMiniEnum<typeof Status> = z.enum(
  Status,
);

/** @internal */
export type UpdateListRequestBody$Outbound = {
  title?: string | undefined;
  description?: string | null | undefined;
  is_ranked?: boolean | undefined;
  is_private?: boolean | undefined;
  status?: string | undefined;
};

/** @internal */
export const UpdateListRequestBody$outboundSchema: z.ZodMiniType<
  UpdateListRequestBody$Outbound,
  UpdateListRequestBody
> = z.pipe(
  z.object({
    title: z.optional(z.string()),
    description: z.optional(z.nullable(z.string())),
    isRanked: z.optional(z.boolean()),
    isPrivate: z.optional(z.boolean()),
    status: z.optional(Status$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      isRanked: "is_ranked",
      isPrivate: "is_private",
    });
  }),
);

export function updateListRequestBodyToJSON(
  updateListRequestBody: UpdateListRequestBody,
): string {
  return JSON.stringify(
    UpdateListRequestBody$outboundSchema.parse(updateListRequestBody),
  );
}

/** @internal */
export type UpdateListRequest$Outbound = {
  list_id: number;
  body?: UpdateListRequestBody$Outbound | undefined;
};

/** @internal */
export const UpdateListRequest$outboundSchema: z.ZodMiniType<
  UpdateListRequest$Outbound,
  UpdateListRequest
> = z.pipe(
  z.object({
    listId: z.int(),
    body: z.optional(z.lazy(() => UpdateListRequestBody$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      listId: "list_id",
    });
  }),
);

export function updateListRequestToJSON(
  updateListRequest: UpdateListRequest,
): string {
  return JSON.stringify(
    UpdateListRequest$outboundSchema.parse(updateListRequest),
  );
}

/** @internal */
export const UpdateListData$inboundSchema: z.ZodMiniType<
  UpdateListData,
  unknown
> = z.object({
  id: types.optional(types.number()),
  title: types.optional(types.string()),
  description: types.optional(types.string()),
});

export function updateListDataFromJSON(
  jsonString: string,
): SafeParseResult<UpdateListData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateListData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateListData' from JSON`,
  );
}

/** @internal */
export const UpdateListResponseBody$inboundSchema: z.ZodMiniType<
  UpdateListResponseBody,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => UpdateListData$inboundSchema)),
});

export function updateListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateListResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateListResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateListResponseBody' from JSON`,
  );
}

/** @internal */
export const UpdateListResponse$inboundSchema: z.ZodMiniType<
  UpdateListResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => UpdateListResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function updateListResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateListResponse' from JSON`,
  );
}
