/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ViewYourMonthlyReadingCalendarRequest = {
  /**
   * UTC year; defaults to the current year.
   */
  year?: number | undefined;
  /**
   * Month from 1 to 12; defaults to the current UTC month.
   */
  month?: number | undefined;
  /**
   * Page number, starting at 1.
   */
  page?: number | undefined;
};

/**
 * Success.
 */
export type ViewYourMonthlyReadingCalendarResponseBody = {
  data?: Array<any> | undefined;
  currentPage?: number | undefined;
  lastPage?: number | undefined;
  total?: number | undefined;
};

export type ViewYourMonthlyReadingCalendarResponse = {
  headers: { [k: string]: Array<string> };
  result: ViewYourMonthlyReadingCalendarResponseBody;
};

/** @internal */
export type ViewYourMonthlyReadingCalendarRequest$Outbound = {
  year?: number | undefined;
  month?: number | undefined;
  page?: number | undefined;
};

/** @internal */
export const ViewYourMonthlyReadingCalendarRequest$outboundSchema:
  z.ZodMiniType<
    ViewYourMonthlyReadingCalendarRequest$Outbound,
    ViewYourMonthlyReadingCalendarRequest
  > = z.object({
    year: z.optional(z.int()),
    month: z.optional(z.int()),
    page: z.optional(z.int()),
  });

export function viewYourMonthlyReadingCalendarRequestToJSON(
  viewYourMonthlyReadingCalendarRequest: ViewYourMonthlyReadingCalendarRequest,
): string {
  return JSON.stringify(
    ViewYourMonthlyReadingCalendarRequest$outboundSchema.parse(
      viewYourMonthlyReadingCalendarRequest,
    ),
  );
}

/** @internal */
export const ViewYourMonthlyReadingCalendarResponseBody$inboundSchema:
  z.ZodMiniType<ViewYourMonthlyReadingCalendarResponseBody, unknown> = z.pipe(
    z.object({
      data: types.optional(z.array(z.any())),
      current_page: types.optional(types.number()),
      last_page: types.optional(types.number()),
      total: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "current_page": "currentPage",
        "last_page": "lastPage",
      });
    }),
  );

export function viewYourMonthlyReadingCalendarResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  ViewYourMonthlyReadingCalendarResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ViewYourMonthlyReadingCalendarResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ViewYourMonthlyReadingCalendarResponseBody' from JSON`,
  );
}

/** @internal */
export const ViewYourMonthlyReadingCalendarResponse$inboundSchema:
  z.ZodMiniType<ViewYourMonthlyReadingCalendarResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        ViewYourMonthlyReadingCalendarResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function viewYourMonthlyReadingCalendarResponseFromJSON(
  jsonString: string,
): SafeParseResult<ViewYourMonthlyReadingCalendarResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ViewYourMonthlyReadingCalendarResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ViewYourMonthlyReadingCalendarResponse' from JSON`,
  );
}
