/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ViewYearlyReadingStatisticsRequest = {
  /**
   * UTC year; defaults to the current year.
   */
  year?: number | undefined;
};

export type Progress = {
  year?: number | undefined;
  target?: number | undefined;
  readCount?: number | undefined;
  percent?: number | undefined;
  completed?: boolean | undefined;
  expectedReads?: number | undefined;
  paceDifference?: number | undefined;
  remaining?: number | undefined;
  readsPerWeek?: number | undefined;
  editable?: boolean | undefined;
  lastYearReads?: number | undefined;
  suggestedTarget?: number | undefined;
  timezone?: string | undefined;
  isPublic?: boolean | undefined;
  notifyMilestones?: boolean | undefined;
  notifyLapses?: boolean | undefined;
  emailUpdates?: boolean | undefined;
  shareUrl?: string | null | undefined;
};

export type Day = {
  date?: string | undefined;
  count?: number | undefined;
  total?: number | undefined;
  expected?: number | undefined;
};

export type Months = {
  one?: number | undefined;
  two?: number | undefined;
  three?: number | undefined;
  four?: number | undefined;
  five?: number | undefined;
  six?: number | undefined;
  seven?: number | undefined;
  eight?: number | undefined;
  nine?: number | undefined;
  ten?: number | undefined;
  eleven?: number | undefined;
  twelve?: number | undefined;
};

export type Breakdowns = {
  series?: Array<any> | undefined;
  publishers?: Array<any> | undefined;
  creators?: Array<any> | undefined;
  characters?: Array<any> | undefined;
};

export type ViewYearlyReadingStatisticsData = {
  progress?: Progress | undefined;
  days?: Array<Day> | undefined;
  months?: Months | undefined;
  breakdowns?: Breakdowns | undefined;
  activeDays?: number | undefined;
  longestStreak?: number | undefined;
  currentStreak?: number | undefined;
  projectedReads?: number | undefined;
  projectedFinish?: string | null | undefined;
  thisWeek?: number | undefined;
  thisMonth?: number | undefined;
  monthlyTarget?: number | undefined;
  busiestMonth?: string | null | undefined;
  finishedSeries?: Array<any> | undefined;
};

/**
 * Success.
 */
export type ViewYearlyReadingStatisticsResponseBody = {
  data?: ViewYearlyReadingStatisticsData | undefined;
  years?: Array<number> | undefined;
};

export type ViewYearlyReadingStatisticsResponse = {
  headers: { [k: string]: Array<string> };
  result: ViewYearlyReadingStatisticsResponseBody;
};

/** @internal */
export type ViewYearlyReadingStatisticsRequest$Outbound = {
  year?: number | undefined;
};

/** @internal */
export const ViewYearlyReadingStatisticsRequest$outboundSchema: z.ZodMiniType<
  ViewYearlyReadingStatisticsRequest$Outbound,
  ViewYearlyReadingStatisticsRequest
> = z.object({
  year: z.optional(z.int()),
});

export function viewYearlyReadingStatisticsRequestToJSON(
  viewYearlyReadingStatisticsRequest: ViewYearlyReadingStatisticsRequest,
): string {
  return JSON.stringify(
    ViewYearlyReadingStatisticsRequest$outboundSchema.parse(
      viewYearlyReadingStatisticsRequest,
    ),
  );
}

/** @internal */
export const Progress$inboundSchema: z.ZodMiniType<Progress, unknown> = z.pipe(
  z.object({
    year: types.optional(types.number()),
    target: types.optional(types.number()),
    read_count: types.optional(types.number()),
    percent: types.optional(types.number()),
    completed: types.optional(types.boolean()),
    expected_reads: types.optional(types.number()),
    pace_difference: types.optional(types.number()),
    remaining: types.optional(types.number()),
    reads_per_week: types.optional(types.number()),
    editable: types.optional(types.boolean()),
    last_year_reads: types.optional(types.number()),
    suggested_target: types.optional(types.number()),
    timezone: types.optional(types.string()),
    is_public: types.optional(types.boolean()),
    notify_milestones: types.optional(types.boolean()),
    notify_lapses: types.optional(types.boolean()),
    email_updates: types.optional(types.boolean()),
    share_url: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "read_count": "readCount",
      "expected_reads": "expectedReads",
      "pace_difference": "paceDifference",
      "reads_per_week": "readsPerWeek",
      "last_year_reads": "lastYearReads",
      "suggested_target": "suggestedTarget",
      "is_public": "isPublic",
      "notify_milestones": "notifyMilestones",
      "notify_lapses": "notifyLapses",
      "email_updates": "emailUpdates",
      "share_url": "shareUrl",
    });
  }),
);

export function progressFromJSON(
  jsonString: string,
): SafeParseResult<Progress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Progress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Progress' from JSON`,
  );
}

/** @internal */
export const Day$inboundSchema: z.ZodMiniType<Day, unknown> = z.object({
  date: types.optional(types.string()),
  count: types.optional(types.number()),
  total: types.optional(types.number()),
  expected: types.optional(types.number()),
});

export function dayFromJSON(
  jsonString: string,
): SafeParseResult<Day, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Day$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Day' from JSON`,
  );
}

/** @internal */
export const Months$inboundSchema: z.ZodMiniType<Months, unknown> = z.pipe(
  z.object({
    "1": types.optional(types.number()),
    "2": types.optional(types.number()),
    "3": types.optional(types.number()),
    "4": types.optional(types.number()),
    "5": types.optional(types.number()),
    "6": types.optional(types.number()),
    "7": types.optional(types.number()),
    "8": types.optional(types.number()),
    "9": types.optional(types.number()),
    "10": types.optional(types.number()),
    "11": types.optional(types.number()),
    "12": types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "1": "one",
      "2": "two",
      "3": "three",
      "4": "four",
      "5": "five",
      "6": "six",
      "7": "seven",
      "8": "eight",
      "9": "nine",
      "10": "ten",
      "11": "eleven",
      "12": "twelve",
    });
  }),
);

export function monthsFromJSON(
  jsonString: string,
): SafeParseResult<Months, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Months$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Months' from JSON`,
  );
}

/** @internal */
export const Breakdowns$inboundSchema: z.ZodMiniType<Breakdowns, unknown> = z
  .object({
    series: types.optional(z.array(z.any())),
    publishers: types.optional(z.array(z.any())),
    creators: types.optional(z.array(z.any())),
    characters: types.optional(z.array(z.any())),
  });

export function breakdownsFromJSON(
  jsonString: string,
): SafeParseResult<Breakdowns, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Breakdowns$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Breakdowns' from JSON`,
  );
}

/** @internal */
export const ViewYearlyReadingStatisticsData$inboundSchema: z.ZodMiniType<
  ViewYearlyReadingStatisticsData,
  unknown
> = z.pipe(
  z.object({
    progress: types.optional(z.lazy(() => Progress$inboundSchema)),
    days: types.optional(z.array(z.lazy(() => Day$inboundSchema))),
    months: types.optional(z.lazy(() => Months$inboundSchema)),
    breakdowns: types.optional(z.lazy(() => Breakdowns$inboundSchema)),
    active_days: types.optional(types.number()),
    longest_streak: types.optional(types.number()),
    current_streak: types.optional(types.number()),
    projected_reads: types.optional(types.number()),
    projected_finish: z.optional(z.nullable(types.string())),
    this_week: types.optional(types.number()),
    this_month: types.optional(types.number()),
    monthly_target: types.optional(types.number()),
    busiest_month: z.optional(z.nullable(types.string())),
    finished_series: types.optional(z.array(z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_days": "activeDays",
      "longest_streak": "longestStreak",
      "current_streak": "currentStreak",
      "projected_reads": "projectedReads",
      "projected_finish": "projectedFinish",
      "this_week": "thisWeek",
      "this_month": "thisMonth",
      "monthly_target": "monthlyTarget",
      "busiest_month": "busiestMonth",
      "finished_series": "finishedSeries",
    });
  }),
);

export function viewYearlyReadingStatisticsDataFromJSON(
  jsonString: string,
): SafeParseResult<ViewYearlyReadingStatisticsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ViewYearlyReadingStatisticsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ViewYearlyReadingStatisticsData' from JSON`,
  );
}

/** @internal */
export const ViewYearlyReadingStatisticsResponseBody$inboundSchema:
  z.ZodMiniType<ViewYearlyReadingStatisticsResponseBody, unknown> = z.object({
    data: types.optional(
      z.lazy(() => ViewYearlyReadingStatisticsData$inboundSchema),
    ),
    years: types.optional(z.array(types.number())),
  });

export function viewYearlyReadingStatisticsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  ViewYearlyReadingStatisticsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ViewYearlyReadingStatisticsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ViewYearlyReadingStatisticsResponseBody' from JSON`,
  );
}

/** @internal */
export const ViewYearlyReadingStatisticsResponse$inboundSchema: z.ZodMiniType<
  ViewYearlyReadingStatisticsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => ViewYearlyReadingStatisticsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function viewYearlyReadingStatisticsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ViewYearlyReadingStatisticsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ViewYearlyReadingStatisticsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ViewYearlyReadingStatisticsResponse' from JSON`,
  );
}
